smartdevicelink/sdl_atf_test_scripts

KnownIssues.md
README.md

After @vveremeva testingm was found some issued in README. 
This commits fix it.

Fix some issues and typos

---

fabfile.py

Added path to tools and bin directories
Related to [APPLINK-29745](https://adc.luxoft.com/jira/browse/APPLINK-29745)
Please review @LuxoftAKutsan

Fix ATF's paths in fabfile

---

user_modules/shared_testcases/commonFunctions.lua

Add functions to read parameter from ini file and write to ini file

Add common functions

---

user_modules/shared_testcases/commonFunctions.lua

Now, is_table_equal can deep compare table even with diff order. But for arrays still important order!
Please review @istoimenova, @dtrunov.

Create deep compare for tables function

---

test_scripts/Polices/Policy_Table_Update/002_ATF_P_TC_PTU_AppID_NotListed_PT_DeviceConsented_SecondApp_ExternalProprieatry.lua
test_scripts/Polices/Policy_Table_Update/005_ATF_P_TC_User_requests_PTU_ExternalProprietary.lua

Common files for build SDL are removed.

---

user_modules/shared_testcases/testCasesForPolicyAppIdManagament.lua

@istoimenova and @maria-mih please review.

Added common module for appID Management scripts

---

test_scripts/Polices/ATF_Preloaded_PT_validation.lua

Add check if SDL was stopped before trying start it.
If it wasn't then wait and stop SDL after timeout
Please review @LuxoftAKutsan

Add waiting before startSDL

---

user_modules/shared_testcases/commonFunctions.lua

Added common function to get data from policy.sqlite

---

user_modules/shared_testcases/testCasesForPolicyTable.lua

Update of getting data after UPDATE_NEEDED notification.

---

files/ptu_general_default_keep_context_true.json
test_scripts/Polices/App_Permissions/013_P_ATF_KeepContext_Validation_true.lua
test_scripts/Polices/App_Permissions/182_P_ATF_KeepContext_Validation_true.lua

Feature/app permissions/app check keep context true appid

---

files/ptu_general_default_keep_context_false.json
test_scripts/Polices/App_Permissions/012_P_ATF_KeepContext_Validation_false.lua
test_scripts/Polices/App_Permissions/181_P_ATF_KeepContext_Validation_false.lua

Added script for coverage req. APPLINK-22812

---

files/ptu_general_default_steal_focus_false.json
test_scripts/Polices/App_Permissions/010_P_ATF_Steal_Focus_Validation_False.lua
test_scripts/Polices/App_Permissions/179_P_ATF_Steal_Focus_Validation_False.lua

Added script for coverage req. APPLINK-22814

---

test_scripts/Polices/App_Permissions/178_ATF_P_DISALLOWED_default_policies_And_RequestType_Validation.lua
test_scripts/Polices/App_Permissions/ATF_P_DISALLOWED_default_policies_And_RequestType_Validation.lua

Add script to check allowance RPCs with requestType assigned in default section

---

files/ptu_general_steal_focus_true.json
test_scripts/Polices/App_Permissions/008_P_ATF_StealFocus_validation_true_PTU.lua
test_scripts/Polices/App_Permissions/177_P_ATF_StealFocus_validation_true_PTU.lua

check steal_focus for app_id after PTU

Added script for coverage req. APPLINK-22901

---

files/jsons/Policies/App_Permissions/ptu_014.json
test_scripts/Polices/App_Permissions/014_ATF_P_TC_General_Result_Codes_Disallowed_Rpc_Is_Omitted_In_The_Policy_Table_Default_Group.lua
test_scripts/Polices/App_Permissions/183_ATF_P_TC_General_Result_Codes_Disallowed_Rpc_Is_Omitted_In_The_Policy_Table_Default_Group.lua

@maria-mih please review.
Please note common module is under review in another pull request https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/42

Feature/app permissions/general result codes disallowed rpc is omitted in the policy table default group

---

files/PTU_with_permissions_for_app_1234567.json
test_scripts/Polices/App_Permissions/174_ATF_HP_User_Consent_NO.lua
test_scripts/Polices/App_Permissions/ATF_HP_User_Consent_NO.lua

Add script to check User disallow permissions

---

files/PTU_with_permissions_for_app_1234567.json
test_scripts/Polices/App_Permissions/173_ATF_HP_User_Consent_Yes.lua
test_scripts/Polices/App_Permissions/ATF_HP_User_Consent_Yes.lua

Add script to check permissions consented by user

---

user_modules/shared_testcases/commonFunctions.lua

Create common function for checking db columns, change function
is_table_equal for comparing disordered arrays.

Update common functions

---

test_scripts/Polices/Validation_of_PolicyTables/005_ATF_preloaded_pt_does_not_exists.lua
test_scripts/Polices/Validation_of_PolicyTables/228_ATF_preloaded_pt_does_not_exists.lua

[Policy] log an error if PreloadedPT does not exist at the path defined in .ini file
@istoimenova please review my pull request

Created test script for case start SDL with incorrect path to Preloaded PT files

---

test_scripts/Polices/Validation_of_PolicyTables/002_ATF_preloaded_pt_invalid_optional_param.lua
test_scripts/Polices/Validation_of_PolicyTables/225_ATF_preloaded_pt_invalid_optional_param.lua

[PreloadedPT] At least one optional param has invalid type
@istoimenova please review my pull request

Created test script for case preloaded pt has one optional parameter with invalid type

---

test_scripts/Polices/App_Permissions/192_ATF_P_No_Permission_Notification_To_HMI_In_First_App_Registration.lua
test_scripts/Polices/App_Permissions/ATF_P_No_Permission_Notification_To_HMI_In_First_App_Registration.lua

Add script to check that no permission notification is sent to HMI in first app registration

---

test_scripts/Polices/App_Permissions/193_ATF_P_Default_Priority_Value_Assigned_To_App.lua
test_scripts/Polices/App_Permissions/ATF_P_Default_Priority_Value_Assigned_To_App.lua

Add script to check default priority value assigned to the app

---

user_modules/shared_testcases/commonFunctions.lua

Fix problem in get_data_policy_sql, implement method for sleep in common function

Fix common function

---

test_sets/policies_happy_paths.txt

Remove redundant files from list of test scripts

Removed files .gitkeep

---

files/jsons/Policies/user_consent/OnAppPermissionConsent.json
test_scripts/Polices/user_consent_of_Policies/126_ATF_User_consent_prompt_persists.lua

Update of script 126_ATF_User_consent_prompt_persists.lua  and adding file for it.

Update of calling RPCs. Added json fiel.

---

test_scripts/Polices/Policy_Table_Update/008_ATF_P_TC_PTS_Creation_rule.lua
user_modules/shared_testcases/testCasesForPolicyTableSnapshot.lua

Update will be also done according clarifications.

Added return result of verification for PTS

---

files/ptu_general_0000001.json
test_scripts/Polices/App_Permissions/ATF_P_OnPermissionsChange_After_PTU.lua

Add script to check OnPermissionsChange after PTU with new permissions

---

files/sdl_preloaded_pt_AlertOnlyNotifications.json
test_scripts/Polices/user_consent_of_Policies/126_ATF_User_consent_prompt_persists.lua

Script is updated after clarifications.

---

files/jsons/Policies/Policy_Table_Update/ptu_18190.json
test_scripts/Polices/Policy_Table_Update/026_ATF_P_TC_PTU_Merge_Into_LPT.lua
test_scripts/Polices/Policy_Table_Update/ATF_P_TC_PTU_Merge_Into_LPT.lua

Feature/policy table update/ptu merge into lpt

---

files/jsons/Policies/Policy_Table_Update/preloaded_18192.json
files/jsons/Policies/Policy_Table_Update/ptu_22734.json
test_scripts/Polices/Policy_Table_Update/038_ATF_P_TC_PTU_Omit_Of_Consumer_Friendly_Messages.lua
test_scripts/Polices/Policy_Table_Update/ATF_P_TC_PTU_Omit_Of_Consumer_Friendly_Messages.lua

Feature/policy table update/ptu omit of consumer friendly messages

---

files/jsons/Policies/Policy_Table_Update/ptu_19168.json
test_scripts/Polices/Policy_Table_Update/039_ATF_P_TC_PTU_SDL_Must_Remove_PTU_File_Got_From_Sync_After_Getting_The_Updates.lua
test_scripts/Polices/Policy_Table_Update/ATF_P_TC_PTU_SDL_Must_Remove_PTU_File_Got_From_Sync_After_Getting_The_Updates.lua

Feature/policy table update/ptu sdl must remove ptu file got from sync after getting the updates

---

test_scripts/Polices/Validation_of_PolicyTables/019_ATF_merge_preloaded_pt_into_local_pt_app_policies.lua
test_scripts/Polices/Validation_of_PolicyTables/238_ATF_merge_preloaded_pt_into_local_pt_app_policies.lua

[Policies] Merging rules for "app_policies" section
@istoimenova please review my pull request

Created test for check merge functionality for app_policies section

---

test_scripts/Polices/build_options/ATF_PolicyManager_changes_status_to_UPDATING_PROPRIETARY.lua

[PolicyTableUpdate] PoliciesManager changes status to “UPDATING” PROPRIETARY

---

test_scripts/Polices/Validation_of_PolicyTables/261_ATF_Validate_groups_default_policies.lua

Script is ready to be merged.

---

test_scripts/Polices/Validation_of_PolicyTables/275_ATF_P_PT_Exchanged_X_Days_After_Epoch_In_PTS.lua
test_scripts/Polices/Validation_of_PolicyTables/ATF_P_PT_Exchanged_X_Days_After_Epoch_In_PTS.lua

Add script to check pt_exchanged_x_days_after_epoch in PTS

---

user_modules/shared_testcases/commonFunctions.lua

Add functions:
1. for check PTU
2. for subscribe/unsubscribe vehicle data
3. for triggered PTU by odometer

Add new functionality to common functions

---

test_scripts/Polices/build_options/ATF_PM_change_status_UPDATE_NEEDED_after_timeout_expired.lua

Added correction for change status ready for script

---

test_scripts/Polices/Policies_Security/002_ATF_P_Policies_Performance_Requirement.lua

Added script for check policies performance requirement

---

test_scripts/Polices/ATF_QDB_initialization.lua

Fix path to files and add check for stop SDL
@tkireva Please review

Fixed crashes inside file

---

test_scripts/Polices/App_Permissions/171_ATF_HP_OnPermissionsChange_With_Assigned_Policy_After_App_Registration.lua

OnAppRegistered may come right after OnHMIStatus
Fixed check in OnPermissionsChange validation
Please review @tkireva

Fix OnPermissionsChange_With_Assigned_Policy_After_App_Registration script

---

test_scripts/Polices/build_options/ATF_P_Transfer_OnSystemRequest_toApp_PROPRIETARY.lua

UnReady.
@istoimenova please review

Add script to check transfer OnSystemRequest from HMI to mobile app

---

test_scripts/Polices/build_options/ATF_P_timeout_countdown_start_PROPRIETARY.lua

UnReady.
@istoimenova please review

PolicyTableUpdate_"timeout" countdown start

---

test_scripts/Polices/Validation_of_PolicyTables/ATF_P_Count_Of_Rejections_Sync_Out_Of_Memory.lua

Add script to check count-of_rejections_sync_out_of_memory

---

test_scripts/Polices/user_consent_of_Policies/ATF_P_Device_HashID_In_LPT.lua

Add script to check Device HashId in LPT

---

test_scripts/Polices/App_Permissions/ATF_P_ChangeRegistration_With_AppName_Not_Listed_In_NickNames.lua

Add script to check DISALLOWED for ChangeRegistration with appName which not listed in nickNames in PT

---

test_scripts/Polices/App_Permissions/ATF_P_Nickname_Validation_Before_Duplicate_Name_Validation.lua

Add script to check nickname validation before duplicate name validation

---

files/PTFromCloud_Nickname_validation.json
test_scripts/Polices/App_Permissions/ATF_P_APP_UNAUTHORIZED_If_Failed_Nickname_Validation_After_PTU.lua

Add script to check app unregistration if nickname validation is failed after PTU

---

test_scripts/Polices/Validation_of_PolicyTables/ATF_HP_Validation_Count_Of_User_Selections.lua

Add script to check count_of_user_selections in PTS

---

test_scripts/Polices/appID_Management/ATF_P_TC_Register_App_Interface_Assign_Default_Policies_To_Application_Which_Appid_Does_Not_Exist_In_LPT.lua

Feature/appid management/register app interface assign default policies to application which appid does not exist in lpt

---

user_modules/shared_testcases/commonFunctions.lua

Use NewTestSuiteNumber as local value
@tkireva Please review

Fix using Common Function

---

test_scripts/Polices/Validation_of_PolicyTables/ATF_HP_Usage_And_Error_Counts_For_AppID.lua

Add script to check usage_and_error_counts for each unique appId

---

files/jsons/Policies/appID_Management/ptu_19849.json
test_scripts/Polices/appID_Management/ATF_P_TC_Register_App_Interface_Assign_Existing_Policies_To_Application_Which_Appid_Exists_In_LPT.lua

Feature/appid management/register app interface assign existing policies to application which appid exists in lpt

---

files/ptu_for_navi_app.json
test_scripts/Polices/Policy_Table_Update/ATF_P_PTU_Trigger_On_Navi_App_Registration_And_No_Certificate.lua

Add script to check PTU trigger on Navi App registration and if no certificate in LPT

---

files/PTU_with_permissions_for_app_0000001.json
test_scripts/Polices/user_consent_of_Policies/001_ATF_HP_Device_Data_Section_Validation.lua

Add script to check device_data section in PTS

---

files/jsons/Policies/build_options/ptu_18269.json
test_scripts/Polices/build_options/ATF_P_TC_PTU_Cycleing_Through_The_URLs_During_Retry_Sequence.lua

@istoimenova please review.
Note script is designed for HTTP flow.

Feature/build option/ptu cycleing through the urls during retry sequence

---

test_scripts/Polices/App_Permissions/ATF_P_NickName_Case_Insensitivity.lua

Add script to check nickname case insensitivity

---

test_scripts/Polices/build_options/ATF_P_SDL_Send_PolicyUpdat_To_HMI_In_Case_PTU_Is_Triggered.lua

Add script to check PolicyUpdate after PTU is triggered

---

test_scripts/Polices/App_Permissions/ATF_P_DISALLOWED_App_Which_Name_Does_Not_Match_With_Nickname_In_PT.lua

Add script to check DISALLOWED app nickname does not match ones listed in Policy Table

---

test_scripts/Polices/build_options/ATF_P_PTS_creation_rule_PROPRIETARY.lua

Added script for coverage req. [PolicyTableUpdate] PTS creation rule,  PROPRIETARY.

---

test_scripts/Polices/build_options/009_ATF_P_TC_Policy_Table_Snapshot_Creation_HTTP.lua
test_scripts/Polices/build_options/012_ATF_P_TC_Policy_Table_Snapshot_Creation_HTTP.lua

012_ATF_P_TC_Policy_Table_Snapshot_Creation_HTTP.lua 
user_modules/shared_testcases/testCasesForBuildingSDLPolicyFlag.lua
@istoimenova Please review.

Added script for requirement [PolicyTableUpdate] PTS creation rule

---

test_scripts/Polices/build_options/042_ATF_P_TC_PTU_OnStatsusUpdate_Trigger_UPDATE_NEEDED_HTTP.lua

042_ATF_P_TC_PTU_OnStatsusUpdate_Trigger_UPDATE_NEEDED_HTTP.lua

Added script for requirement [PolicyTableUpdate] OnStatusUpdate trigger

---

test_scripts/Polices/build_options/043_ATF_P_TC_PTU_OnStatsusUpdate_Trigger_UPDATING_HTTP.lua

043_ATF_P_TC_PTU_OnStatsusUpdate_Trigger_UPDATING_HTTP.lua

Added test for requirement [PolicyTableUpdate] OnStatusUpdate trigger

---

test_scripts/Polices/Policy_Table_Update/018_ATF_P_TC_Sending_PTS_to_mobile_application.lua
test_scripts/Polices/Policy_Table_Update/019_ATF_P_TC_Sending_PTS_to_app_OnSystemRequest_appID_default.lua
test_scripts/Polices/Policy_Table_Update/022_ATF_P_TC_Got_PTU_from_mobile_application.lua
test_scripts/Polices/Policy_Table_Update/038_ATF_P_TC_PTU_Omit_Of_Consumer_Friendly_Messages.lua
test_scripts/Polices/Policy_Table_Update/040_ATF_P_TC_PTU_Policies_Manager_Changes_Status_To_UPDATE_NEEDED.lua
test_scripts/Polices/user_consent_of_Policies/116_ATF_Consent_timestamp.lua

First part of aborted tests
@tkireva Please review

Fix aborted tests

---

test_scripts/Polices/App_Permissions/ATF_P_Successful_Nickname_Validation.lua

Add script to check successful nickname validation

---

test_scripts/Polices/build_options/006_ATF_P_TC_PTU_Trigger_IGN_Cycles_HTTP.lua

006_ATF_P_TC_PTU_Trigger_IGN_Cycles_HTTP.lua

Added script for requirement [PTU] Trigger: ignition cycles

---

files/jsons/Policies/Related_HMI_API/ptu_24047_1.json
files/jsons/Policies/Related_HMI_API/ptu_24047_2.json
test_scripts/Polices/Related_HMI_API/ATF_P_TC_Get_Status_Update_Request_from_HMI.lua

@istoimenova please review.
Please note common module is under review in another pull request https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/42

Feature/related hmi api/get status update request from hmi

---

test_scripts/Polices/Validation_of_PolicyTables/Check_count_of_rejected_rpcs_calls.lua
user_modules/shared_testcases/commonSteps.lua
user_modules/shared_testcases/testCasesForPolicyTable.lua

@istoimenova Please review commit  	993b029

 Check count_of_rejected_rpcs_calls

---

test_scripts/Polices/Validation_of_PolicyTables/Check_app_registration_language_gui.lua
user_modules/shared_testcases/commonSteps.lua
user_modules/shared_testcases/testCasesForPolicyTable.lua

@istoimenova Please review last commit   5ccdfc4

Check updating app_registration_language_gui

---

test_scripts/Polices/Validation_of_PolicyTables/Check_count_of_rpcs_sent_in_hmi_none.lua

Check count_of_rpcs_sent_in_hmi_none

---

test_scripts/Polices/build_options/P_ATF_Register_NewApp_not_exist_inLocalPT_FinishPTU_PROPRIETARY.lua

Use common function for check value in table.
Please review @istoimenova, @tkireva

Fix accessing to policy db

---

test_scripts/Polices/Policy_Table_Update/029_ATF_P_TC_Notifying_HMI_via_OnAppPermissionChanged.lua
user_modules/shared_testcases/commonSteps.lua
user_modules/shared_testcases/testCasesForPolicyTable.lua

@istoimenova Please review commit  389d97e

Cover Notifying HMI via OnAppPermissionChanged

---

user_modules/shared_testcases/commonSteps.lua
user_modules/shared_testcases/testCasesForPolicyTable.lua

Add PTU for different sessions
Add creation PTU using user app data
Please review @istoimenova

Add common functions for PTU

---

test_scripts/Polices/build_options/020_ATF_P_TC_PTU_Validation_Failure_HTTP.lua
test_scripts/Polices/build_options/024_ATF_P_TC_PTU_Validation_Failure_HTTP.lua

024_ATF_P_TC_PTU_Validation_Failure_HTTP.lua

Added script for requirement [PolicyTableUpdate] PTU validation failure

---

test_scripts/Polices/Policy_Table_Update/028_ATF_P_TC_HMILvl_on_PTU_affected_in_BACKGROUND_or_NONE.lua

@istoimenova Please review commit  ae7776f

Cover that HMI level  None/Background  affected after PTU

---

test_scripts/Polices/Validation_of_PolicyTables/Check_count_of_removals_for_bad_behavior_REQUEST_WHILE_IN_NONE_HMI_LEVEL.lua
test_scripts/Polices/Validation_of_PolicyTables/Check_count_of_removals_for_bad_behavior_too_many_pending_requests.lua
test_scripts/Polices/Validation_of_PolicyTables/Check_count_of_removals_for_bad_behavior_too_many_requests.lua

Cover check of count_of_removals_for_bad_behavior

---

test_scripts/Polices/Policy_Table_Update/030_ATF_P_TC_Apply_PTU_and_OnPermissionChange_notify.lua
user_modules/shared_testcases/commonSteps.lua
user_modules/shared_testcases/testCasesForPolicyTable.lua

@istoimenova Please review commit ced0ce6

Cover apply PTU and OnPermissionChanges notify

---

test_scripts/Polices/build_options/046_ATF_P_TC_PTU_UTF8_Encoding_Check_HTTP.lua

046_ATF_P_TC_PTU_UTF8_Encoding_Check_HTTP.lua

Added testscript for requirement [Policies]: UTF-8 encoding

---

test_scripts/Polices/Policy_Table_Update/027_ATF_P_TC_HMILvl_on_PTU_affected_in_FULL_or_LIMITED.lua
user_modules/shared_testcases/testCasesForPolicyTable.lua

Should be merged only after [#227](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/227)
@istoimenova Please review commit 6fa6de4c7ce0d706256d2a6ce9b166480f5d3b15

Cover HMI levels FULL and LIMITED remain after PTU

---

user_modules/shared_testcases/commonFunctions.lua

Create function for update json file

Create function for update json file

---

test_scripts/Polices/build_options/019_ATF_P_TC_PTU_Validation_Rules_HTTP.lua
test_scripts/Polices/build_options/023_ATF_P_TC_PTU_Validation_Rules_HTTP.lua

Added script for requirement [PolicyTableUpdate] PTU validation rules

---

test_scripts/Polices/Validation_of_PolicyTables/235_ATF_merge_preloaded_pt_into_local_pt_consumer_frendly_messages_exists.lua

Updated test script with correct test data and additional logging

Updated test script with correct test data and additional logging

---

files/PTU_NewPermissionsForUserConsent.json
test_scripts/Polices/user_consent_of_Policies/100_ATF_TC_P_isAppPermissionsRevoked_true.lua

Removed check of not existing parameter.
Updated json file.
Please review @istoimenova, @tkireva

Fix ATF_TC_P_isAppPermissionsRevoked_true

---

test_scripts/Polices/build_options/002_ATF_P_Policies_Performance_Requirement.lua

Fix issues

---

test_scripts/Polices/build_options/ATF_P_Check_STATUS_vai_USER_Request.lua

SDL check status via user request fix

---

test_scripts/Polices/Related_HMI_API/205_ATF_OnAppPermissionConsent_without_appID.lua
test_scripts/Polices/Related_HMI_API/206_ATF_OnAppPermissionConsent_with_appID.lua

Changed non-existing messageCode "allowedFunctions" to correct "Location" and "Navigation"

Fixed scripts for OnAppPermissionConsent

---

test_scripts/Polices/build_options/017_ATF_P_TC_PoliciesManager_Sets_Status_UPDATING_HTTP.lua

Related to [APPLINK-30884](https://adc.luxoft.com/jira/browse/APPLINK-30884)

Fix wrong check in expect_notification

---

test_scripts/Polices/build_options/ATF_Check_SDL_respond_GetURLs_Request_fromHMI_PROPRIETARY.lua

Updated test script for ATF_Check_SDL_respond_GetURLs_Request_fromHMI_PROPRIETARY

---

test_scripts/RC/ATF_REVSDL-1038.lua
test_scripts/RC/ATF_REVSDL-1064.lua
test_scripts/RC/ATF_REVSDL-1066.lua
test_scripts/RC/ATF_REVSDL-1278.lua
test_scripts/RC/ATF_REVSDL-1360.lua
test_scripts/RC/ATF_REVSDL-1577.lua
test_scripts/RC/ATF_REVSDL-1587.lua
test_scripts/RC/ATF_REVSDL-1678.lua
test_scripts/RC/ATF_REVSDL-1702.lua
test_scripts/RC/ATF_REVSDL-1749.lua
test_scripts/RC/ATF_REVSDL-1766.lua
test_scripts/RC/ATF_REVSDL-1800.lua
test_scripts/RC/ATF_REVSDL-1827.lua
test_scripts/RC/ATF_REVSDL-1954.lua
test_scripts/RC/ATF_REVSDL-1983.lua
test_scripts/RC/ATF_REVSDL-2162.lua
test_scripts/RC/ATF_REVSDL-831.lua
test_scripts/RC/ATF_REVSDL-846.lua
test_scripts/RC/ATF_REVSDL-932.lua
test_scripts/RC/ATF_REVSDL-966.lua
test_scripts/RC/ATF_REVSDL-994.lua
test_scripts/RC/test.lua

Added new flag, fixed constructor forMobileSession

Fixed tests for working on current ATF

---

test_scripts/API/OnSeekMediaClockTimer/ATF_P_OnSeekMediaClockTimer_With_Fake_Parameter.lua

Add script to check OnSeekMediaClockTimer with fake parameter

---

test_scripts/RC/REVSDL-1827/02.01.01-REVSDL-1827_ButtonPress_LeftLongRadio.lua
test_scripts/RC/REVSDL-1827/02.01.03-REVSDL-1827_ButtonPress_BackRightLongRadio.lua
test_scripts/RC/REVSDL-1827/02.01.04-REVSDL-1827_ButtonPress_NotExists.lua
test_scripts/RC/REVSDL-1827/02.01.14_ButtonPress_FrontShortRadio.lua
test_scripts/RC/REVSDL-1827/02.01.15_REVSDL-1827_ButtonPress_BackRightRadio.lua
test_scripts/RC/REVSDL-1827/02.01.16_REVSDL-1827_ButtonPress_NotExistedShortRadio.lua
test_scripts/RC/REVSDL-1827/02.02.01_REVSDL-1827_GetInterior_Front.lua
test_scripts/RC/REVSDL-1827/02.02.02_REVSDL-1827_GetInterior_Left.lua
test_scripts/RC/REVSDL-1827/02.02.03_REVSDL-1827_GetInterior_BackRight.lua
test_scripts/RC/REVSDL-1827/02.02.04_REVSDL-1827_GetInterior_NotExisted.lua
test_scripts/RC/REVSDL-1827/02.03.01_REVSDL-1827_SetInterior_FrontRadio.lua
test_scripts/RC/REVSDL-1827/02.03.02_REVSDL-1827_SetInterior_LeftRadio.lua
test_scripts/RC/REVSDL-1827/02.03.03_REVSDL-1827_SetInterior_RightRadio.lua
test_scripts/RC/REVSDL-1827/02.03.04_REVSDL-1827_SetInterior_NotExistsRadio.lua
test_scripts/RC/REVSDL-1827/03.01.01_REVSDL-1827_ButtonPress_DriverRADIO.lua
test_scripts/RC/REVSDL-1827/03.03.01_REVSDL-1827_SetInterior_NotexistZone_DriverAllowFrontRadio.lua
test_scripts/RC/REVSDL-1827/08_REVSDL-1827_GetInterior_UserDisallowed.lua

Splitted failed tests for test set 2, 3 and 8

Add atomic scripts to REVSDL-1827. Part 1

---

test_scripts/API/PerformAudioPassThru/001_ATF_P_PerformAudioPassThru_SUCCESS_All_Params.lua
test_scripts/API/PerformAudioPassThru/002_ATF_P_PerformAudioPassThru_SUCCESS_All_Params_Upper.lua

Scripts updated with appropriate check

Scripts are updated with OnHashChange check

---

test_scripts/API/PerformAudioPassThru/005_ATF_P_PerformAudioPassThru_WARNINGS_Different_Speech_Capabilities_PRE_RECORDED.lua

Updated expected result code after clarification

---

test_scripts/API/PerformAudioPassThru/006_ATF_P_PerformAudioPassThru_WARNINGS_Different_Speech_Capabilities_SAPI_PHONEMES.lua

006_ATF_P_PerformAudioPassThru_WARNINGS_Different_Speech_Capabilities_SAPI_PHONEMES.lua 
Testing coverage available at #643

006 Script for requirement [PerformAudioPassThru] requested "ttsChunks" is NOT supported

---

test_scripts/API/PerformAudioPassThru/008_ATF_P_PerformAudioPassThru_WARNINGS_Different_Speech_Capabilities_SILENCE.lua

008_ATF_P_PerformAudioPassThru_WARNINGS_Different_Speech_Capabilities_SILENCE.lua 
Testing coverage available at #643

008 Script for requirement [PerformAudioPassThru] requested "ttsChunks" is NOT supported

---

test_scripts/RC/REVSDL-2162/02.01.01_REVSDL-AutoAllow_DriverRADIO.lua

Uncomment part of test

---

test_scripts/API/RAI/029_ATF_P_steeringWheelLocation_CENTER_response_transfered_fake_param_WRONG_LANGUAGE_RAI_steeringWheelLocation.lua
test_scripts/API/RAI/057_ATF_P_steeringWheelLocation_CENTER_response_transfered_fake_param_WRONG_LANGUAGE_RAI_steeringWheelLocation.lua

029_steeringWheelLocation_CENTER_response_transfered_fake_param_WRONG_LANGUAGE_RAI_steeringWheelLocation

---

test_scripts/API/RAI/028_ATF_P_steeringWheelLocation_CENTER_response_transfered_fake_param_RESUME_FAILED_RAI_steeringWheelLocation.lua
test_scripts/API/RAI/056_ATF_P_steeringWheelLocation_CENTER_response_transfered_fake_param_RESUME_FAILED_RAI_steeringWheelLocation.lua

028_steeringWheelLocation_CENTER_response_transfered_fake_param_RESUME_FAILED_RAI_steeringWheelLocation

---

test_scripts/API/RAI/027_ATF_P_steeringWheelLocation_CENTER_response_transfered_fake_param_WARNINGS_RAI_steeringWheelLocation.lua
test_scripts/API/RAI/055_ATF_P_steeringWheelLocation_CENTER_response_transfered_fake_param_WARNINGS_RAI_steeringWheelLocation.lua

027_steeringWheelLocation_CENTER_response_transfered_fake_param_WARNINGS_RAI_steeringWheelLocation

---

test_scripts/API/RAI/026_ATF_P_steeringWheelLocation_LEFT_WRONG_LANGUAGE_RAI_steeringWheelLocation.lua
test_scripts/API/RAI/054_ATF_P_steeringWheelLocation_LEFT_WRONG_LANGUAGE_RAI_steeringWheelLocation.lua

026_steeringWheelLocation_LEFT_WRONG_LANGUAGE_RAI_steeringWheelLocation

---

test_scripts/API/RAI/025_ATF_P_steeringWheelLocation_LEFT_RESUME_FAILED_RAI_steeringWheelLocation.lua
test_scripts/API/RAI/053_ATF_P_steeringWheelLocation_LEFT_RESUME_FAILED_RAI_steeringWheelLocation.lua

025_steeringWheelLocation_LEFT_RESUME_FAILED_RAI_steeringWheelLocation

---

test_scripts/API/RAI/024_ATF_P_steeringWheelLocation_LEFT_WARNINGS_RAI_steeringWheelLocation.lua
test_scripts/API/RAI/052_ATF_P_steeringWheelLocation_LEFT_WARNINGS_RAI_steeringWheelLocation.lua

024_steeringWheelLocation_LEFT_WARNINGS_RAI_steeringWheelLocation

---

test_scripts/API/RAI/023_ATF_N_steeringWheelLocation_IsWrongDataType_WRONG_LANGUAGE_RAI_steeringWheelLocation.lua
test_scripts/API/RAI/051_ATF_N_steeringWheelLocation_IsWrongDataType_WRONG_LANGUAGE_RAI_steeringWheelLocation.lua

023_steeringWheelLocation_IsWrongDataType_WRONG_LANGUAGE_RAI_steeringWheelLocation

---

test_scripts/API/RAI/022_ATF_N_steeringWheelLocation_IsWrongDataType_RESUME_FAILED_RAI_steeringWheelLocation.lua
test_scripts/API/RAI/050_ATF_N_steeringWheelLocation_IsWrongDataType_RESUME_FAILED_RAI_steeringWheelLocation.lua

022_steeringWheelLocation_IsWrongDataType_RESUME_FAILED_RAI_steeringWheelLocation

---

test_scripts/API/RAI/021_ATF_N_steeringWheelLocation_IsWrongDataType_WARNINGS_RAI_steeringWheelLocation.lua
test_scripts/API/RAI/049_ATF_N_steeringWheelLocation_IsWrongDataType_WARNINGS_RAI_steeringWheelLocation.lua

021_steeringWheelLocation_IsWrongDataType_WARNINGS_RAI_steeringWheelLocation

---

test_scripts/API/RAI/020_ATF_N_HMI_Does_Not_Respond_WRONG_LANGUAGE_RAI_steeringWheelLocation.lua
test_scripts/API/RAI/048_ATF_N_HMI_Does_Not_Respond_WRONG_LANGUAGE_RAI_steeringWheelLocation.lua

020_HMI_Does_Not_Respond_WRONG_LANGUAGE_RAI_steeringWheelLocation

---

test_scripts/API/RAI/019_ATF_N_HMI_Does_Not_Respond_RESUME_FAILED_RAI_steeringWheelLocation.lua
test_scripts/API/RAI/047_ATF_N_HMI_Does_Not_Respond_RESUME_FAILED_RAI_steeringWheelLocation.lua

019_HMI_Does_Not_Respond_RESUME_FAILED_RAI_steeringWheelLocation

---

test_scripts/API/RAI/018_ATF_N_HMI_Does_Not_Respond_WARNINGS_RAI_steeringWheelLocation.lua
test_scripts/API/RAI/046_ATF_N_HMI_Does_Not_Respond_WARNINGS_RAI_steeringWheelLocation.lua

018_HMI_Does_Not_Respond_WARNINGS_RAI_steeringWheelLocation

---

test_scripts/API/RAI/017_ATF_P_steeringWheelLocation_CENTER_response_transfered_fake_param_4_Apps_RAI_steeringWheelLocation.lua
test_scripts/API/RAI/045_ATF_P_steeringWheelLocation_CENTER_response_transfered_fake_param_4_Apps_RAI_steeringWheelLocation.lua

017_steeringWheelLocation_CENTER_response_transfered_fake_param_4_Apps_RAI_steeringWheelLocation

---

test_scripts/API/RAI/016_ATF_P_steeringWheelLocation_RIGHT_response_transfered_fake_param_3_Apps_RAI_steeringWheelLocation.lua
test_scripts/API/RAI/044_ATF_P_steeringWheelLocation_RIGHT_response_transfered_fake_param_3_Apps_RAI_steeringWheelLocation.lua

016_steeringWheelLocation_RIGHT_response_transfered_fake_param_3_Apps_RAI_steeringWheelLocation

---

test_scripts/API/RAI/015_ATF_P_steeringWheelLocation_LEFT_response_transfered_fake_param_RAI_steeringWheelLocation.lua
test_scripts/API/RAI/043_ATF_P_steeringWheelLocation_LEFT_response_transfered_fake_param_RAI_steeringWheelLocation.lua

015_steeringWheelLocation_LEFT_response_transfered_fake_param_RAI_steeringWheelLocation

---

test_scripts/API/SetAudioStreamingIndicator/001_ATF_N_TC_SetAudioStreamingIndicator_PLAY_PAUSE_IGNORED_media_app.lua

Script is part of TS: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/932

001_ATF_N_TC_SetAudioStreamingIndicator_PLAY_PAUSE_IGNORED_media_app

---

test_scripts/API/SetAudioStreamingIndicator/002_ATF_N_TC_SetAudioStreamingIndicator_PLAY_IGNORED_media_app.lua

002_ATF_N_TC_SetAudioStreamingIndicator_PLAY_IGNORED_media_app

---

test_scripts/API/SetAudioStreamingIndicator/003_ATF_N_TC_SetAudioStreamingIndicator_PAUSE_IGNORED_media_app.lua

003_ATF_N_TC_SetAudioStreamingIndicator_PAUSE_IGNORED_media_app

---

test_scripts/API/SetAudioStreamingIndicator/007_ATF_N_TC_SetAudioStreamingIndicator_non-media_app_REJECTED.lua

007_SetAudioStreamingIndicator_non-media_app_REJECTED

---

test_scripts/API/SetAudioStreamingIndicator/008_ATF_N_TC_SetAudioStreamingIndicator_navi_app_REJECTED.lua

008_SetAudioStreamingIndicator_navi_app_REJECTED

---

test_scripts/API/SetAudioStreamingIndicator/010_ATF_N_TC_SetAudioStreamingIndicator_non-media_app_REJECTED_fake_param.lua

010_SetAudioStreamingIndicator_non-media_app_REJECTED_fake_param

---

test_scripts/API/SetAudioStreamingIndicator/011_ATF_N_TC_SetAudioStreamingIndicator_navi_app_REJECTED_fake_param.lua

011_SetAudioStreamingIndicator_navi_app_REJECTED_fake_param

---

test_scripts/API/SetAudioStreamingIndicator/012_ATF_N_TC_SetAudioStreamingIndicator_voice_com_app_REJECTED_fake_param.lua

012_SetAudioStreamingIndicator_voice_com_app_REJECTED_fake_param

---

test_scripts/API/SetAudioStreamingIndicator/017_ATF_N_TC_SetAudioStreamingIndicator_param_data_nonexisting_value_non-media_app_SDL_replies_INVALID_DATA.lua

017_ATF_N_TC_SetAudioStreamingIndicator_param_data_nonexisting_value

---

test_scripts/API/SetAudioStreamingIndicator/018_ATF_N_TC_SetAudioStreamingIndicator_param_empty_value_non-media_app_SDL_replies_INVALID_DATA.lua

018_ATF_N_TC_SetAudioStreamingIndicator_param_empty_value_non-media_

---

test_scripts/API/SetAudioStreamingIndicator/020_ATF_N_TC_SetAudioStreamingIndicator_param_data_nonexisting_value_navi_app_SDL_replies_INVALID_DATA.lua

020_ATF_N_TC_SetAudioStreamingIndicator_param_data_nonexisting_value

---

test_scripts/API/SetAudioStreamingIndicator/021_ATF_N_TC_SetAudioStreamingIndicator_param_empty_value_navi_app_SDL_replies_INVALID_DATA.lua

021_ATF_N_TC_SetAudioStreamingIndicator_param_empty_value_navi_app

---

test_scripts/API/SetAudioStreamingIndicator/004_ATF_N_TC_SetAudioStreamingIndicator_PLAY_PAUSE_IGNORED_media_app_fake_param.lua

004_ATF_N_TC_SetAudioStreamingIndicator_PLAY_PAUSE_IGNORED_fake_param

---

test_scripts/API/SetAudioStreamingIndicator/009_ATF_N_TC_SetAudioStreamingIndicator_voice_com_app_REJECTED.lua

009_SetAudioStreamingIndicator_voice_com_app_REJECTED

---

test_scripts/API/SetAudioStreamingIndicator/005_ATF_N_TC_SetAudioStreamingIndicator_PLAY_IGNORED_media_app_fake_param.lua
test_scripts/API/SetAudioStreamingIndicator/005_ATF_P_TC_SetAudioStreamingIndicator_PLAY_media_app_fake_param_SUCCESS.lua

005_ATF_P_TC_SetAudioStreamingIndicator_PLAY_media_app_fake_param_SUCCESS

---

test_scripts/API/SetAudioStreamingIndicator/019_ATF_N_TC_SetAudioStreamingIndicator_param_wrongtype_navi_app_SDL_replies_INVALID_DATA.lua

019_ATF_N_TC_SetAudioStreamingIndicator_param_wrongtype_navi_app_SDL

---

test_scripts/API/PerformAudioPassThru/009_ATF_P_PerformAudioPassThru_SUCCESS_Dynamic_Image_All_Params.lua
test_scripts/API/PerformAudioPassThru/010_ATF_P_PerformAudioPassThru_SUCCESS_Dynamic_Image_MandatoryParams_and_audioPassThruIcon.lua

Scripts updated due to changes in commonPreconditions

Updated with new config.pathToSDL function

---

test_scripts/API/SetAudioStreamingIndicator/065_ATF_N_HMI_responds_Invalid_Json_SetAudioStreamingIndicator.lua

065_ATF_N_HMI_responds_Invalid_Json_SetAudioStreamingIndicator

---

test_scripts/API/SetAudioStreamingIndicator/064_ATF_N_wrong_Json_SetAudioStreamingIndicator_INVALID_DATA.lua

064_ATF_N_wrong_Json_SetAudioStreamingIndicator_INVALID_DATA

---

test_scripts/API/AutoCompleteList/001_ATF_SetGlobalProperties_P_AutoCompleteList_OmitedText_HAPPY_PATH.lua

@OVikhrov @aarotar please review.

Script for coverage when autoCompleteList and autoCompleteText present in RPC

---

test_scripts/API/AutoCompleteList/002_ATF_SetGlobalProperties_P_AutoCompleteList_WithOutParam.lua

Script for coverage when autoCompleteList param not present in PRC

---

test_scripts/API/AutoCompleteList/003_ATF_SetGlobalProperties_N_transfer_NotAllowed_request.lua

Script for coverage when RPC with autoCompleteList not allow

---

test_scripts/API/AutoCompleteList/004_ATF_SetGlobalProperties_P_AutoCompleteList_ValueUpperBound.lua

Script for coverage when AutoCompleteList have values in upper bound

---

test_scripts/API/AutoCompleteList/005_ATF_SetGlobalProperties_P_AutoCompleteList_ValueSpaceBefore.lua

@OVikhrov @aarotar please review.

Script for coverage when AutoCompleteList have spaces before values

---

test_scripts/API/AutoCompleteList/006_ATF_SetGlobalProperties_P_AutoCompleteList_ValueSpaceAfter.lua

Script for coverage when AutoCompleteList have spaces after values

---

test_scripts/API/AutoCompleteList/007_ATF_SetGlobalProperties_P_AutoCompleteList_ValueLowerBound.lua

Script for coverage when AutoCompleteList have values in lower bound

---

test_scripts/API/AutoCompleteList/008_ATF_SetGlobalProperties_P_AutoCompleteList_ArrayOfUpperBound.lua

Script for coverage when AutoCompleteList have array values in upper bounds

---

test_scripts/API/AutoCompleteList/009_ATF_SetGlobalProperties_P_AutoCompleteList_ArrayOfLowerBound.lua

@aarotar @OVikhrov please review

Script for coverage when AutoCompleteList have array values in lower bounds

---

test_scripts/API/AutoCompleteList/010_ATF_SetGlobalProperties_N_AutoCompleteList_ValueNewLine.lua

Script for coverage when AutoCompleteList have new line symbol in value

---

test_scripts/API/AutoCompleteList/011_ATF_SetGlobalProperties_N_AutoCompleteList_TabInValue.lua

Script for coverage when AutoCompleteList have tabulation symbol in value

---

test_scripts/API/AutoCompleteList/013_ATF_SetGlobalProperties_N_AutoCompleteList_SpacesInValue.lua

Script for coverage when AutoCompleteList have spaces values

---

test_scripts/API/AutoCompleteList/014_ATF_SetGlobalProperties_N_AutoCompleteList_InvalidParam_GENERIC_ERROR.lua

Script for coverage when AutoCompleteList have on of invalid param

---

test_scripts/API/AutoCompleteList/015_ATF_SetGlobalProperties_N_AutoCompleteList_IncorrectJSON.lua

Script for coverage when SDL receive invalid json with autoCompleteList

---

test_scripts/API/AutoCompleteList/017_ATF_SetGlobalProperties_N_AutoCompleteList_HMI_Invalid_response_on_Mobile.lua

@OVikhrov @aarotar please review.

Script for coverage when SDL received invalid HMI respond

---

test_scripts/AppIconsFolder/ATF_P_AppIconsAmountToRemove_zero_value.lua

Script covering case when AppIconsAmountToRemove has zero value

---

test_scripts/AppIconsFolder/ATF_N_Icon_greater_than_AppIconsFolderMaxSize.lua

Script covering case when icon greater than appIconsFolderMaxSize

---

test_scripts/AppIconsFolder/ATF_P_AppIconsFolderMaxSize_less_than_default.lua

Script covering case when AppIconsFolder maxSize less than default value

---

test_scripts/AppIconsFolder/ATF_P_Cyclically_Remove_AppIconsAmountToRemove.lua

Script covering cyclic removing due to appIconsAmountToRemove

---

test_scripts/AppIconsFolder/ATF_P_Remove_Old_AppIconsAmountToRemove_noSpace.lua

Script covering case when icons removed due appIconsAmountToRemove

---

test_scripts/API/IsReady/UI_IsReady/SetAudioStreamingIndicator/003_ATF_N_TC_SetAudioStreamingIndicator_IsReady_available_false.lua

Test is part of https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1071

003_ATF_N_TC_SetAudioStreamingIndicator_IsReady_available_false

---

test_scripts/API/PerformAudioPassThru/023_ATF_P_PerformAudioPassThru_TTS_SUCCESS_UI_success_false.lua

@istoimenova Please check update in script 023_ATF_P_PerformAudioPassThru_TTS_SUCCESS_UI_success_false.lua

Info parameter expectation updated

---

test_scripts/API/PerformAudioPassThru/023_ATF_P_PerformAudioPassThru_TTS_SUCCESS_UI_success_false.lua
test_scripts/API/PerformAudioPassThru/025_ATF_P_PerformAudioPassThru_UI_SUCCESS_TTS_success_false_true.lua
test_scripts/API/PerformAudioPassThru/026_ATF_P_PerformAudioPassThru_UI_success_false_TTS_success_false.lua

@istoimenova 
Please review:
023_ATF_P_PerformAudioPassThru_TTS_SUCCESS_UI_success_false.lua 
025_ATF_P_PerformAudioPassThru_UI_SUCCESS_TTS_success_false_true.lua 
026_ATF_P_PerformAudioPassThru_UI_success_false_TTS_success_false.lua 
Added TODO and additional check, also scripts were beautified.

Script updated with temporary fix to avoid issue with ATF HMI_API.xml

---

test_sets/rc_smoke.txt

Test cases for multidevice functionality removed from rc_smoke

Test cases for multidevice functionality removed from rc_smoke

---

test_scripts/API/PerformAudioPassThru/009_ATF_P_PerformAudioPassThru_SUCCESS_Dynamic_Image_All_Params.lua

Need to check correct storage path for image with type DYNAMIC

Debug of Dynamic image storage path

---

test_scripts/API/PerformAudioPassThru/009_ATF_P_PerformAudioPassThru_SUCCESS_Dynamic_Image_All_Params.lua
test_scripts/API/PerformAudioPassThru/010_ATF_P_PerformAudioPassThru_SUCCESS_Dynamic_Image_MandatoryParams_and_audioPassThruIcon.lua
test_scripts/API/PerformAudioPassThru/021_ATF_P_PerformAudioPassThru_WARNING_Missing_audioPassThruIcon_AllParams_DYNAMIC.lua
test_scripts/API/PerformAudioPassThru/022_ATF_P_PerformAudioPassThru_WARNING_Missing_audioPassThruIcon_MandatoryParams_DYNAMIC.lua

@istoimenova Please review, the storage path has been updated to avoid fails of scripts on CI server.

Scripts updated to run on CI

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/001_ATF_P_TC_new_navi_app_no_certificate.lua

Script is part of TS: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1163
common functions for CRQ: #1175

001_ATF_P_TC_new_navi_app_no_certificate

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/002_ATF_P_TC_existing_navi_app_no_certificate.lua

Script is part of TS: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1163
common functions for CRQ: #1175

002_ATF_P_TC_existing_navi_app_no_certificate

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/003_ATF_N_TC_new_navi_app_certificate_exist.lua

Script is part of TS: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1163
common functions for CRQ: #1175

003_ATF_N_TC_new_navi_app_certificate_exist

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/006_ATF_P_TC_comm_app_first_StartService_RPC_encrypt_true.lua

Script is part of TS: #1163 
PRs: #1195; #1197 have common scenario for different type of applications.

006_ATF_P_TC_comm_app_first_StartService_RPC_encrypt_true

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/007_ATF_P_TC_media_app_first_StartService_RPC_encrypt_true.lua

PRs: #1195; #1196 have common scenario for different type of applications.

007_ATF_P_TC_media_app_first_StartService_RPC_encrypt_true

---

files/jsons/Policies/Related_HMI_API/OnAppPermissionConsent_ptu.json
test_scripts/Polices/External_UCS_Informing_HMI/001_ATF_P_GetListofPermissions_with_appID_all_ecs_in_bound_EntitySatus_ON.lua

@istoimenova Please review 
001_ATF_P_GetListofPermissions_with_appID_all_ecs_in_bound_EntitySatus_ON.lua 
Testing coverage is under review in #1165 

[WIP] 001 Script for requirement [GENIVI] [Policies] External UCS: informing HMI

---

user_modules/shared_testcases/testCasesForExternalUCS.lua

Common functions used in scripts for https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1169

External UCS parameters: Common functions

---

user_modules/shared_testcases/testCasesForPolicyCeritificates.lua

Add new common function for StartService NACK

testCasesForPolicyCeritificates - common function start_service_NACK

---

test_scripts/Polices/External_UCS/001_ATF_P_TC_LPT_Creation_PreloadedPT_without_external_consent_status_groups_struct.lua

External UCS parameters: Script 001

---

user_modules/shared_testcases/commonFunctions.lua

Create simple common function in user_modules for join paths in scripts
Function sequentially concatenates parameters with "/" to one string without "/" at the end.
Function does not perform any check for parameters.

Simple function for join paths created

---

test_scripts/Polices/External_UCS/006_ATF_P_TC_LPT_Creation_PreloadedPT_with_disallowed_by_external_consent_entities_on_struct.lua

[WIP] External UCS parameters: Script 006

---

test_scripts/Polices/External_UCS/003_ATF_P_TC_LPT_Creation_PreloadedPT_without_disallowed_by_external_consent_entities_off_struct.lua

External UCS parameters: Script 003

---

test_scripts/Polices/External_UCS/004_ATF_P_TC_LPT_Creation_PreloadedPT_with_disallowed_by_external_consent_entities_off_struct.lua

External UCS parameters: Script 004

---

test_scripts/Polices/External_UCS/005_ATF_P_TC_LPT_Creation_PreloadedPT_without_disallowed_by_external_consent_entities_on_struct.lua

External UCS parameters: Script 005

---

test_scripts/Polices/External_UCS_Informing_HMI/018_ATF_N_GetListofPermissions_empty_due_to_missing_status_OnAppPermissionChange.lua

Update script 018

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/010_ATF_P_TC_media_app_PTU_fail_ForceProtectedService_ON_RPC_encrypted_true.lua

PRs: #1226, #1227 have common scenario for different type of applications.

010_ATF_P_TC_media_app_PTU_fail_ForceProtectedService_ON_RPC_encrypte

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/011_ATF_P_TC_comm_app_PTU_fail_ForceProtectedService_ON_RPC_encrypted_true.lua

PRs: #1225, #1227 have common scenario for different type of applications.

011_ATF_P_TC_comm_app_PTU_fail_ForceProtectedService_ON_RPC_encrypted

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/012_ATF_P_TC_default_app_PTU_fail_ForceProtectedService_ON_RPC_encrypted_true.lua

PRs: #1225, #1226 have common scenario for different type of applications.

012_ATF_P_TC_default_app_PTU_fail_ForceProtectedService_ON_RPC_encryp

---

test_scripts/Polices/External_UCS/002_ATF_N_TC_LPT_Creation_PreloadedPT_with_external_consent_status_groups_struct.lua

External UCS parameters: Script 002

---

test_scripts/Polices/External_UCS/007_ATF_N_TC_LPT_Creation_PreloadedPT_with_disallowed_by_external_consent_entities_off_struct_with_invalid_type_of_params.lua

External UCS parameters: Script 007

---

test_scripts/Polices/External_UCS/008_ATF_N_TC_LPT_Creation_PreloadedPT_with_disallowed_by_external_consent_entities_on_struct_with_invalid_type_of_params.lua

External UCS parameters: Script 008

---

test_scripts/Polices/External_UCS/009_ATF_P_TC_SnapshotPT_without_external_consent_status_groups_struct.lua

External UCS parameters: Script 009

---

test_scripts/Polices/External_UCS/012_ATF_P_TC_SnapshotPT_with_disallowed_by_external_consent_entities_off_struct.lua

 External UCS parameters: Script 012

---

test_scripts/Polices/External_UCS/014_ATF_P_TC_SnapshotPT_with_disallowed_by_external_consent_entities_on_struct.lua

 External UCS parameters: Script 014

---

test_scripts/Polices/External_UCS/010_ATF_P_TC_SnapshotPT_with_external_consent_status_groups_struct.lua

External UCS parameters: Script 010

---

test_scripts/Polices/External_UCS/011_ATF_P_TC_SnapshotPT_without_disallowed_by_external_consent_entities_off_struct.lua

 External UCS parameters: Script 011

---

test_scripts/Polices/External_UCS/015_ATF_P_TC_PTU_without_external_consent_status_groups_struct.lua

External UCS parameters: Script 015

---

test_scripts/Polices/External_UCS/020_ATF_P_TC_PTU_with_disallowed_by_external_consent_entities_on_struct.lua

External UCS parameters: Script 020

---

test_scripts/Polices/External_UCS/023_ATF_P_TC_LPT_Update_PreloadedPT_without_external_consent_status_groups_struct.lua

External UCS parameters: Script 023

---

test_scripts/Polices/External_UCS/External_Consent_OFF/021_ATF_Policies_External_Consent_OFF_allowed_change_to_ON_disallowed.lua

021_ATF_Policies_External_Consent_OFF_allowed_change_to_ON_disallowed.lua 
Test set is available in #1219
User modules should be taken from #1211
@dboltovskyi @vvvakulenko @ttdong

[WIP] 021 Script for requirement [Policies] External UCS: OFF OnPermissionsChange for allowed groupings after externalConsentStatus changes to ON

---

test_scripts/Polices/External_UCS/013_ATF_P_TC_SnapshotPT_without_disallowed_by_external_consent_entities_on_struct.lua

 External UCS parameters: Script 013

---

test_scripts/Polices/External_UCS/016_ATF_N_TC_PTU_with_external_consent_status_groups_struct.lua

External UCS parameters: Script 016

---

test_scripts/Polices/External_UCS/027_ATF_P_TC_LPT_Update_PreloadedPT_without_disallowed_by_external_consent_entities_on_struct.lua

External UCS parameters: Script 027

---

test_scripts/Polices/External_UCS/026_ATF_P_TC_LPT_Update_PreloadedPT_with_disallowed_by_external_consent_entities_off_struct.lua

External UCS parameters: Script 026

---

test_scripts/Polices/External_UCS/025_ATF_P_TC_LPT_Update_PreloadedPT_without_disallowed_by_external_consent_entities_off_struct.lua

External UCS parameters: Script 025

---

test_scripts/Polices/External_UCS/024_ATF_N_TC_LPT_Update_PreloadedPT_with_external_consent_status_groups_struct.lua

External UCS parameters: Script 024

---

test_scripts/Polices/External_UCS/018_ATF_P_TC_PTU_with_disallowed_by_external_consent_entities_off_struct.lua

External UCS parameters: Script 018

---

test_scripts/Polices/External_UCS/028_ATF_P_TC_LPT_Update_PreloadedPT_with_disallowed_by_external_consent_entities_on_struct.lua

External UCS parameters: Script 028

---

test_scripts/Polices/External_UCS/017_ATF_P_TC_PTU_without_disallowed_by_external_consent_entities_off_struct.lua

External UCS parameters: Script 017

---

test_scripts/Polices/External_UCS/019_ATF_P_TC_PTU_without_disallowed_by_external_consent_entities_on_struct.lua

External UCS parameters: Script 019

---

test_scripts/Polices/External_UCS/021_ATF_N_TC_PTU_with_disallowed_by_external_consent_entities_off_struct_with_invalid_type_of_params.lua

External UCS parameters: Script 021

---

test_scripts/Polices/External_UCS/022_ATF_N_TC_PTU_with_disallowed_by_external_consent_entities_on_struct_with_invalid_type_of_params.lua

External UCS parameters: Script 022

---

test_scripts/Polices/External_UCS/029_ATF_N_TC_LPT_Update_PreloadedPT_with_disallowed_by_external_consent_entities_off_struct_with_invalid_type_of_params.lua

External UCS parameters: Script 029

---

test_scripts/Polices/External_UCS/030_ATF_N_TC_LPT_Update_PreloadedPT_with_disallowed_by_external_consent_entities_on_struct_with_invalid_type_of_params.lua

External UCS parameters: Script 030

---

test_scripts/AppIconsFolder/ATF_N_AppIconsAmountToRemove_larger_than_icons_amount.lua
test_scripts/AppIconsFolder/ATF_P_AppIconsAmountToRemove_zero_value.lua
test_scripts/AppIconsFolder/ATF_P_AppIconsFolderMaxSize_greater_than_default.lua
test_scripts/AppIconsFolder/ATF_P_AppIconsFolderMaxSize_less_than_default.lua
test_scripts/AppIconsFolder/ATF_P_Cyclically_Remove_AppIconsAmountToRemove.lua
test_scripts/AppIconsFolder/ATF_P_Remove_Old_AppIconsAmountToRemove_noSpace.lua

Time between Putfile requests was increased

Time between Putfile requests increased

---

user_modules/IsReady_Template/ATF_Interface_IsReady_missing_SingleRPC_Template.lua

Fix waiting GENERIC_ERROR for Slider.
Increase timeout according slider's timeout
Fix expecting UnsubscribeVehicleData on HMI side in error case

Fix IsReady missing single rpc template

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/040_ATF_P_TC_default_app_PTU_retry_sequence_finish_ForceProtectedService_OFF_RPC_encrypted_true.lua

Script is common as PRs: #1312, #1313

040_ATF_P_TC_default_app_PTU_retry_sequence_finish_ForceProtectedService_OFF_RPC_encrypted_true

---

user_modules/common_functions.lua

Existing approach does not remove .log files in SDL/bin folder
Current PR fixes this problem

Fix removing of .log files

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/041_ATF_P_TC_navi_PTU_brings_certificate_Audio_ForceProtectedService_OFF.lua

Script is common as PRs: #1321, #1322, #1324

041_ATF_P_TC_navi_PTU_brings_certificate_Audio_ForceProtectedService_OFF

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/042_ATF_P_TC_navi_PTU_brings_certificate_Video_ForceProtectedService_OFF.lua

Script is common as PRs: #1320, #1322, #1324

042_ATF_P_TC_navi_PTU_brings_certificate_Video_ForceProtectedService_OFF

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/043_ATF_P_TC_navi_PTU_brings_certificate_RPC_ForceProtectedService_OFF.lua

Script is common as PRs: #1320, #1321, #1324

043_ATF_P_TC_navi_PTU_brings_certificate_RPC_ForceProtectedService_OFF

---

test_scripts/Polices/External_UCS/External_Consent_ON/011_ATF_Policies_External_Consent_ON_through_ignition_cycles_allowed_RPCs.lua

Script is part of test set: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1301
Similar scripts:
https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1331
https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1332

External UCS: ON by the User: Script 011

---

user_modules/shared_testcases/commonPreconditions.lua

Implemented approach mentioned in https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1240

Added function getAbsolutePath()

---

test_scripts/Polices/External_UCS/External_Consent_OFF/001_ATF_Policies_External_Consent_OFF_disallowed_by_external_consent_entities_on_data_consent_disallowed.lua
test_scripts/Polices/External_UCS/External_Consent_OFF/002_ATF_Policies_External_Consent_OFF_disallowed_by_external_consent_entities_on_user_consent_disallowed.lua
test_scripts/Polices/External_UCS/External_Consent_OFF/003_ATF_Policies_External_Consent_OFF_disallowed_by_external_consent_entities_on_user_consent_allowed.lua
test_scripts/Polices/External_UCS/External_Consent_OFF/004_ATF_Policies_External_Consent_OFF_disallowed_by_external_consent_entities_off_data_consent_disallowed.lua
test_scripts/Polices/External_UCS/External_Consent_OFF/005_ATF_Policies_External_Consent_OFF_disallowed_by_external_consent_entities_off_user_consent_allowed.lua
test_scripts/Polices/External_UCS/External_Consent_OFF/006_ATF_Policies_External_Consent_OFF_disallowed_by_external_consent_entities_off_user_consent_disallowed.lua
test_scripts/Polices/External_UCS/External_Consent_OFF/007_ATF_Policies_External_Consent_OFF_disallowed_by_external_consent_entities_omitted_data_consent_disallowed.lua
test_scripts/Polices/External_UCS/External_Consent_OFF/008_ATF_Policies_External_Consent_OFF_disallowed_by_external_consent_entities_omitted_user_consent_allowed.lua
test_scripts/Polices/External_UCS/External_Consent_OFF/009_ATF_Policies_External_Consent_OFF_disallowed_by_external_consent_entities_omitted_user_consent_disallowed.lua
test_scripts/Polices/External_UCS/External_Consent_OFF/010_ATF_Policies_External_Consent_OFF_disallowed_by_external_consent_entities_omitted_user_consent_omitted.lua
test_scripts/Polices/External_UCS/External_Consent_OFF/011_ATF_Policies_External_Consent_OFF_through_ignition_cycles.lua
test_scripts/Polices/External_UCS/External_Consent_OFF/014_ATF_Policies_External_Consent_OFF_disallowed_change_to_ON_allowed.lua
test_scripts/Polices/External_UCS/External_Consent_OFF/015_ATF_Policies_External_Consent_OFF_external_consent_disallowed_user_consent_allowed.lua
test_scripts/Polices/External_UCS/External_Consent_OFF/016_ATF_Policies_External_Consent_OFF_external_consent_disallowed_user_consent_disallowed.lua
test_scripts/Polices/External_UCS/External_Consent_OFF/017_ATF_Policies_External_Consent_OFF_external_consent_disallowed_user_consent_omitted.lua
test_scripts/Polices/External_UCS/External_Consent_OFF/018_ATF_Policies_External_Consent_OFF_external_consent_allowed_user_consent_allowed.lua
test_scripts/Polices/External_UCS/External_Consent_OFF/019_ATF_Policies_External_Consent_OFF_external_consent_allowed_user_consent_disallowed.lua
test_scripts/Polices/External_UCS/External_Consent_OFF/020_ATF_Policies_External_Consent_OFF_external_consent_allowed_user_consent_omitted.lua

Scripts are transferred from FS to OpenSDL. Lua check and runtime errors are checked.

Script are passed lua check and runtime errors.

---

test_scripts/Polices/External_UCS/External_Consent_ON/012_ATF_Policies_External_Consent_ON_through_ignition_cycles_user_disallowed_RPCs.lua

Script is part of test set: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1301
Similar scripts:
https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1330
https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1332

External UCS: ON by the User: Script 012

---

test_scripts/Polices/External_UCS/External_Consent_ON/013_ATF_Policies_External_Consent_ON_through_ignition_cycles_disallowed_by_external_consent_entities_omitted.lua

Script is part of test set: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1301
Similar scripts:
https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1330
https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1331

External UCS: ON by the User: Script 013

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/045_ATF_P_TC_navi_PTU_brings_certificate_Audio_ForceProtectedService_ON.lua

Script is common as PRs: #1338, #1339, #1340

045_ATF_P_TC_navi_PTU_brings_certificate_Audio_ForceProtectedService_ON

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/046_ATF_P_TC_navi_PTU_brings_certificate_Video_ForceProtectedService_ON.lua

Script is common as PRs: #1337, #1339, #1340

046_ATF_P_TC_navi_PTU_brings_certificate_Video_ForceProtectedService_ON

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/047_ATF_P_TC_navi_PTU_brings_certificate_RPC_ForceProtectedService_ON.lua

Script is common as PRs: #1337, #1338, #1340

047_ATF_P_TC_navi_PTU_brings_certificate_RPC_ForceProtectedService_ON

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/048_ATF_P_TC_navi_PTU_brings_certificate_Hybrid_ForceProtectedService_ON.lua

Script is common as PRs: #1337, #1338, #1339

048_ATF_P_TC_navi_PTU_brings_certificate_Hybrid_ForceProtectedService_ON

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/050_ATF_P_TC_comm_PTU_brings_certificate_RPC_ForceProtectedService_OFF.lua

Script is common as PRs: #1325, #1327

050_ATF_P_TC_comm_PTU_brings_certificate_RPC_ForceProtectedService_OFF

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/051_ATF_P_TC_media_PTU_brings_certificate_RPC_ForceProtectedService_OFF.lua

Script is common as PRs: #1325, #1326

051_ATF_P_TC_media_PTU_brings_certificate_RPC_ForceProtectedService_OFF

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/052_ATF_P_TC_default_PTU_brings_certificate_RPC_ForceProtectedService_ON.lua

Script is common as PRs: #1347, #1348

052_ATF_P_TC_default_PTU_brings_certificate_RPC_ForceProtectedService_ON

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/053_ATF_P_TC_comm_PTU_brings_certificate_RPC_ForceProtectedService_ON.lua

Script is common as PRs: #1346, #1348

053_ATF_P_TC_comm_PTU_brings_certificate_RPC_ForceProtectedService_ON

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/054_ATF_P_TC_media_PTU_brings_certificate_RPC_ForceProtectedService_ON.lua

Script is common as PRs:#1346, #1347

054_ATF_P_TC_media_PTU_brings_certificate_RPC_ForceProtectedService_ON

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/055_ATF_N_TC_media_app_not_first_RPC_encrypt_true.lua

Script is common as PRs: #1350, #1351

055_ATF_N_TC_media_app_not_first_RPC_encrypt_true

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/056_ATF_N_TC_comm_app_not_first_RPC_encrypt_true.lua

Script is common as PRs: #1349, #1351

056_ATF_N_TC_comm_app_not_first_RPC_encrypt_true

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/057_ATF_N_TC_default_app_not_first_RPC_encrypt_true.lua

Script is common as PRs: #1349, #1350

057_ATF_N_TC_default_app_not_first_RPC_encrypt_true

---

test_scripts/Polices/External_UCS/External_Consent_OFF/031_ATF_Policies_External_Consent_missing.lua

Script is part of TestSet: #1219

031_ATF_Policies_External_Consent_missing

---

user_modules/shared_testcases/testCasesForPolicyTable.lua

Additional check is implemented regarding issue https://github.com/smartdevicelink/sdl_core/issues/1376
SDL fix is in https://github.com/smartdevicelink/sdl_core/pull/1417

Additional check on PTS in payload for OnSystemRequest

---

test_scripts/Smoke/Resumption/ATF_Resumption_3rd_ignition_cycle.lua
test_scripts/Smoke/Resumption/ATF_Resumption_App_Unregister_itself.lua
test_scripts/Smoke/Resumption/ATF_Resumption_BACKGROUND_level.lua
test_scripts/Smoke/Resumption/ATF_Resumption_FULL_IGNITION_OFF.lua
test_scripts/Smoke/Resumption/ATF_Resumption_LIMITED_IGNITION_OFF.lua
test_scripts/Smoke/Resumption/ATF_Resumption_LIMITED_level.lua
test_scripts/Smoke/Resumption/ATF_Resumption_app_registered_in_more_than_30sec_after_BC.OnReady.lua
test_scripts/Smoke/Resumption/ATF_Resumption_big_amount_of_data.lua
test_scripts/Smoke/Resumption/ATF_Resumption_disconnect_more_than_30s_before_SUSPEND.lua
test_scripts/Smoke/Resumption/ATF_Resumption_heartbeat_disconnect.lua
test_scripts/Smoke/Resumption/ATF_Resumption_unexpected_disconnect.lua
user_modules/shared_testcases/commonStepsResumption.lua

Automate Resumption Smoke according to template
https://adc.luxoft.com/jira/browse/SDLOPEN-916 (see attached files)

Resumption Smoke

---

test_scripts/Polices/External_UCS_Informing_HMI/019_ATF_N_GetListofPermissions_empty_due_to_invalid_param_entityType_OnAppPermissionChange.lua

resolving conflicts from PR #1218

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/023_ATF_P_TC_navi_app_PTU_no_certificate_ForceProtectedService_OFF_Hybrid_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/029_ATF_P_TC_navi_app_PTU_fail_ForceProtectedService_OFF_Hybrid_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/034_ATF_P_TC_navi_app_PTU_retry_sequence_finish_ForceProtectedService_OFF_Hybrid_encrypted_true.lua

Clarification: "Contradictory requirements for StartService with Bulk and RPC data"

Update according to clarification

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/020_ATF_P_TC_navi_app_PTU_no_certificate_ForceProtectedService_OFF_RPC_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/023_ATF_P_TC_navi_app_PTU_no_certificate_ForceProtectedService_OFF_Hybrid_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/024_ATF_P_TC_media_app_PTU_no_certificate_ForceProtectedService_OFF_RPC_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/025_ATF_P_TC_comm_app_PTU_no_certificate_ForceProtectedService_OFF_RPC_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/026_ATF_P_TC_default_app_PTU_no_certificate_ForceProtectedService_OFF_RPC_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/029_ATF_P_TC_navi_app_PTU_fail_ForceProtectedService_OFF_Hybrid_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/030_ATF_P_TC_navi_app_PTU_fail_ForceProtectedService_OFF_RPC_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/033_ATF_P_TC_navi_app_PTU_retry_sequence_finish_ForceProtectedService_OFF_RPC_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/034_ATF_P_TC_navi_app_PTU_retry_sequence_finish_ForceProtectedService_OFF_Hybrid_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/035_ATF_P_TC_media_app_PTU_fail_ForceProtectedService_OFF_RPC_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/036_ATF_P_TC_comm_app_PTU_fail_ForceProtectedService_OFF_RPC_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/037_ATF_P_TC_default_app_PTU_fail_ForceProtectedService_OFF_RPC_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/038_ATF_P_TC_media_app_PTU_retry_sequence_finish_ForceProtectedService_OFF_RPC_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/039_ATF_P_TC_comm_app_PTU_retry_sequence_finish_ForceProtectedService_OFF_RPC_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/040_ATF_P_TC_default_app_PTU_retry_sequence_finish_ForceProtectedService_OFF_RPC_encrypted_true.lua

"Contradictory requirements for StartService with Bulk and RPC data"

Update based on clarification

---

user_modules/common_steps.lua

Fix regarding defect "[GENIVI] SDL crushes at IGN_OFF -> IGN_ON cycle during check of UCS parameter."

Change logic for IgnitionOff

---

test_scripts/Smoke/Registration/ATF_Register_5_connection.lua
test_scripts/Smoke/Registration/ATF_Register_5_session.lua
test_scripts/Smoke/Registration/ATF_Register_App.lua
test_scripts/Smoke/Registration/ATF_Reregister_App.lua
test_scripts/Smoke/Registration/ATF_Reregister_App_after_disconnect.lua
test_scripts/Smoke/Registration/ATF_Reregister_App_if_two_apps_are_registered.lua
test_sets/smoke_tests.txt

Smoke tests for registration (transport)

---

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/010_ATF_P_TC_media_app_PTU_fail_ForceProtectedService_ON_RPC_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/011_ATF_P_TC_comm_app_PTU_fail_ForceProtectedService_ON_RPC_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/012_ATF_P_TC_default_app_PTU_fail_ForceProtectedService_ON_RPC_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/027_ATF_P_TC_navi_app_PTU_fail_ForceProtectedService_OFF_Audio_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/028_ATF_P_TC_navi_app_PTU_fail_ForceProtectedService_OFF_Video_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/029_ATF_P_TC_navi_app_PTU_fail_ForceProtectedService_OFF_Hybrid_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/030_ATF_P_TC_navi_app_PTU_fail_ForceProtectedService_OFF_RPC_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/035_ATF_P_TC_media_app_PTU_fail_ForceProtectedService_OFF_RPC_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/036_ATF_P_TC_comm_app_PTU_fail_ForceProtectedService_OFF_RPC_encrypted_true.lua
test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/037_ATF_P_TC_default_app_PTU_fail_ForceProtectedService_OFF_RPC_encrypted_true.lua

- Added expectation for "SDL.OnStatusUpdate" notification with status = "UPDATING"

Fix scripts with not finished PTU

---

test_scripts/Polices/build_options/032_ATF_P_TC_PTU_Retry_Sequence_Retry_Timeout_Expiration_HTTP.lua

LOCK_SCREEN_ICON_URL can come when app registered
Fix calculation of time according requirements

Fix check retry timeout

---

test_scripts/Polices/appID_Management/162_ATF_P_TC_HMI_Status_Appid_Gets_Null_In_Case_Of_PTU.lua
test_scripts/Polices/appID_Management/163_ATF_P_TC_HMI_Status_Value_Of_AppId_In_PT_Is_Null.lua

Fix for PR https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1399

Add additional OnHMIStatus notification (develop)

---

test_scripts/Polices/appID_Management/162_ATF_P_TC_HMI_Status_Appid_Gets_Null_In_Case_Of_PTU.lua
test_scripts/Polices/appID_Management/163_ATF_P_TC_HMI_Status_Value_Of_AppId_In_PT_Is_Null.lua

Fix for PR https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1394

Add additional OnHMIStatus notification (extended)

---

test_scripts/Polices/user_consent_of_Policies/112_ATF_User_consents_permissions.lua

Remove condition for ptu trigger of navi application.

update regarding ptu trigger for navi app

---

test_scripts/Smoke/HeartBeat/ATF_HeartBeat_App_does_not_send_HB_and_does_not_respond.lua
test_scripts/Smoke/HeartBeat/ATF_HeartBeat_App_does_not_send_HB_but_respond.lua
test_scripts/Smoke/HeartBeat/ATF_HeartBeat_App_send_HB.lua
test_scripts/Smoke/HeartBeat/ATF_HeartBeat_no_heartbeat_v2_protocol.lua
test_sets/smoke_tests.txt

Automate HeartBeat Smoke according to template
https://adc.luxoft.com/jira/browse/SDLOPEN-916 (see attached files)

[WIP]Smoke tests for HeartBeat

---

test_scripts/Smoke/HeartBeat/ATF_HeartBeat_App_does_not_send_HB_and_does_not_respond.lua
test_scripts/Smoke/HeartBeat/ATF_HeartBeat_App_does_not_send_HB_but_respond.lua
test_scripts/Smoke/HeartBeat/ATF_HeartBeat_App_send_HB.lua
test_scripts/Smoke/HeartBeat/ATF_HeartBeat_no_heartbeat_v2_protocol.lua
test_sets/smoke_tests.txt

Apply changes #1376 on feature/extended_policy_functionality branch

Smoke tests for HeartBeat

---

test_scripts/Polices/Related_HMI_API/ATF_OnPolicyUpdate_initiation_of_PTU.lua

Issue: "[GENIVI]SDL doens't send BC.PolicyUpdate at new ignition cycle"

Remove restarting SDL because of sdl issue 

---

test_scripts/Polices/build_options/ATF_P_Register_NewApp_not_exist_inLocalPT_FinishPTU_PROPRIETARY.lua

Update to have PTU through application in FULL

---

test_scripts/Polices/Validation_of_PolicyTables/235_ATF_merge_preloaded_pt_into_local_pt_consumer_frendly_messages_exists.lua

Clarification: "Clarification of requirements "Merging rules for "consumer_friendly_messages" section""

Update of script 235

---

test_scripts/Polices/Validation_of_PolicyTables/292_ATF_P_Memory_Kb_Constraints_Ignoring.lua

Script is corrected in scope of fixing of "Application is unregistered due to TOO_MANY_REQUESTS"

Correct script

---

test_scripts/Polices/Policy_Table_Update/027_ATF_P_TC_HMILvl_on_PTU_affected_in_FULL_or_LIMITED.lua

Added check notifications for the 2 registered applications.

Script is updated

---

files/jsons/Policies/Policy_Table_Update/few_endpoints_appId_default.json
files/jsons/Policies/Policy_Table_Update/few_endpoints_appId_not_registered.json
files/jsons/Policies/Policy_Table_Update/few_endpoints_appId_registered.json
test_scripts/Polices/Policy_Table_Update/055_ATF_P_TC_HMI_sends_GetURLs_one_app_registered_urls_3default.lua
test_scripts/Polices/Policy_Table_Update/056_ATF_P_TC_HMI_sends_GetURLs_one_app_registered_urls_3default_not_registered.lua
test_scripts/Polices/Policy_Table_Update/057_ATF_P_TC_HMI_sends_GetURLs_one_app_registered_urls_3default_registered.lua

The scripts are based on different urls in sdl_preloaded_pt.json regarding registered / non-registered applications / defaults.

Added new scripts for verification of GetURLS.

---

user_modules/shared_testcases/commonSteps.lua

Change minorVersion for mobile_api according to develop branch

---

test_scripts/Polices/Validation_of_PolicyTables/074_ATF_usage_and_error_counts_update_count_of_sync_reboots.lua

Replased instant stop of SDL onto shutdown sequence in one of Validation_of_PolicyTables scripts.

Update test script with shutdown sequence

---

test_scripts/Polices/build_options/031_ATF_P_TC_PTU_Retry_Sequence_Retry_Timeout_Computation_HTTP.lua
test_scripts/Polices/build_options/032_ATF_P_TC_PTU_Retry_Sequence_Retry_Timeout_Expiration_HTTP.lua
test_scripts/Polices/build_options/ATF_P_TC_PTU_HTTP_PTU_Unsuccessful_Even_After_Retry_Strategy.lua

Corrections for the scripts according to clarification for exact formula for retry sequence

Correct scripts according to clarification

---

files/jsons/Policies/Policy_Table_Update/ptu_without_preloaded.json
test_scripts/Polices/build_options/022_ATF_P_TC_PTU_Merge_Into_Local_PT_HTTP.lua

Add request type LOCK_SCREEN_ICON_URL to default policies section
in json file

Fix issue with expected param in script

---

style_guide_for_lua_code.md

Created Style guide for Lua code document.
This document defines coding conventions and some recommendations for programming on the Lua language.

Style guide for Lua code

---

test_scripts/Polices/Related_HMI_API/202_ATF_OnAllowSDLFunctionality_allowed_true_without_device.lua

- added params for SDL.OnAllowSDLFunctionality
Related to [ISSUE-1208](https://github.com/smartdevicelink/sdl_core/issues/1208)

Update script 202_ATF_OnAllowSDLFunctionality_allowed_true_without_device.lua

---

files/jsons/Policies/PTU_ValidationRules/valid_PTU_all_sections.json
test_scripts/Polices/Policy_Table_Update/022_ATF_P_TC_Got_PTU_from_mobile_application.lua
test_scripts/Polices/Policy_Table_Update/025_ATF_P_TC_PTU_validation_failure.lua
test_scripts/Polices/Policy_Table_Update/030_ATF_P_TC_Apply_PTU_and_OnPermissionChange_notify.lua
test_scripts/Polices/Related_HMI_API/205_ATF_OnAppPermissionConsent_without_appID.lua
test_scripts/Polices/Validation_of_PolicyTables/254_ATF_pt_snapshot_storage_on_file_system.lua

Fixed issues in scripts that were found during CI fails analysis

Fix issues in scripts

---

files/jsons/Policies/Policy_Table_Update/ign_cycle_ptu.json
files/jsons/Policies/Policy_Table_Update/ptu_22734.json
test_scripts/Polices/App_Permissions/174_ATF_HP_User_Consent_NO.lua
test_scripts/Polices/Validation_of_PolicyTables/220_ATF_preloaded_pt_validation_rules_for_omited_parameters_exist.lua
test_scripts/Polices/Validation_of_PolicyTables/223_ATF_preloaded_pt_validation_rules_for_required_parameters.lua
test_scripts/Polices/Validation_of_PolicyTables/224_ATF_preloaded_pt_invalid_required_param.lua
test_scripts/Polices/Validation_of_PolicyTables/225_ATF_preloaded_pt_invalid_optional_param.lua
test_scripts/Polices/Validation_of_PolicyTables/227_ATF_preloaded_pt_exists_but_no_read_permissions.lua
test_scripts/Polices/Validation_of_PolicyTables/228_ATF_preloaded_pt_does_not_exists.lua
test_scripts/Polices/Validation_of_PolicyTables/229_preloaded_pt_exists.lua
test_scripts/Polices/Validation_of_PolicyTables/233_ATF_preloaded_pt_requesttype_parameters_all_are_invalid.lua
test_scripts/Polices/Validation_of_PolicyTables/248_ATF_pt_snapshot_path_is_incorrect.lua
test_scripts/Polices/Validation_of_PolicyTables/281_ATF_EmptyArray_preconsented_groups_preDataConsent.lua
test_scripts/Polices/Validation_of_PolicyTables/282_ATF_EmptyValue_preconsented_groups_preDataConsent.lua
test_scripts/Polices/build_options/020_ATF_P_TC_PTU_Validation_Failure_HTTP.lua
test_scripts/Polices/build_options/026_ATF_P_TC_PTU_PM_Sets_Status_UPDATE_NEEDED_HTTP.lua
test_scripts/Polices/user_consent_of_Policies/125_ATF_No_user_consent_prompt_in_group.lua
test_scripts/Polices/user_consent_of_Policies/126_ATF_User_consent_prompt_persists.lua

Additional corrections for policies scripts

Fix issues in scripts 2

---

files/ptu.json

Add additional request type (LOCK_SCREEN_ICON_URL) that is required for HTTP PTU scripts

Add additional request type required for HTTP

---

test_scripts/RC/GetInteriorVehicleData/002c.lua
test_scripts/RC/GetInteriorVehicleData/002r.lua
test_scripts/RC/GetInteriorVehicleData/003.lua
test_scripts/RC/GetInteriorVehicleData/004.lua
test_scripts/RC/GetInteriorVehicleData/005.lua
test_scripts/RC/GetInteriorVehicleData/006.lua
test_scripts/RC/GetInteriorVehicleData/007.lua
test_scripts/RC/commonRC.lua
test_sets/rc_GetInteriorVehicleData.txt

- Added new and updated exists tests for GetInteriorVehicleData RPC. 
- Extended policy permission for RC applications.
- Created initial test suite for GetInteriorVehicleData RPC

Created initial test suite for GetInteriorVehicleData RPC

---

test_scripts/RC/SetInteriorVehicleData/001.lua

Delete usage of commonRC.getInteriorZone().

Deleted getinteriorZone function.

---

test_scripts/RC/ButtonPress/001.lua
test_scripts/RC/ButtonPress/002r.lua
test_scripts/RC/ButtonPress/003.lua
test_scripts/RC/ButtonPress/004.lua
test_sets/rc_ButtonPress.txt

Updated old scripts and added two scripts for cases when "moduleType" and "buttonName" related to different modules.

ButtonPress scripts 

---

test_scripts/RC/Capabilities/001_All_modules_all_params.lua
test_scripts/RC/Capabilities/010_Only_CLIMATE_all_params.lua
test_scripts/RC/Capabilities/011_Only_RADIO_all_params.lua
test_sets/rc_Capabilities.txt

- Add tests for RC.GetCapabilities to check allowed rc modules
- Add tests into test set rc_Capabilities

Add tests for RC.GetCapabilities to check allowed rc modules

---

test_scripts/Smoke/Registration/ATF_Register_5_connection.lua

Before this fix WiFi connection was lost after script had been run
Beside of shut down of created connections, some refactoring was also introduced

Added shut down of created connections in Postconditions

---

test_scripts/Smoke/HeartBeat/ATF_HeartBeat_App_does_not_send_HB_and_does_not_respond.lua
test_scripts/Smoke/HeartBeat/ATF_HeartBeat_App_does_not_send_HB_but_respond.lua
test_scripts/Smoke/HeartBeat/ATF_HeartBeat_App_send_HB.lua
test_scripts/Smoke/HeartBeat/ATF_HeartBeat_no_heartbeat_v2_protocol.lua
test_scripts/Smoke/Registration/ATF_Register_5_connection.lua
test_scripts/Smoke/Registration/ATF_Register_5_session.lua
test_scripts/Smoke/Registration/ATF_Register_App.lua
test_scripts/Smoke/Registration/ATF_Reregister_App.lua
test_scripts/Smoke/Registration/ATF_Reregister_App_after_disconnect.lua
test_scripts/Smoke/Registration/ATF_Reregister_App_if_two_apps_are_registered.lua
test_scripts/Smoke/Resumption/ATF_Resumption_3rd_ignition_cycle.lua
test_scripts/Smoke/Resumption/ATF_Resumption_App_Unregister_itself.lua
test_scripts/Smoke/Resumption/ATF_Resumption_BACKGROUND_level.lua
test_scripts/Smoke/Resumption/ATF_Resumption_FULL_IGNITION_OFF.lua
test_scripts/Smoke/Resumption/ATF_Resumption_LIMITED_IGNITION_OFF.lua
test_scripts/Smoke/Resumption/ATF_Resumption_LIMITED_level.lua
test_scripts/Smoke/Resumption/ATF_Resumption_app_registered_in_more_than_30sec_after_BC.OnReady.lua
test_scripts/Smoke/Resumption/ATF_Resumption_big_amount_of_data.lua
test_scripts/Smoke/Resumption/ATF_Resumption_disconnect_more_than_30s_before_SUSPEND.lua
test_scripts/Smoke/Resumption/ATF_Resumption_heartbeat_disconnect.lua
test_scripts/Smoke/Resumption/ATF_Resumption_unexpected_disconnect.lua
test_scripts/Smoke/ShutDown/ATF_ShutDown_IGNITION_OFF.lua
test_scripts/Smoke/ShutDown/ATF_ShutDown_MASTER_RESET.lua
user_modules/shared_testcases/commonStepsResumption.lua

There are following changes in scripts have been made:
1) Corrections due to incorrect usage of StopSDL() function
Before most of the expectations in steps where this function is used are checked partially 
2) Fixes of expectations in some scripts
3) Some refactoring

Fix issues concerning StopSDL

---

test_scripts/template_of_script.lua

@Itileda , @aderiabin Please review

New version of template of script

---

test_scripts/RC/OnRemoteControlSettings/022_Release_resource_on_PTU_with_module_disallow.lua
test_scripts/RC/OnRemoteControlSettings/023_Release_resource_on_PTU_with_app_revoked.lua

Information about RC app2 was added to PTU
This information is needed for last check in script

Information about RC app2 was added to PTU

---

user_modules/shared_testcases/commonTestCases.lua

Some of the test scripts fail due to DelayedExp() function
Timeout is extended by this pull request

Fix: DelayedExp Timeout

---

test_scripts/API/LastMileNavigation/GetWayPoints/001_GetWayPoints_success_flow.lua
test_scripts/API/LastMileNavigation/commonLastMileNavigation.lua

Add LastMileNavigation common module and script for GetWayPoints with success flow

GetWayPoints initial commit

---

test_scripts/API/ATF_Show.lua
user_modules/shared_testcases/commonFunctions.lua
user_modules/shared_testcases/testCasesForArrayEnumParameter.lua
user_modules/shared_testcases/testCasesForMetadataTagsParameter.lua

Test scripts associated with SDL 0073 -- Adding Metadata Types

Adding Test Scripts for metadata tagging feature

---

test_scripts/API/VehicleData/GetVehicleData/001_Success_flow.lua
test_scripts/API/VehicleData/GetVehicleData/002_RPC_parameter_DISALLOWED_by_policies_flow.lua
test_scripts/API/VehicleData/OnVehicleData/001_Success_flow.lua
test_scripts/API/VehicleData/OnVehicleData/002_NotificationForUnsubsribedParameter_Ignored_flow.lua
test_scripts/API/VehicleData/OnVehicleData/003_NotificationParameterDisallowedByPolicies_Ignored_flow.lua
test_scripts/API/VehicleData/SubscribeVehicleData/001_Success_flow.lua
test_scripts/API/VehicleData/SubscribeVehicleData/002_RPC_parameter_DISALLOWED_by_policies_flow.lua
test_scripts/API/VehicleData/SubscribeVehicleData/003_RPC_parameter_already_subscribed_Result_IGNORED_flow.lua
test_scripts/API/VehicleData/UnsubscribeVehicleData/001_Success_flow.lua
test_scripts/API/VehicleData/UnsubscribeVehicleData/002_RPC_parameter_not_yet_subscribed_IGNORED_flow.lua
test_scripts/API/VehicleData/UnsubscribeVehicleData/003_RPC_parameter_already_unsubscribed_Result_IGNORED_flow.lua
test_scripts/API/VehicleData/UnsubscribeVehicleData/004_RPC_parameter_disallowed_by_policies_Result_DISALLOWED_flow.lua
test_scripts/API/VehicleData/commonVehicleData.lua

`"GitHub issue link" ~ "https://github.com/SmartDeviceLink/sdl_core/issues/1656"`

Add test coverage for RPCs containing fuelRange parameter

---

test_scripts/API/ATF_OnTouchEvent.lua

sdl_evolution [SDL-0049](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0049-touch-cancellation.md) is implemented.
SDL Core PR is [here](https://github.com/smartdevicelink/sdl_core/pull/1692)
Please review them.

Add TouchType CANCEL

---

test_scripts/API/Navigation/SendLocation/018_SendLocation_MandatoryOnly_Float.lua
test_scripts/API/Navigation/SendLocation/019_SendLocation_MandatoryOnly_Int.lua
test_scripts/API/Navigation/SendLocation/020_SendLocation_boundary_by_parameters.lua

- MandatoryOnly
- latitudeDegrees bound values
- longitudeDegrees bound values
"GitHub issue link" ~ "https://github.com/smartdevicelink/sdl_core/issues/1740"

New SendLocation scripts

---

test_scripts/Smoke/API/001_SetGlobalProperties_PositiveCase_SUCCESS.lua
test_scripts/Smoke/commonSmoke.lua
test_scripts/Smoke/commonSmokeApi.lua

Added initial test script for testing SetGlobalProperties happy path and also added new common module for smoke API testing.
`"GitHub issue link" ~ " https://github.com/SmartDeviceLink/sdl_atf/issues/97"`

Add smoke API test script for SetGlobalProperties

---

test_scripts/API/Navigation/OnWayPointChange/006_OnWayPointChange_OnlyManadatoryParams.lua
test_scripts/API/Navigation/OnWayPointChange/007_OnWayPointChange_OnlyManadatoryParamsEmpty_success.lua
test_scripts/API/Navigation/OnWayPointChange/008_OnWayPointChange_boundary_values_by_parameters.lua
test_scripts/API/Navigation/OnWayPointChange/009_OnWayPointChange_out_boundary_values_by_parameters.lua
test_scripts/API/Navigation/OnWayPointChange/010_OnWayPointChange_ImageWithUnknownValue.lua
test_scripts/API/Navigation/OnWayPointChange/011_OnWayPointChange_invalid_types.lua
test_scripts/API/Navigation/OnWayPointChange/012_OnWayPointChange_invalid_characters.lua
test_scripts/API/Navigation/OnWayPointChange/013_OnWayPointChange_invalid_json.lua
test_scripts/API/Navigation/OnWayPointChange/014_OnWayPointChange_WithInvalidJsonStructure.lua
test_scripts/API/Navigation/OnWayPointChange/015_OnWayPointChange_WithFakeParams_SuccessWOFakeParams.lua
test_scripts/API/Navigation/OnWayPointChange/016_OnWayPointChange_WithFakeParamsFromAnotherAPI_SuccessWOFakeParams.lua
test_scripts/API/Navigation/OnWayPointChange/017_OnWayPointChange_SeveralNotificationsWithIdenticalParams_AllSuccess.lua
test_scripts/API/Navigation/OnWayPointChange/018_OnWayPointChange_SeveralNotificationsWithDiffParams_AllSuccess.lua
test_scripts/API/Navigation/OnWayPointChange/019_OnWayPointChange_diff_HMI_levels.lua

- boundary values by params
- out of bound values by params
- invalid characters \t, \n, whitespace only
- invalid parameter types
- invalid json
- processing API in different HMI levels

Regression scripts for OnWayPointChange

---

test_scripts/API/VehicleData/OnVehicleData/004_OnVehicleData_fuelRange_bound_values.lua
test_scripts/API/VehicleData/OnVehicleData/005_OnVehicleData_fuelRange_out_bound_values.lua
test_scripts/API/VehicleData/OnVehicleData/006_OnVehicleData_fuelRange_invalid_types.lua
test_scripts/API/VehicleData/OnVehicleData/007_OnVehicleData_fuelRange_params_missed.lua

- boundary values
- out of boundary values
- invalid types
- params missed

Expanded coverage for FuelRange in OnVehicleData

---

test_scripts/API/System/OnSystemRequest/001_OnSystemRequest_send_binaryData_for_any_requestType.lua
test_scripts/API/System/commonSystem.lua

https://github.com/SmartDeviceLink/sdl_core/issues/1714

Check that the SDL sends binary data using the OnSystemRequest RPC for any requestType

---

test_scripts/API/VehicleData/GetVehicleData/003_GetVD_fuelRange_boundary_values.lua
test_scripts/API/VehicleData/GetVehicleData/004_GetVD_fuelRange_out_boundary_values.lua
test_scripts/API/VehicleData/GetVehicleData/005_GetVD_fuelRange_params_missed.lua
test_scripts/API/VehicleData/GetVehicleData/006_GetVD_fuelRange_params_invalid_type.lua
test_scripts/API/VehicleData/GetVehicleData/007_GetVD_fuelRange_missed.lua

- boundary values
- out of boundary values
- missed params
- invalid types
- missed fuelRange parameter in HMI response
"GitHub issue link" ~ "https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0072-New-vehicle-data-FuelRange.md"

Expanded test scripts for GetVD(FuelRange)

---

test_scripts/API/Navigation/GetWayPoints/012_GetWayPoints_boundary_values.lua
test_scripts/API/Navigation/GetWayPoints/013_GetWayPoints_verify_correlationID_parameter.lua
test_scripts/API/Navigation/GetWayPoints/014_GetWayPoints_OnResetTimeout.lua
test_scripts/API/Navigation/GetWayPoints/015_GetWayPoints_empty_wayPoints.lua

1. boundary values
2. verify correlation ID parameter 
3. OnResetTimeout
4. empty wayPoints array element

Additional scripts for GetWayPoints

---

test_scripts/API/Navigation/GetWayPoints/016_GetWayPoints_bound_value_by_parameters.lua
test_scripts/API/Navigation/GetWayPoints/017_GetWayPoints_out_bound_value_by_parameters.lua
test_scripts/API/Navigation/GetWayPoints/018_GetWayPoints_fake_parameters.lua
test_scripts/API/Navigation/GetWayPoints/019_GetWayPoints_duplicated_corr_id.lua
test_scripts/API/Navigation/GetWayPoints/020_GetWayPoints_invalid_HMI_responses.lua
test_scripts/API/Navigation/GetWayPoints/021_GetWayPoints_diff_HMI_levells.lua
test_scripts/API/Navigation/GetWayPoints/022_GetWayPoints_invalid_characters.lua
test_scripts/API/Navigation/GetWayPoints/023_GetWayPoints_app_not_registered.lua
test_scripts/API/Navigation/GetWayPoints/024_GetWayPoints_invalid_types_in_HMIresponse.lua
test_scripts/API/Navigation/GetWayPoints/025_GetWayPoints_mandatory_missed_in_HMIresponse.lua
test_scripts/API/Navigation/GetWayPoints/026_GetWayPoints_several_responses.lua

- bound values by parameters
- out bound values by parameters
- fake, from another parameters 
- duplicated correlation id
- invalid HMI response
- processing API in different HMI levels
- invalid characters in HMI response
- APP_NOT_REGISTERED

Regression scripts for GetWayPoints

---

test_scripts/Smoke/API/001_SetGlobalProperties_PositiveCase_SUCCESS.lua
test_scripts/Smoke/API/002_ResetGlobalProperties_PositiveCase_SUCCESS.lua
test_scripts/Smoke/API/003_AddCommand_PositiveCase_SUCCESS.lua
test_scripts/Smoke/API/004_DeleteCommand_PositiveCase_SUCCESS.lua
test_scripts/Smoke/API/005_AddSubMenu_PositiveCase_SUCCESS.lua
test_scripts/Smoke/API/006_DeleteSubMenu_PositiveCase_SUCCESS.lua
test_scripts/Smoke/API/007_Alert_PositiveCase_SUCCESS.lua
test_scripts/Smoke/API/008_CreateInteractionChoiceSet_PositiveCase_SUCCESS.lua
test_scripts/Smoke/API/009_DeleteInteractionChoiceSet_PositiveCase_SUCCESS.lua
test_scripts/Smoke/API/010_DeleteFile_PositiveCase_SUCCESS.lua
test_scripts/Smoke/API/011_ListFiles_PositiveCase_SUCCESS.lua
test_scripts/Smoke/commonSmoke.lua

Add new smoke test scripts

---

test_scripts/Policies/build_options/103_ATF_Timeout_wait_response_PTU_PROPRIETARY.lua

Fix script

---

test_scripts/iAP2TransportSwitch/001_happy_path.lua
test_scripts/iAP2TransportSwitch/002_resume_failed_simple_case.lua
test_scripts/iAP2TransportSwitch/003_resume_failed_remove_data_check.lua
test_scripts/iAP2TransportSwitch/004_commands_hold_while_switching.lua
test_scripts/iAP2TransportSwitch/common.lua
test_scripts/smoke_api.lua

Now switching is being triggered externally so new signals handling has
been addes and tests have been changed accordingly.

Updates tests according to switching flow changes

---

test_scripts/Defects/4_5/1376_PTU_all_flows.lua

Script to verify that SDL attach binary data to OnSystemRequest notification during PTU
https://github.com/SmartDeviceLink/sdl_core/issues/1376

Script to verify that SDL attach binary data to OnSystemRequest notification during PTU - Drop2

---

test_scripts/Defects/4_5/1395_Resumption_data_IGN_OFF.lua

Script that verifies SUSPEND -> OnSDLAwake -> SUSPEND -> IGN_OFF sequence for resumption data saving
https://github.com/smartdevicelink/sdl_core/issues/1395

Script that verifies SUSPEND -> OnSDLAwake -> SUSPEND -> IGN_OFF sequence for resumption data saving - Drop2

---

test_scripts/Defects/4_5/1225_FACTORY_DEFAULTS.lua
test_scripts/Defects/4_5/1376_PTU_all_flows.lua
test_scripts/Defects/4_5/1395_Resumption_data_IGN_OFF.lua
test_scripts/Defects/4_5/1772_update_default_section.lua

Added comments in scripts

---

test_scripts/Defects/4_5/1892_HB_from_SDL_after_receiving_HB_from_mobile.lua

Added comments in script 1892

---

test_scripts/Smoke/HeartBeat/ATF_HeartBeat_App_does_not_send_HB_and_does_not_respond.lua
test_scripts/Smoke/HeartBeat/ATF_HeartBeat_App_does_not_send_HB_but_respond.lua

Fix due to changes made in ATF: https://github.com/smartdevicelink/sdl_atf/pull/110

Fix test scripts related to Heartbeat due to corresponding changes in ATF

---

test_scripts/Policies/appID_Management/046_ATF_Register_App_Interface_Assign_Existing_Policies_To_Application_Which_Appid_Exists_In_LPT.lua

Updated 046 policy script because of error in test step.

Updated policy script

---

test_scripts/Smoke/HeartBeat/ATF_HeartBeat_App_does_not_send_HB_and_does_not_respond.lua
test_scripts/Smoke/HeartBeat/ATF_HeartBeat_App_does_not_send_HB_but_respond.lua
test_scripts/smoke_api.lua
test_sets/smoke_tests.txt

This PR fix test script due to changes regarding [SendLocation Updates](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0004-sendlocation-updates.md)
It needs to be merged along with https://github.com/smartdevicelink/sdl_core/pull/1821

Smoke: Remove turnText item and other fixes

---

test_scripts/Smoke/API/012_PerfomInteraction_PositiveCase.lua
test_scripts/Smoke/API/013_ScrollableMessage_PositiveCase.lua
test_scripts/Smoke/commonSmoke.lua

Separated scripts from smoke API script for PerformInteraction and ScrollableMessage

Smoke: Separated scripts for PI and ScrMsg from smoke API script

---

test_scripts/Smoke/API/014_SetMediaClockTimer_PositiveCase.lua
test_scripts/Smoke/API/015_Show_PositiveCase.lua
test_scripts/Smoke/commonSmoke.lua

Separated scripts from smoke API script for SetMediaClockTimer and Show

Smoke: Separated scripts for SetTimer and Show from smoke API script

---

test_scripts/Smoke/API/032_EndAudioPassThru_PositiveCase.lua
test_scripts/Smoke/API/033_ReadDID_PositiveCase.lua

Separated scripts for EndAudioPassThru and ReadDID from smoke API script

Smoke: Separated scripts for EndAudioPassThru and ReadDID from smoke API script

---

test_scripts/Smoke/API/028_AlertManeuver_PositiveCase.lua
test_scripts/Smoke/API/029_OnDriverDistraction_PositiveCase.lua

Separated scripts for AlertManeuver and OnDriverDistraction from smoke API script

Smoke: Separated scripts for AlertManeuver and OnDriverDistraction from smoke API script

---

test_scripts/Smoke/API/026_GetVehicleData_PositiveCase.lua
test_scripts/Smoke/API/027_UpdateTurnList_PositiveCase.lua

Separated scripts for GetVehicleData and UpdateTurnList from smoke API script

Smoke: Separated scripts for GetVD and UpdateTurnList from smoke API script

---

test_scripts/Smoke/API/024_SubscribeVehicleData_PositiveCase.lua
test_scripts/Smoke/API/025_UnsubscribeVehicleData_PositiveCase.lua

Separated scripts for UnsubscribeVehicleData  and SubscribeVehicleData from smoke APi script

Smoke: Separated scripts for UnsubscribeVD  and SubscribeVD from smoke APi script

---

test_scripts/Smoke/API/030_DialNumber_PositiveCase.lua
test_scripts/Smoke/API/031_PerformAudioPassThru_PositiveCase.lua

Separated scripts for DialNumber and PerformAudioPassThru from smoke API script

Smoke: Separated scripts for DialNumber and PerformAudioPassThru from smoke API script

---

test_scripts/Smoke/API/022_SubscribeButton_PositiveCase.lua
test_scripts/Smoke/API/023_UnsubscribeButton_PositiveCase.lua

Separated scripts for SubscribeButton and UnsubscribeButton from smoke API script

Smoke: Separated scripts for SubscribeButton and UnsubscribeButton from smoke API script

---

test_scripts/Smoke/API/016_ShowConstantTBT_PositiveCase_SUCCESS.lua
test_scripts/Smoke/API/017_Slider_PositiveCase_SUCCESS.lua

Separated scripts for ShowConstantTBT and Slider from smoke API script

Smoke: Separated scripts for ShowConstantTBT and Slider from smoke API script

---

test_scripts/Smoke/API/036_UnregisterAppInterface_PositiveCase_SUCCESS.lua
test_scripts/Smoke/API/037_RegisterAppInterface_PositiveCase_SUCCESS.lua

Separated scripts for RegisterAppInterface and UnregisterAppInterface from smoke API script

Smoke: Separated scripts for Register and UnregisterAppInterface from smoke API script

---

test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/common.lua

There was intersection between 2 PTU sequences
This PR resolve it by adding additional expectation on HMI side

Improve stability of the scripts on security

---

test_scripts/Defects/4_5/1225_FACTORY_DEFAULTS.lua
test_scripts/Defects/4_5/1376_PTU_all_flows.lua
test_scripts/Defects/4_5/1912_Video_service_start_via_2_protocol.lua
test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/common.lua
test_scripts/Defects/4_5/commonDefects.lua

Update the calculation logic for MAC address and device id

Fix obtaining of MAC address and Device Id

---

test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/001_Success_flow.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/002_Disallow_flow_by_policy_AUDIO.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/003_Disallow_flow_by_policy_LIGHT.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/004_Disallow_flow_by_policy_HMI_SETTINGS.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/005_Disallow_flow_in_case_appHMIType_is_not_REMOTE_CONTROL.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/006_RPC_parameters_values.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/007_GENERIC_ERROR_in_case_HMI_did_not_respond.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/008_GENERIC_ERROR_in_case_HMI_respond_with_invalid_data.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/009_Success_flow_in_case_moduleType_is_an_empty_array_in_LPT.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/010_Disallow_flow_in_case_moduleType_is_absent_in_LPT.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/011_GENERIC_ERROR_in_case_HMI_respond_with_READ_ONLY.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/012_Transfering_of_HMI_resultCode_to_mobile.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/013_Absence_of_isSubscribed_parameter_in_case_request_from_Mob_app_without_subscribe_parameter_but_response_from_HMI_with_isSubscribed.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/014_Absence_of_subscribe_parameter_in_request_for_HMI_in_case_of_2nd_Subscription_UnSubscription.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/015_Transfering_of_isSubscribed_parameter_in_case_request_from_Mob_app_with_subscribe_parameter_but_response_from_HMI_without_isSubscribed.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/commonRCmodules.lua
test_scripts/RC/commonRC.lua

Initial scripts for GetInteriorVehicleData for LIGHT, AUDIO, HMI_SETTINGS feature

Initial scripts for GetInteriorVehicleData for LIGHT, AUDIO, HMI_SETTINGS feature

---

test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleDataConsent/001_Consent_true_SIVD.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleDataConsent/002_Consent_false_SIVD.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleDataConsent/003_TIMED_OUT_from_HMI_SIVD.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleDataConsent/004_HMI_no_response_SIVD.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleDataConsent/005_HMI_invalid_response_SIVD.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/OnInteriorVehicleData/001_Success_flow.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/OnInteriorVehicleData/002_Disallow_flow_by_policy_AUDIO.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/OnInteriorVehicleData/003_Disallow_flow_by_policy_LIGHT.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/OnInteriorVehicleData/004_Disallow_flow_by_policy_HMI_SETTINGS.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/OnInteriorVehicleData/005_Absence_of_OnIVD_in_case_of_successfull_subscribing_with_isSubscribe_false_from_HMI.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/OnInteriorVehicleData/009_Existence_of_OnIVD_in_case_of_successfull_unsubscribing_with_isSubscribe_true_from_HMI.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/OnInteriorVehicleData/010_Existence_of_OnIVD_in_case_of_successfull_unsubscribing_without_isSubscribe_from_HMI.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/OnInteriorVehicleData/011_Existence_of_OnIVD_in_case_of_unsuccessfull_unsubscribing_without_isSubscribe_from_HMI.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/commonRCmodules.lua

Initial scripts for GetIVDConsent, OnIVD for AUDIO,LIGHT,HMI_SETTINGS feature

Initial scripts for GetIVDConsent, OnIVD for AUDIO,LIGHT,HMI_SETTINGS feature

---

test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/OnRemoteControlSettings/001_SUCCESS_in_case_AUTO_ALLOW_seq_1.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/OnRemoteControlSettings/005_REJECTED_in_case_nonFULL_HMI_level.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/OnRemoteControlSettings/009_Allowed_true_accessMode_AUTO_ALLOW.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/OnRemoteControlSettings/010_Allowed_true_accessMode_AUTO_DENY.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/OnRemoteControlSettings/011_Allowed_true_accessMode_ASK_DRIVER.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/OnRemoteControlSettings/012_Default_accessMode.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/commonRCmodules.lua

Initial scripts for OnRemoteControlSettings for AUDIO, LIGHT, HMI_SETTINGS feature

Initial scripts for OnRemoteControlSettings for AUDIO, LIGHT, HMI_SETTINGS feature

---

test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/001_Success_flow.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/002_Disallow_flow_by_policy_CLIMATE.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/003_Disallow_flow_by_policy_AUDIO.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/004_Disallow_flow_by_policy_LIGHT.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/005_Disallow_flow_by_policy_HMI_SETTINGS.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/007_Success_flow_in_case_moduleType_is_an_empty_array_in_LPT.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/008_Disallow_flow_in_case_moduleType_is_absent_in_LPT.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/010_Read_only_response_for_set_interior_vehicle_data_if_read_only_params_requested.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/016_Change_audio_source_in_FULL.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/017_Change_audio_source_in_BACKGROUND.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/018_Change_audio_source_in_FULL_rc_non_media_app.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/019_Change_audio_source_from_MOBILE_APP_without_keepContext.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/020_Change_audio_source_from_MOBILE_APP_keepContext_false.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/021_Change_audio_source_from_MOBILE_APP_keepContext_true.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/022_Change_audio_source_from_any_type_except_MOBILE_APP_keepContext_true.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/commonRCmodules.lua

Initial scripts for SetInteriorVD for AUDIO, LIGHT, HMI_SETTINGS feature

Initial scripts for SetInteriorVD for AUDIO, LIGHT, HMI_SETTINGS feature

---

test_scripts/Defects/4_5/Trigger_PTU_NO_Certificate/common.lua
test_scripts/LowVoltage/001_Low_Voltage_and_Wake_Up.lua
test_scripts/LowVoltage/002_Low_Voltage_and_Shut_Down.lua
test_scripts/LowVoltage/003_Wake_Up_and_Shut_Down_wo_Low_Voltage.lua
test_scripts/LowVoltage/004_App_registered_30_sec_after_Wake_Up.lua
test_scripts/LowVoltage/005_App_disconnected_30_sec_before_Low_Voltage.lua
test_scripts/LowVoltage/006_App_unregister_itself_gracefully.lua
test_scripts/LowVoltage/007_Low_Voltage_and_Wake_Up_RPC_in_progress.lua
test_scripts/LowVoltage/common.lua
test_sets/low_voltage.txt
user_modules/sequences/actions.lua

This is new PR for Low Voltage feature.
Previous PR https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1823 was closed.

Test scripts for Low Voltage feature

---

test_scripts/DTLS/001_StartRPC_service.lua
test_scripts/DTLS/002_Start_Audio_service.lua
test_scripts/DTLS/003_Start_Video_service.lua
test_scripts/DTLS/004_Processing_of_RPC.lua
test_scripts/DTLS/005_Ignore_malformed_packet.lua
test_scripts/DTLS/006_Ignore_unexpected_packet.lua
test_scripts/DTLS/007_Processing_multiple_frames.lua
test_scripts/DTLS/common.lua
test_sets/dtls_encryption.txt

This is new PR for DTLS feature.
Previous PR https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1831 was closed.

Test scripts for DTLS encryption feature

---

test_scripts/RC/OnRCStatus/005_notification_by_module_allocation_ButtonPress.lua
test_scripts/RC/OnRCStatus/006_notification_by_module_allocation_SetInteriorVehicleData.lua
test_scripts/RC/OnRCStatus/008_notification_by_module_allocation_ButtonPress_two_apps.lua
test_scripts/RC/OnRCStatus/009_notification_by_module_allocation_SetInteriorVehicleData_two_apps.lua
test_scripts/RC/OnRCStatus/010_notification_by_module_allocation_two_apps_one_app_not_rc.lua
test_scripts/RC/OnRCStatus/011_notification_by_app_unregistration.lua
test_scripts/RC/OnRCStatus/012_notification_by_revoking_module_by_policy.lua
test_scripts/RC/OnRCStatus/013_notification_by_reallocation_module_by_the_same_app.lua
test_scripts/RC/OnRCStatus/014_notification_by_reallocation_module_by_second_app.lua
test_scripts/RC/OnRCStatus/015_notification_by_user_exit.lua
test_scripts/RC/OnRCStatus/016_notification_by_DRIVER_DISTRACTION_VIOLATION.lua
test_scripts/RC/OnRCStatus/017_notification_by_rejecting_consent_by_driver.lua
test_scripts/RC/OnRCStatus/018_notification_by_driver_consent.lua
test_scripts/RC/OnRCStatus/019_notification_by_app_disconnect.lua
test_scripts/RC/OnRCStatus/020_notification_in_case_of_policy_permissions_absence.lua
test_scripts/RC/OnRCStatus/021_notification_in_case_AUTO_DENY_mode.lua
test_scripts/RC/OnRCStatus/commonOnRCStatus.lua

Changes according to resolved question https://github.com/smartdevicelink/sdl_requirements/issues/44

Changes according to resolved question 44

---

test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/commonRCmodules.lua

Removed keepContext from GetInterVD and OnInterVD

Removed keepContext from GetInterVD and OnInterVD

---

test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/002_Disallow_flow_by_policy_CLIMATE.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/003_Disallow_flow_by_policy_AUDIO.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/004_Disallow_flow_by_policy_LIGHT.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/005_Disallow_flow_by_policy_HMI_SETTINGS.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/007_Success_flow_in_case_moduleType_is_an_empty_array_in_LPT.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/008_Disallow_flow_in_case_moduleType_is_absent_in_LPT.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/010_Read_only_response_for_set_interior_vehicle_data_if_read_only_params_requested.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/016_Change_audio_source_in_FULL.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/017_Change_audio_source_in_BACKGROUND.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/018_Change_audio_source_in_FULL_rc_non_media_app.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/019_Change_audio_source_from_MOBILE_APP_without_keepContext.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/020_Change_audio_source_from_MOBILE_APP_keepContext_false.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/021_Change_audio_source_from_MOBILE_APP_keepContext_true.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/022_Change_audio_source_from_any_type_except_MOBILE_APP_keepContext_true.lua
test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/commonRCmodules.lua

Added processing read only parameter for AUDIO module.

Added read only parameter for AUDIO module

---

test_scripts/Image_template/001_isTemplate_is_true.lua
test_scripts/Image_template/002_isTemplate_is_false.lua
test_scripts/Image_template/003_isTemplate_is_absent.lua
test_scripts/Image_template/004_isTemplate_invalid_type.lua
test_scripts/Image_template/commonImageTemplate.lua
test_sets/template_images.txt

Initial scripts for Template images feature

Initial scripts for Template images feature

---

test_scripts/MobileProjection/Phase2/005_audioStreamingState_111-114.lua
test_scripts/MobileProjection/Phase2/007_videoStreamingState_007-030.lua
test_sets/mobile_projection_2.txt

Added additional scripts

---

test_scripts/Defects/4_6/959_resumption_limited_non_media.lua
test_scripts/Defects/commonDefects.lua

Script for reproducing issue [HMILevel is not resumed to LIMITED for non-media applications](https://github.com/smartdevicelink/sdl_core/issues/959)

Script for reproducing issue 959

---

test_scripts/API/SubMenuIcon/001_menuIcon_is_SUCCESS.lua
test_scripts/API/SubMenuIcon/002_menuIcon_invalid_type.lua
test_scripts/API/SubMenuIcon/003_menuIcon_selected_not_existing_file.lua
test_scripts/API/SubMenuIcon/004_menuIcon_is_absent.lua
test_scripts/API/SubMenuIcon/commonSubMenuIcon.lua
test_sets/submenu_icon.txt

Scripts for "SubMenu icon"  feature.
Proposal: https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0085-submenu-icon.md

Scripts for feature "SubMenu icon"

---

test_scripts/API/VehicleData/GetVehicleData/001_Success_flow.lua
test_scripts/API/VehicleData/GetVehicleData/002_RPC_parameter_DISALLOWED_by_policies_flow.lua
test_scripts/API/VehicleData/OnVehicleData/001_Success_flow.lua
test_scripts/API/VehicleData/OnVehicleData/002_NotificationForUnsubsribedParameter_Ignored_flow.lua
test_scripts/API/VehicleData/OnVehicleData/003_NotificationParameterDisallowedByPolicies_Ignored_flow.lua
test_scripts/API/VehicleData/SubscribeVehicleData/001_Success_flow.lua
test_scripts/API/VehicleData/SubscribeVehicleData/002_RPC_parameter_DISALLOWED_by_policies_flow.lua
test_scripts/API/VehicleData/SubscribeVehicleData/003_RPC_parameter_already_subscribed_Result_IGNORED_flow.lua
test_scripts/API/VehicleData/UnsubscribeVehicleData/001_Success_flow.lua
test_scripts/API/VehicleData/UnsubscribeVehicleData/002_RPC_parameter_not_yet_subscribed_IGNORED_flow.lua
test_scripts/API/VehicleData/UnsubscribeVehicleData/003_RPC_parameter_already_unsubscribed_Result_IGNORED_flow.lua
test_scripts/API/VehicleData/UnsubscribeVehicleData/004_RPC_parameter_disallowed_by_policies_Result_DISALLOWED_flow.lua
test_scripts/API/VehicleData/commonVehicleData.lua
test_sets/EngineOilLife.txt

ATF scripts for testing New vehicle data - EngineOilLife feature
Proposal: [New vehicle data - EngineOilLife](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0082-New-vehicle-data-EngineOilLife.md)

New vehicle data - EngineOilLife feature

---

test_scripts/MobileProjection/Phase2/021_two_apps_and_deactivation.lua
test_scripts/MobileProjection/Phase2/022_two_apps_proj_media_and_deactivation_streaming.lua
test_scripts/MobileProjection/Phase2/023_two_apps_navi_comm_and_deactivation_streaming.lua
test_scripts/MobileProjection/Phase2/common.lua
test_sets/mobile_projection_2.txt

Add new scripts on 2 apps and deactivation

Add new scripts on 2 apps and deactivation

---

test_scripts/API/VehicleData/GetVehicleData/001_Success_flow.lua
test_scripts/API/VehicleData/GetVehicleData/002_RPC_parameter_DISALLOWED_by_policies_flow.lua
test_scripts/API/VehicleData/OnVehicleData/001_Success_flow.lua
test_scripts/API/VehicleData/OnVehicleData/002_NotificationForUnsubsribedParameter_Ignored_flow.lua
test_scripts/API/VehicleData/OnVehicleData/003_NotificationParameterDisallowedByPolicies_Ignored_flow.lua
test_scripts/API/VehicleData/SubscribeVehicleData/001_Success_flow.lua
test_scripts/API/VehicleData/SubscribeVehicleData/002_RPC_parameter_DISALLOWED_by_policies_flow.lua
test_scripts/API/VehicleData/SubscribeVehicleData/003_RPC_parameter_already_subscribed_Result_IGNORED_flow.lua
test_scripts/API/VehicleData/UnsubscribeVehicleData/001_Success_flow.lua
test_scripts/API/VehicleData/UnsubscribeVehicleData/002_RPC_parameter_not_yet_subscribed_IGNORED_flow.lua
test_scripts/API/VehicleData/UnsubscribeVehicleData/003_RPC_parameter_already_unsubscribed_Result_IGNORED_flow.lua
test_scripts/API/VehicleData/UnsubscribeVehicleData/004_RPC_parameter_disallowed_by_policies_Result_DISALLOWED_flow.lua
test_scripts/API/VehicleData/commonVehicleData.lua

Add new tire pressure parameters to vehicle data test scripts.

Add new tire pressure parameters

---

test_scripts/Image_template/001_isTemplate_is_true.lua
test_scripts/Image_template/002_isTemplate_is_false.lua
test_scripts/Image_template/003_isTemplate_is_absent.lua
test_scripts/Image_template/004_isTemplate_invalid_type.lua
test_scripts/Image_template/005_isTemplate_is_true_with_not_png_image.lua
test_scripts/Image_template/006_isTemplate_is_true_with_STATIC_image.lua
test_scripts/Image_template/commonImageTemplate.lua
test_sets/template_images.txt

ATF Test Scripts to check #[1588](https://github.com/smartdevicelink/sdl_core/issues/1588)
Scripts for 'Template images' feature.
[Develop branch](https://github.com/smartdevicelink/sdl_atf/tree/develop)

Scripts for feature "Template images" feature

---

test_scripts/RC/CLIMATE_RADIO/GetSystemCapability/001_Success_flow.lua
test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/016_UNSUPPORTED_RESOURCE_hdRadioEnableAvailable_false.lua
test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/017_UNSUPPORTED_RESOURCE_hdRadioEnableAvailable_omitted.lua
test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/018_Success_flow_band_setting.lua
test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/019_UNSUPPORTED_RESOURCE_siriusxmRadioAvailable_false.lua
test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/020_UNSUPPORTED_RESOURCE_siriusxmRadioAvailable_omitted.lua
test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/021_INVALID_DATA_in_case_invalid_data_in_hdRadioEnable.lua
test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/022_availableHDs_hdChannel_upper_bound.lua
test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/023_availableHDs_hdChannel_out_of_upper_bound.lua
test_scripts/RC/commonRC.lua
test_sets/rc_radio_parameter_update.txt
user_modules/hmi_values.lua

ATF Test Scripts to check #[2162](https://github.com/smartdevicelink/sdl_core/issues/2162)
Scripts for feature "Remote Control Radio Parameter Update" 
[Develop branch](https://github.com/smartdevicelink/sdl_atf/tree/develop)

Initial scripts for feature "Radio parameter update"

---

test_scripts/Defects/4_6/1218_Mandatory_parameter_spaceAvailable_is_not_provided_in_response_for_PutFile_request.lua

Script for reproducing issue [Mandatory parameter 'spaceAvailable' is not provided in response for PutFile request](https://github.com/smartdevicelink/sdl_core/issues/1218)

Script for reproducing issue 1218

---

README.md

Remove outdated information about running all test scripts and update manual setup

Update README with recent information

---

test_scripts/RC/OnRCStatus/001_notification_by_apps_registration.lua
test_scripts/RC/OnRCStatus/007_notification_by_module_subscription_GetInteriorVehicleData_two_apps.lua
test_scripts/RC/OnRCStatus/009_notification_by_module_allocation_SetInteriorVehicleData_two_apps.lua
test_scripts/RC/OnRCStatus/010_notification_by_module_allocation_two_apps_one_app_not_rc.lua
test_scripts/RC/OnRCStatus/018_notification_by_driver_consent.lua
test_scripts/RC/OnRCStatus/022_notification_by_rc_functionality_disallowed_on_hmi_with_registered_app.lua
test_scripts/RC/OnRCStatus/023_notification_by_rc_functionality_allowed_on_hmi_with_registered_app.lua
test_scripts/RC/OnRCStatus/commonOnRCStatus.lua
test_sets/rc_OnRCStatus.txt

Initial scripts for 'Update OnRCStatus with a new allowed parameter' feature

Initial scripts for 'Update OnRCStatus with a new allowed parameter' feature

---

test_scripts/API/SubMenuIcon/001_menuIcon_is_SUCCESS.lua
test_scripts/API/SubMenuIcon/002_menuIcon_invalid_type.lua
test_scripts/API/SubMenuIcon/003_menuIcon_selected_not_existing_file.lua
test_scripts/API/SubMenuIcon/004_menuIcon_is_absent.lua
test_scripts/API/SubMenuIcon/commonSubMenuIcon.lua
test_scripts/SDL4.6/SDL-0162/001_DuplicateCorrelationIDs_INVALID_ID.lua
test_sets/submenu_icon.txt

ATF Test Scripts to check #[1747](https://github.com/smartdevicelink/sdl_core/issues/1747)
Scripts for feature "SubMenu icon" 
[Develop branch](https://github.com/smartdevicelink/sdl_atf/tree/develop)

Scripts for feature "SubMenu icon" 

---

test_scripts/RC/OnRCStatus/020_notification_in_case_of_policy_permissions_absence.lua
test_scripts/RC/OnRCStatus/022_notification_by_rc_functionality_disallowed_on_hmi_with_registered_app.lua
test_scripts/RC/OnRCStatus/023_notification_by_rc_functionality_allowed_on_hmi_with_registered_app.lua
test_scripts/RC/OnRCStatus/024_notification_by_apps_registration_several_apps.lua
test_scripts/RC/OnRCStatus/025_notification_by_rc_functionality_disallowed_on_hmi_sevaral_apps.lua
test_scripts/RC/OnRCStatus/025_notification_by_rc_functionality_disallowed_on_hmi_several_apps.lua
test_scripts/RC/OnRCStatus/026_registration_non_rc_app_several_apps.lua
test_scripts/RC/OnRCStatus/027_registration_non_rc_app_several_apps_rc_disallowed.lua
test_scripts/RC/OnRCStatus/commonOnRCStatus.lua
test_sets/rc_OnRCStatus.txt

Changes for OnRCStatus(allowed):
-- Not expect OnRCStatus notification on HMI by app registration
-- Expect OnRCStatus notification on HMI by changing disable/enable RC from HMI

Changes for OnRCStatus(allowed)

---

test_scripts/Defects/4_5/1881_OnDriverDistraction_After_changing_HMIlevel_from_NONE.lua
test_scripts/Defects/4_5/commonDefects.lua
test_scripts/Defects/commonDefects.lua
test_scripts/RC/commonRC.lua
test_scripts/Smoke/commonSmoke.lua

ATF Test changes for https://github.com/smartdevicelink/sdl_core/pull/2344

Add expectation for OnDriverDistraction on app registration

---

test_scripts/RC/OnRCStatus/commonOnRCStatus.lua

update scripts for Remote Control - Update OnRCStatus with a new allowed parameter
(proposal: https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0172-onRcStatus-allowed.md) according to discussion https://github.com/smartdevicelink/sdl_core/pull/2306#discussion_r202067957

Fix validation of parameter allowed

---

test_scripts/SDL4_6/MobileVersioning/vrCommandOptional/001_create_interaction_choice_success_legacy_app.lua
test_scripts/SDL4_6/MobileVersioning/vrCommandOptional/002_create_interaction_choice_invalid_data_legacy_app.lua
test_scripts/SDL4_6/MobileVersioning/vrCommandOptional/003_perform_interaction_success_legacy_app.lua
test_scripts/SDL4_6/vrCommandOptional/001_create_interaction_choice_set_invalid_data.lua
test_scripts/SDL4_6/vrCommandOptional/002_perform_interaction_invalid_data.lua
test_scripts/Smoke/API/008_CreateInteractionChoiceSet_PositiveCase_SUCCESS.lua
test_scripts/Smoke/API/012_PerfomInteraction_PositiveCase_SUCCESS.lua
test_sets/mobile_api_versioning.txt

fixes #1988, also fixes choise/choice typo while we're here

Add test for choice with no vrCommands, fix typo in file

---

test_scripts/RC/CLIMATE_RADIO/GetSystemCapability/001_Success_flow.lua
test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/016_UNSUPPORTED_RESOURCE_hdRadioEnableAvailable_false.lua
test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/017_UNSUPPORTED_RESOURCE_hdRadioEnableAvailable_omitted.lua
test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/018_Success_flow_band_setting.lua
test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/019_UNSUPPORTED_RESOURCE_siriusxmRadioAvailable_false.lua
test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/020_UNSUPPORTED_RESOURCE_siriusxmRadioAvailable_omitted.lua
test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/021_INVALID_DATA_in_case_invalid_data_in_hdRadioEnable.lua
test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/022_availableHDs_hdChannel_upper_bound.lua
test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/023_availableHDs_hdChannel_out_of_upper_bound.lua
test_scripts/RC/commonRC.lua
test_sets/rc_radio_parameter_update.txt
user_modules/hmi_values.lua

ATF Test Scripts to check #[2162](https://github.com/smartdevicelink/sdl_core/issues/2162)
Scripts for feature "Remote Control Radio Parameter Update" 
[Develop branch](https://github.com/smartdevicelink/sdl_atf/tree/develop)

Scripts for feature "Remote Control Radio Parameter Update" 

---

test_scripts/SDL4_6/MobileVersioning/VersionNegotiation/001_register_legacy_app.lua

Update the expected syncMsgVersion to 4.5. [Related Core PR](https://github.com/smartdevicelink/sdl_core/pull/2519)

Update version to 4.5

---

test_scripts/Handling_VR_help_requests/025_SetGlobalProp_with_several_vrCommands_in_one_addCommand_request.lua
test_scripts/Handling_VR_help_requests/026_SetGlobalProp_with_several_vrCommands_in_one_addCommand_request_by_resumption.lua
test_scripts/Handling_VR_help_requests/031_SetGlobalProp_processing_30_commands_several_in_one_command.lua
test_scripts/Handling_VR_help_requests/032_SetGlobalProp_processing_30_commands_several_in_one_command_by_resumption.lua
test_scripts/Handling_VR_help_requests/033_SetGlobalProp_delete_last_command.lua
test_scripts/Handling_VR_help_requests/commonVRhelp.lua

ATF Test Scripts to check [#2539](https://github.com/smartdevicelink/sdl_core/issues/2539)
Update for existing scripts according to changes in initial version of proposal

Test scripts for Revise SDL-0122 to exclude synonyms

---

test_scripts/API/Expanded_proprietary_data_exchange/commonDataExchange.lua
test_scripts/API/SetAppIcon/009_Mobile_App_received_response_SetAppIcon_DISALLOWED.lua
test_scripts/API/SetAppIcon/commonIconResumed.lua
test_scripts/API/SubMenuIcon/commonSubMenuIcon.lua
test_scripts/MobileProjection/Phase1/001_Start_video_audio_service.lua
test_scripts/MobileProjection/Phase1/002_Start_video_streaming.lua
test_scripts/MobileProjection/Phase1/003_Start_audio_streaming.lua
test_scripts/MobileProjection/Phase1/004_OnTouchEvent_while_streamings.lua
test_scripts/MobileProjection/Phase1/005_Start_video_service_streaming_in_LIMITED.lua
test_scripts/MobileProjection/Phase1/006_Start_audio_service_streaming_in_LIMITED.lua
test_scripts/MobileProjection/Phase1/007_Rejecting_audio_video_service_in_NONE.lua
test_scripts/MobileProjection/Phase1/008_Rejecting_audio_video_service_in_BACKGROUND.lua
test_scripts/MobileProjection/Phase1/009_Rejecting_audio_video_service_in_FULL_2_protocol.lua
test_scripts/MobileProjection/Phase1/010_Rejecting_audio_video_service_in_LIMITED_2_protocol.lua
test_scripts/MobileProjection/Phase1/011_Retry_sequence_of_StartAudioStream_during_audio_service_start.lua
test_scripts/MobileProjection/Phase1/012_Retry_sequence_of_StartStream_during_video_service_start.lua
test_scripts/MobileProjection/Phase1/013_Rejecting_StartAudioStream_during_audio_service_start.lua
test_scripts/MobileProjection/Phase1/014_Rejecting_StartStream_during_video_service_start.lua
test_scripts/MobileProjection/Phase1/015_Restore_video_streaming_from_NONE.lua
test_scripts/MobileProjection/Phase1/016_Restore_audio_streaming_from_NONE.lua
test_scripts/MobileProjection/Phase1/017_HappyPath_flow_with_audio_video_streamings.lua
test_scripts/SDL4_6/TTSChunks/009_AlertManeuver.lua
test_scripts/iAP2TransportSwitch/003_resume_failed_remove_data_check.lua

Updates for ATF Test Scripts
Update for existing scripts due to changes introduced in [#2159](https://github.com/smartdevicelink/sdl_core/issues/2159)

Update scripts due to fullAppId changes 

---

test_scripts/Defects/5_0/2464_SDL_does_not_send_OnSDLClose_notification_by_switching_off_with_reason_IGNITION_OFF.lua

ATF Test Scripts to check [#2464](https://github.com/smartdevicelink/sdl_core/issues/2464)
A test script to verify that issue is fixed
- [x ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

Scripts to check issue 2464

---

test_scripts/Defects/4_6/842_App_does_not_activate_when_policies_are_disabled.lua

Verified:
App does not activate when policies are disabled
smartdevicelink/sdl_core#842

Verified issue smartdevicelink/sdl_core#842

---

test_scripts/Defects/5_0/1887_PoliciesManager_allows_all_requested_params_in_case_parameters_field_is_empty.lua

ATF Test Scripts to check [#1887](https://github.com/smartdevicelink/sdl_core/issues/1887)
A test script to verify that issue is fixed
- [x ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

Scripts to check issue 1887

---

test_scripts/Resumption/InteriorVehicleData/001_InteriorVD_resumption_OnHashChange_by_module_subscription.lua
test_scripts/Resumption/InteriorVehicleData/002_InteriorVD_resumption_absense_OnHashCnage_without_subscription.lua
test_scripts/Resumption/InteriorVehicleData/003_InteriorVD_resumption_one_module_unexpected_disconnect.lua
test_scripts/Resumption/InteriorVehicleData/004_InteriorVD_resumption_all_modules_unexpected_disconnect.lua
test_scripts/Resumption/InteriorVehicleData/005_InteriorVD_resumption_one_module_after_unsubscription_unexpected_disconnect.lua
test_scripts/Resumption/InteriorVehicleData/006_InteriorVD_resumption_one_module_after_unsubscription_IGNITION_OFF.lua
test_scripts/Resumption/InteriorVehicleData/007_InteriorVD_resumption_one_module_IGNITION_OFF.lua
test_scripts/Resumption/InteriorVehicleData/008_InteriorVD_resumption_all_modules_IGNITION_OFF.lua
test_scripts/Resumption/InteriorVehicleData/009_InteriroVD_resumption_2_apps_different_modules_unexpected_disconnect.lua
test_scripts/Resumption/InteriorVehicleData/010_InteriroVD_resumption_2_apps_different_modules_IGNITION_OFF.lua
test_scripts/Resumption/InteriorVehicleData/011_InteriroVD_resumption_2_apps_same_module_unexpected_disconnect.lua
test_scripts/Resumption/InteriorVehicleData/012_InteriroVD_resumption_2_apps_same_module_IGNITION_OFF.lua
test_scripts/Resumption/InteriorVehicleData/013_InteriroVD_resumption_2_apps_same_and_different_modules_unexpected_disconnect.lua
test_scripts/Resumption/InteriorVehicleData/014_InteriorVD_resumption_3rd_ignition_cycle.lua
test_scripts/Resumption/InteriorVehicleData/015_InteriorVD_resumption_4rd_ignition_cycle.lua
test_scripts/Resumption/InteriorVehicleData/016_InteriorVD_resumption_one_module_with_error_from_HMI.lua
test_scripts/Resumption/InteriorVehicleData/017_InteriorVD_resumption_all_modules_with_error_from_HMI.lua
test_scripts/Resumption/InteriorVehicleData/018_InteriroVD_resumption_2_apps_different_modules_error_to_one_app.lua
test_scripts/Resumption/InteriorVehicleData/019_InteriroVD_resumption_2_apps_same_module_error_to_one_app.lua
test_scripts/Resumption/InteriorVehicleData/020_InteriroVD_resumption_2_apps_same_module_error_with_delay_to_one_app.lua
test_scripts/Resumption/InteriorVehicleData/common_resumptionsInteriorVD.lua

Initial scripts for InteriorVehicleData resumption

Initial scripts for interiorVD resumption

---

test_scripts/Defects/5_0/2457_Needed_fixes_sending_of_UpdateDeviceList_notification_on_device_connect.lua

ATF Test Scripts to check [#2457](https://github.com/smartdevicelink/sdl_core/issues/2457)
Summary
A set of test scripts to verify that issue is fixed

Script for defect 2457

---

test_scripts/Defects/5_0/2447_Resumption_revoked_app_still_be_resumed_as_FULL.lua

ATF test scripts to check https://github.com/smartdevicelink/sdl_core/issues/2447.
Summary:
A set of test scripts to verify that issue is fixed.

Sript for reproduce defect 2447.

---

files/PTU_with_permissions_for_app_1234567.json
test_scripts/Policies/App_Permissions/003_ATF_HP_User_Consent_Yes.lua
test_scripts/Policies/App_Permissions/004_ATF_HP_User_Consent_NO.lua
test_scripts/Policies/appID_Management/031_ATF_Register_App_Interface_App_Unauthorized.lua
test_scripts/Policies/appID_Management/033_ATF_Register_App_Interface_Order_Of_Nickname_Validation.lua
test_scripts/Policies/user_consent_of_Policies/189_ATF_isAppPermissionsRevoked_true.lua

on fix/allow_user_consent_for_default_group branch of Core

Fix broken EXTERNAL_PROPRIETARY policy tests 

---

test_scripts/Defects/5_0/2480_Vefiry_that_SDL_sends_OnDD_notification_once_upon_registration.lua

Script for https://github.com/SmartDeviceLink/sdl_core/issues/2480

Vefiry that SDL sends OnDD notification once upon registration

---

test_scripts/RC/CLIMATE_RADIO/GetInteriorVehicleData/013_Presence_of_isSubscribed_parameter_in_case_request_from_Mob_app_without_subscribe_parameter_but_response_from_HMI_with_isSubscribed.lua
test_scripts/RC/SEAT/GetInteriorVehicleData/011_Presence_of_isSubscribed_parameter_in_case_request_from_Mob_app_without_subscribe_parameter_but_response_from_HMI_with_isSubscribed.lua

Fix panics resulting from copy-paste error

---

test_scripts/Defects/5_0/2670_2_GetInteriorVD_after_ignition_off.lua
test_scripts/Defects/5_0/2670_3_GetInteriorVD_after_ignition_off.lua
test_scripts/Defects/5_0/2670_4_GetInteriorVD_after_ignition_off.lua
test_scripts/Defects/5_0/2670_GetInteriorVD_after_ignition_off.lua

Script for reproducing https://github.com/smartdevicelink/sdl_core/issues/2670

Script for issue 2670

---

test_scripts/Defects/5_0/1898_Canceling_HMILevel_resumption_of_media_app_after_unexpectedDisconnect.lua

ATF Test Scripts to check #[1898](https://github.com/SmartDeviceLink/sdl_core/issues/1898)
Script for reproducing defect.

ATF test script for reproducing defect #1898

---

test_scripts/Defects/5_0/2446_SDL_doesn_t_resume_HMILevel_when_DEACTIVATE_HMI_with_isActive_is_true_then_false.lua

ATF Test Scripts to check [#2446](https://github.com/smartdevicelink/sdl_core/issues/2446)
Summary
A set of test scripts to verify that issue is fixed

Script for defect 2446

---

test_scripts/Defects/5_0/2443_SDL_does_not_check_for_non_manadatory_parameters.lua

ATF Test Scripts to check [#2443](https://github.com/smartdevicelink/sdl_core/issues/2443)
Summary
A set of test scripts to verify that issue is fixed

Script for Defect 2443

---

test_scripts/Defects/5_0/1905_Navigation_app_must_be_activated_during_active_embedded_navigation.lua

ATF Test Scripts to check [#1905](https://github.com/smartdevicelink/sdl_core/issues/1905)
A test script to verify that issue is fixed

Scripts to check issue 1905

---

test_sets/SDL5_0/mobile_projection_2.txt
test_sets/SDL5_0/mobile_projection_2_smoke.txt

Since issue [#2642](https://github.com/smartdevicelink/sdl_core/issues/2642) is closed related tests needs to be included in test sets

Include in scope tests related to issue 2642

---

test_scripts/Defects/5_0/2427_policy_db_consistency_after_ignition_cycle.lua

Script for reproducing issue [#2427](https://github.com/smartdevicelink/sdl_core/issues/2427)

Script for reproducing issue 2427

---

test_scripts/Smoke/API/021_Speak_PositiveCase_SUCCESS.lua
test_scripts/Smoke/API/041_Speak_Non_Media_PositiveCase_SUCCESS.lua

This is **draft** of the update.
Updated OnResetTimeout notification in smoke tests according to "Restructuring OnResetTimeout" feature
develop

Smoke scripts update according to restructuring OnResetTimeout

---

test_scripts/Defects/4_5/1880_DefaultAndRPCTimeoutGENERIC_ERROR.lua

Fix script for checking https://github.com/smartdevicelink/sdl_core/issues/1880
Fix PerformInteraction_timeout_VR_ONLY case

Fix PerformInteraction_timeout_VR_ONLY case

---

test_sets/policies_happy_paths_HTTP.txt

Add script on policies to test set with appropriate link to issue

Add 083 script on policies to test set with link to issue

---

test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/023_Success_flow_default_capabilities.lua

script for https://github.com/smartdevicelink/sdl_core/issues/2683

Script that verifies that the SDL processes default capabilities correctly

---

test_scripts/AppServices/GetFile/001_GetFile_Success.lua
test_scripts/AppServices/GetFile/002_GetFile_FileNotFound.lua
test_scripts/AppServices/GetFile/003_GetFile_Mobile_ASP.lua
test_scripts/AppServices/GetFile/004_GetFile_HMI_ASP.lua
test_scripts/AppServices/commonAppServices.lua

Test scripts to test the GetFile RPC
[feature/app_services branch](https://github.com/smartdevicelink/sdl_atf/tree/feature/app_services)

GetFile RPC ATF tests

---

test_scripts/AppServices/PublishAppService/003_Nav_success_flow.lua
test_scripts/AppServices/PublishAppService/004_Weather_success_flow.lua
test_scripts/AppServices/PublishAppService/005_Future_service_type_success_flow.lua
test_scripts/AppServices/PublishAppService/006_Mobile_disallowed_flow.lua
test_scripts/AppServices/commonAppServices.lua

- Add success cases for different service types
- Add disallowed failure cases
- Add HMI expectation for OnAppServiceData after publish request

Extended publish app service tests

---

test_scripts/AppServices/GetAppServiceData/005_M2M_Nav_success_flow.lua
test_scripts/AppServices/GetAppServiceData/006_M2M_Weather_success_flow.lua
test_scripts/AppServices/GetAppServiceData/007_M2M_Future_service_type_success_flow.lua
test_scripts/AppServices/OnAppServiceData/005_M2M_Nav_success_flow.lua
test_scripts/AppServices/OnAppServiceData/006_M2M_Weather_success_flow.lua
test_scripts/AppServices/OnAppServiceData/007_M2M_Future_service_type_success_flow.lua
test_scripts/AppServices/commonAppServices.lua

ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/issues/2806
Added success flow tests for all service types in GetAppServiceData and OnAppServiceData tests
`feature/app_services` branch
* Added success flow tests for all service types in GetAppServiceData and OnAppServiceData tests
- #2168

Extended GetAppServiceData and OnAppServiceData tests

---

test_scripts/AppServices/RPCPassThrough/001_SendLocation_Handled_Request.lua
test_scripts/AppServices/RPCPassThrough/002_SendLocation_Unsupported_Request.lua
test_scripts/AppServices/RPCPassThrough/003_SendLocation_Request_Timeout.lua
test_scripts/AppServices/RPCPassThrough/004_SendLocation_MultipleAS.lua
test_scripts/AppServices/commonAppServices.lua

Added tests for RPC pass through for RPC SendLocation.
[feature/app_services branch](https://github.com/smartdevicelink/sdl_atf/tree/feature/app_services)

RPC Pass Through ATF Tests

---

test_scripts/AppServices/GetAppServiceRecords/001_GetAppServiceRecords_MOBILE.lua
test_scripts/AppServices/GetAppServiceRecords/002_GetAppServiceRecords_HMI.lua
test_scripts/AppServices/GetAppServiceRecords/003_GetAppServiceRecords_Multiple.lua

Test scripts to test the GetAppServiceRecords RPC
[feature/app_services branch](https://github.com/smartdevicelink/sdl_atf/tree/feature/app_services)

GetAppServiceRecords RPC ATF Tests

---

test_scripts/CloudAppRPCs/001_CloupAppVehicleId_GetVehicleData.lua
test_scripts/CloudAppRPCs/002_CloudAppVehicleId_SubscribeVehicleData.lua
test_scripts/CloudAppRPCs/003_CloudAppVehicleId_UnsubscribeVehicleData.lua
test_scripts/CloudAppRPCs/004_CloudAppVehicleId_OnVehicleData.lua
test_scripts/CloudAppRPCs/005_SetCloudAppProperties_Success.lua
test_scripts/CloudAppRPCs/006_SetCloudAppProperties_InvalidParams.lua
test_scripts/CloudAppRPCs/007_SetCloudAppProperties_InitNewCloudApp.lua
test_scripts/CloudAppRPCs/008_GetCloudAppProperties_Success.lua
test_scripts/CloudAppRPCs/009_GetCloudAppProperties_DATA_NOT_AVAILABLE.lua
test_scripts/CloudAppRPCs/010_get_icon_url.lua
test_scripts/CloudAppRPCs/011_UpdateAppList_NewCloudApplication.lua
test_scripts/CloudAppRPCs/commonCloudAppRPCs.lua
test_sets/cloudApp_RPCs.txt

ATF Test Scripts to check #[issue number in sdl_core repository]
Added ATF test scripts to check new RPCs and RPC param implemented for Cloud Apps feature

Cloud App RPC tests

---

test_scripts/Defects/5_1/2862_SDL_sends_UnsubscribeWayPoint_request_to_HMI.lua

ATF Test Scripts to check #2862
Added ATF script to test the fix for issue #2862

ATF test for issue #2862

---

test_scripts/CloudAppRPCs/010_get_icon_url.lua
test_scripts/CloudAppRPCs/011_UpdateAppList_NewCloudApplication.lua
test_scripts/CloudAppRPCs/commonCloudAppRPCs.lua

Fixes #2181 
Fix merge issue with `commonCloudAppRPCs.lua` and adjust test expectations accordingly
`develop` branch
* Fix merge issue with `commonCloudAppRPCs.lua` and adjust test expectations accordingly

Fix merge issue with cloud app common file

---

test_scripts/Defects/5_1/2874_SDL_sends_system_request_with_correlationid_-1_and_INAVLID_DATA.lua

ATF Test Scripts to check [#2874](https://github.com/smartdevicelink/sdl_core/issues/2874)
Added ATF script to test the fix for issue [#2874](https://github.com/smartdevicelink/sdl_core/issues/2874)

ATF Test for issue 2874

---

test_scripts/AppServices/GetAppServiceData/014_M2M_Unknown_ServiceType.lua
test_scripts/AppServices/GetAppServiceData/015_M2H_Unknown_ServiceType.lua
test_scripts/AppServices/GetAppServiceData/016_H2M_Unknown_ServiceType.lua
test_scripts/AppServices/PerformAppServiceInteraction/014_M2M_Unknown_ServiceId.lua
test_scripts/AppServices/PerformAppServiceInteraction/015_M2H_Unknown_ServiceId.lua
test_scripts/AppServices/PerformAppServiceInteraction/016_H2M_Unknown_ServiceId.lua
test_sets/app_services.txt

GetAppServiceData unknown service type tests

---

test_scripts/AppServices/RPCPassThrough/005_SendLocation_Invalid_Permissions.lua
test_scripts/AppServices/RPCPassThrough/006_ButtonPress_Handled_Request.lua
test_scripts/AppServices/RPCPassThrough/007_ButtonPress_Invalid_Permissions.lua
test_sets/app_services.txt

RPC passthrough(with Missing permissions)ATF Tests for issue [#2877](https://github.com/smartdevicelink/sdl_core/issues/2877)

RPC PassThrough missing permission ATF tests

---

test_scripts/API/PutFile/001_PutFile_with_crc_singleFrame.lua
test_scripts/API/PutFile/002_PutFile_with_crc_MultiFrame.lua
test_scripts/API/PutFile/003_PutFile_without_crc.lua
test_scripts/API/PutFile/004_PutFile_chunks.lua
test_scripts/API/PutFile/005_PutFile_with_negative_crc_singleFrame.lua
test_scripts/API/PutFile/006_PutFile_with_negative_crc_multiFrame.lua
test_scripts/API/PutFile/007_PutFile_with_crc_more_than_maxvalue.lua
test_scripts/API/PutFile/008_PutFile_corrupted_data.lua
test_scripts/API/PutFile/commonPutFile.lua
test_sets/SDL5_0/expand_put_file.txt
test_sets/SDL5_0/sdl_5_0_test_suite.txt

ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/issues/2799
Modifies existing `PutFile` tests to include `BC.OnPutFile` expectations
`develop`
* Modifies existing `PutFile` tests to include `BC.OnPutFile` expectations

Add OnPutFile expectation to PutFile tests

---

test_scripts/API/SDL_Passenger_Mode/001_OnDD_PT_true.lua
test_scripts/API/SDL_Passenger_Mode/002_OnDD_PT_false.lua
test_scripts/API/SDL_Passenger_Mode/003_OnDD_PT_missing.lua
test_scripts/API/SDL_Passenger_Mode/004_OnDD_PTU_true.lua
test_scripts/API/SDL_Passenger_Mode/005_OnDD_PTU_false.lua
test_scripts/API/SDL_Passenger_Mode/006_OnDD_PTU_missing.lua
test_scripts/API/SDL_Passenger_Mode/007_OnDD_hmiLevel_NONE_to_FULL_DD_OFF.lua
test_scripts/API/SDL_Passenger_Mode/008_OnDD_hmiLevel_NONE_to_FULL_DD_ON.lua
test_scripts/API/SDL_Passenger_Mode/009_OnDD_PTU_several_apps.lua
test_scripts/API/SDL_Passenger_Mode/010_OnDD_PT_another_language_exists.lua
test_scripts/API/SDL_Passenger_Mode/011_OnDD_PT_another_language_not_exists.lua
test_scripts/API/SDL_Passenger_Mode/012_OnDD_PT_another_language_exists_ChangeRegistration.lua
test_scripts/API/SDL_Passenger_Mode/commonPassengerMode.lua
test_sets/sdl_passenger_mode.txt
user_modules/sequences/actions.lua

ATF Test Scripts to check #[2134](https://github.com/smartdevicelink/sdl_core/issues/2134)
Scripts for "SDL Passenger Mode" feature, updates due to changes in proposal introduced by https://github.com/smartdevicelink/sdl_evolution/pull/766

Feature/SDL passenger mode - Updates due to proposal revision

---

test_scripts/SDL5_0/Transfer_RPC_with_invalid_image/003_Alert.lua
test_scripts/Smoke/API/007_Alert_PositiveCase_SUCCESS.lua
test_scripts/Smoke/API/038_Alert_Non_Media_PositiveCase_SUCCESS.lua

ATF Test Scripts to check #2287
Add an icon parameter to the Alert RPC.
develop
* Custom icons available for use via alertIcon parameter on Alert RPC

add alertIcon parameter

---

test_scripts/Smoke/API/015_Show_PositiveCase_SUCCESS.lua

ATF Test Scripts to check [#2393](https://github.com/smartdevicelink/sdl_core/issues/2393)
Added `templateTitle` parameter to the Show RPC test

Add template title param to Show RPC Test

---

test_scripts/TheSameApp/RC/001_RC_modules_allocation_AUTO_ALLOW_same_app_2_devices.lua
test_scripts/TheSameApp/RC/002_RC_modules_reallocation_AUTO_ALLOW_same_app_2_devices.lua
test_scripts/TheSameApp/RC/003_RC_modules_allocation_AUTO_DENY_same_app_2_devices.lua
test_scripts/TheSameApp/RC/004_RC_modules_allocation_ASK_DRIVER_same_app_2_devices.lua
test_scripts/TheSameApp/RC/005_RC_modules_release_same_app_2_devices.lua
test_scripts/TheSameApp/Subscriptions/009_Two_apps_with_same_appName_DIFF_devices_send_subscribe_unsubscribe_on_GetInteriorVehicleData.lua
test_scripts/TheSameApp/commonTheSameApp.lua

Updates for ATF Test Scripts that checks RC related functionality that have been merged in scope of **[SDL 0204- Support running the same app from multiple devices at the same time feature](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2202 )** - 
And need to be updated in scope of **[SDL 0221-Remote Control - Allow Multiple Modules per Module Type feature](https://github.com/smartdevicelink/sdl_core/issues/2919)** 
**[these changes will be merged to [#2226](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2226)]**
Update existing scripts according multiple modules feature changes
https://github.com/smartdevicelink/sdl_atf/tree/develop

fixup! Update existing scripts according multiple modules feature changes

---

test_scripts/SDL5_0/Handling_VR_help_requests/003_SetGlobalProp_without_deleted_commands.lua

Fixed issue [#2248](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2248)
Improve stability of SameApp scripts
develop
One function is replaced by more appropriate one

Improve stability of Handling VR Help scripts

---

test_scripts/API/SDL_Passenger_Mode/012_OnDD_PT_another_language_exists_ChangeRegistration.lua

Fixed issue [#2239](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2239)
Improve stability of SDLPassengerMode scripts
develop
Introduced changes to improve stability

Improve stability of SDLPassengerMode scripts

---

test_scripts/CloudAppRPCs/010_get_icon_url.lua
test_scripts/CloudAppRPCs/011_UpdateAppList_NewCloudApplication.lua
test_scripts/CloudAppRPCs/commonCloudAppRPCs.lua

Fixed issue [#2235](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2235)
Improve stability of CloudApp scripts
develop
Introduced various changes to improve stability

Improve stability of CloudApp scripts

---

test_scripts/TheSameApp/Subscriptions/010_Two_apps_with_same_appName_DIFF_devices_perform_AudioPassThru.lua

Fixed issue [#2241](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2241)
Improve stability of SameApp scripts
develop
Decreased delay

Improve stability of SameApp scripts

---

test_scripts/AppServices/AppServiceActivation/003_two_apps_activate_success.lua
test_scripts/AppServices/commonAppServices.lua

Fixed issue [#2237](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2237)
Improve stability of AppServices scripts
develop
Introduced various changes to improve stability

Improve stability of AppServices scripts

---

test_scripts/RC/InteriorVehicleData_cache/038_OnInteriorVD_one_parameter.lua
test_scripts/RC/InteriorVehicleData_cache/040_GetInteriorVD_with_subscription_after_OnInteriorVD_2_apps_light.lua
test_sets/SDL5_0/rc_interior_vehicle_data_management.txt

ATF Test Scripts to check [#2988](https://github.com/smartdevicelink/sdl_core/issues/2988)
There are following updates:
- updated existing `038` script: added merging of expected data for `LIGHT` module
- added new `040` script to check SDL behavior in case of 2 apps (taken from issue)
develop

Correct scripts for LIGHT RC module

---

test_scripts/API/VehicleData/GenericNetworkSignalData/commonGenericNetSignalData.lua
test_scripts/API/VehicleData/GetVehicleData/001_Success_flow.lua
test_scripts/API/VehicleData/OnVehicleData/003_NotificationParameterDisallowedByPolicies_Ignored_flow.lua
test_scripts/API/VehicleData/commonVehicleData.lua

ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/pull/3040
`maximumChangeVelocity` was improperly defined in the HMI API, this fixes any incorrect usages included in existing tests
develop
* Fixes any incorrect usages of `maximumChangeVelocity` included in existing tests

Fix tests after changing definition of maximumChangeVelocity

---

test_scripts/AppServices/Resumption/001_Resumption_GetAppServiceData_Unexpected_Disconnect.lua
test_sets/app_services.txt

ATF Test Scripts to check #[3096](https://github.com/smartdevicelink/sdl_core/issues/3096)
Script for checking resumption date after unexpected disconnect
develop

Script for checking resumption date after unexpected disconnect

---

test_sets/smoke_tests.txt

Fix wrongly formatted test names from the smoke test set.

remove 2976 after some test names

---

test_scripts/Policies/Validation_of_PolicyTables/314_ATF_Check_count_of_user_selections.lua

ATF Test Scripts update due to changes introduced by the fix for https://github.com/smartdevicelink/sdl_core/issues/3130 and to check https://github.com/smartdevicelink/sdl_core/issues/3144
There is SDL functionality to reject registration of an app with `DUPLICATE_NAME` result code in case app's name is already exist.
Also SDL has to increment `count_of_rejections_duplicate_name` counter of `usage_and_error_counts` section in PT
Before the fix https://github.com/smartdevicelink/sdl_core/pull/3132 SDL created a record in PT in `usage_and_error_counts` section for the rejected app. 
However it seems this was incorrect behavior. Why do we need a record for the rejected app?
The idea is to increment counter only for the apps which already have a records in …

Update 314 policy script due to changes in core

---

test_scripts/CloudAppRPCs/012_Same_app_name_mobile_app_Disallowed.lua
test_scripts/CloudAppRPCs/013_Same_app_name_mobile_app_Unregistered.lua
test_sets/cloudApp_RPCs.txt

ATF Test Scripts to check [#3130](https://github.com/smartdevicelink/sdl_core/issues/3130)
New script to cover issue
develop
- added new test script 
- updated test set

Scripts for defect 3130

---

test_scripts/Defects/6_1/3139_01_Stop_streaming_gracefully_1st_timer.lua
test_scripts/Defects/6_1/3139_02_Stop_streaming_gracefully_2nd_timer.lua
test_scripts/Defects/6_1/3139_03_Stop_streaming_forcibly_app_continue_streaming.lua
test_scripts/Defects/6_1/3139_04_Stop_streaming_forcibly_app_does_not_send_EndServiceAck.lua
test_scripts/Defects/6_1/common_3139_3140_3142.lua
test_sets/Defects/6_1/3139.txt

ATF Test Scripts to check [#3139](https://github.com/smartdevicelink/sdl_core/issues/3139)
New scripts to cover issue
develop
- added new test scripts 
- updated related test sets

Script for defect 3139

---

test_scripts/Policies/build_options/110_ATF_PTU_Trigger_kilometers_PROPRIETARY.lua

ATF Test Scripts to check #[3239](https://github.com/SmartDeviceLink/sdl_core/issues/3239)
Expectations on `SDL.OnStatusUpdate` notification are updated due to changes introduced by HMI PTU feature
develop

Script update to verify 3239 issue

---

test_scripts/Defects/5_0/995_OnSystemrequest_query_apps_after_unsuccessful_attempt.lua
test_scripts/Defects/6_1/995_OnSystemrequest_query_apps_after_unsuccessful_attempt.lua
test_sets/Defects/6_1/995.txt

ATF Test Scripts to check #[995](https://github.com/smartdevicelink/sdl_core/issues/995)
ATF test script to verify the issue.
[develop](https://github.com/smartdevicelink/sdl_atf/commit/6ed5c5c7a55fa05b015de3db7c04e13b91ace01a)

Script for reproducing issue 995

---

test_scripts/Policies/Validation_of_PolicyTables/308_ATF_Check_app_registration_language_gui.lua

ATF Test Scripts to check #[3237](https://github.com/SmartDeviceLink/sdl_core/issues/3237)
Expectations on `SDL.OnStatusUpdate` notification are updated due to changes introduced by HMI PTU feature
develop

Script update to verify 3237 issue

---

test_scripts/Defects/6_1/3113_Deprecated_parameters_are_present_in_RAI_response.lua
test_sets/Defects/6_1/3113.txt

ATF Test Scripts to check [#3113](https://github.com/SmartDeviceLink/sdl_core/issues/3113)
New script is introduced to check the issue
develop

Script for issue 3113

---

test_scripts/Defects/6_1/2966_SDL_incorrectly_assigned_default_permissions.lua
test_sets/Defects/6_1/2966.txt

ATF Test Scripts to check #[2966](https://github.com/SmartDeviceLink/sdl_core/issues/2966)
The script is introduced to check the issue
develop

Script for 2966 issue

---

test_scripts/Defects/6_1/2990_PerfomInteraction_with_choiceID.lua
test_sets/Defects/6_1/2990.txt

ATF Test Scripts to check [#2990](https://github.com/SmartDeviceLink/sdl_core/issues/2990)
New script is introduced to check the issue
develop

Script for issue 2990

---

test_scripts/Defects/6_1/3267_1_RAI_OnSystemRequest_LOCK_SCREEN_ICON_URL.lua
test_scripts/Defects/6_1/3267_2_RAI_OnSystemRequest_LOCK_SCREEN_ICON_URL_app_specific.lua
test_sets/Defects/6_1/3267.txt

ATF Test Scripts to check [#3267](https://github.com/SmartDeviceLink/sdl_core/issues/3267)
New script is introduced to check the issue
develop

Scripts for 3267 issue

---

test_scripts/Defects/6_1/3278_Start_A-V_services_protected_at_the_same_time.lua
test_sets/Defects/6_1/3278.txt

ATF Test Scripts to check [#3278](https://github.com/SmartDeviceLink/sdl_core/issues/3278)
New script is introduced to check the issue
develop

Scripts for 3278 issue

---

test_scripts/Defects/6_1/3148_1_video_streaming.lua
test_scripts/Defects/6_1/3148_2_audio_streaming.lua
test_sets/Defects/6_1/3148.txt

ATF Test Scripts to check #[3148](https://github.com/smartdevicelink/sdl_core/issues/3148)
Scripts for checking the SDL behaviour described in issue
develop

Scripts for 3148 issue

---

test_scripts/API/VehicleData/GenericNetworkSignalData/commonGenericNetSignalData.lua
test_scripts/AppServices/Resumption/001_Resumption_GetAppServiceData_Unexpected_Disconnect.lua
test_scripts/RC/InteriorVehicleData_cache/common_interiorVDcache.lua
test_scripts/Resumption/HMI_Level/common.lua
test_scripts/SDL5_0/LowVoltage/common.lua
test_scripts/Smoke/commonSmoke.lua
test_scripts/TheSameApp/commonTheSameApp.lua
test_scripts/WidgetSupport/common.lua

Fixes #2370 
Improve stability of scripts with unexpected disconnect functions.
develop
- Added delay to unexpected disconnect functions

Add delay to unexpected disconnect functions

---

test_scripts/Policies/HMI_PTU/018_No_App_kilometers_trigger.lua
test_scripts/Policies/HMI_PTU/019_No_App_days_trigger.lua
test_scripts/Policies/HMI_PTU/020_No_App_ignition_cycles_trigger.lua
test_scripts/Policies/HMI_PTU/021_No_App_manual_trigger.lua
test_scripts/Policies/HMI_PTU/common_hmi_ptu.lua
test_scripts/Policies/Validation_of_PolicyTables/280_ATF_Reset_ignition_cycles_since_last_exchange_in_PT.lua
test_scripts/Policies/Validation_of_PolicyTables/308_ATF_Check_app_registration_language_gui.lua
test_scripts/Policies/user_consent_of_Policies/202_ATF_No_OnSDLConsentNeeded.lua
test_scripts/WebEngine/027_UpdateAppList_unregister_2apps.lua
test_sets/hmi_ptu.txt

ATF Test Scripts to check [#3279](https://github.com/SmartDeviceLink/sdl_core/issues/3279)
Updates in scripts related to the fix.
develop
- Corrected `3` existing policy scripts
- Added `4` new scripts in scope of `HMI PTU` feature
- Done minor improvements in `common` module of `HMI PTU` feature

Scripts for 3279 issue

---

test_sets/Defects/Defects.txt
test_sets/Defects/Defects_releases_4_x_and_5_x.txt

ATF Test Scripts to check [#2352](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2352)
Added test set for running of the scripts for issues from releases 4 and 5
develop

Test set for scripts from Defects folder

---

test_scripts/API/VehicleData/GenericNetworkSignalData/commonGenericNetSignalData.lua

This PR is **[not ready]** for review.
[Summary of PR changes]

Add StabilityControlsStatus

---

test_scripts/Defects/6_1/3302_BC_GetSystemInfo_once.lua
test_sets/Defects/6_1/3302.txt

ATF Test Scripts to check [#3302](https://github.com/smartdevicelink/sdl_core/issues/3302)
[New script is introduced to check the issue]
develop

Script for 3302 issue

---

test_scripts/Defects/4_5/1921_Invalid_PT_after_cutting_unknow_values.lua
test_scripts/Defects/4_5/commonDefects.lua
test_sets/Defects/Defects_releases_4_x_and_5_x.txt

ATF Test Scripts to fix #[2333](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2333)
Actualization of the script for 1921
develop

Actualization of the script for 1921

---

test_scripts/Defects/4_5/1206_REQUEST_PTU_Trigger_PTU_failed_previous_IGN_ON.lua
test_scripts/Defects/4_5/1211_ATF_Check_count_of_removals_for_bad_behavior_REQUEST_WHILE_IN_NONE_HMI_LEVEL.lua
test_scripts/Defects/4_5/1225_FACTORY_DEFAULTS.lua
test_scripts/Defects/4_5/1395_Resumption_data_IGN_OFF.lua
test_scripts/Defects/4_5/1873_UnsubscribeVD_OnVD_Parameters_empty_in_policy_table.lua
test_scripts/Defects/4_5/1880_DefaultAndRPCTimeoutGENERIC_ERROR.lua
test_scripts/Defects/4_5/1881_OnDriverDistraction_After_changing_HMIlevel_from_NONE.lua
test_scripts/Defects/4_5/1912_Video_service_start_via_2_protocol.lua
test_scripts/Defects/4_5/1921_Invalid_PT_after_cutting_unknow_values.lua
test_scripts/Defects/5_0/1031_SDL_transfer_OnKeyboardInput_notification_to_not_active_App_when_there_is_no_active_PerformInteraction_KEYBOARD.lua
test_scripts/Defects/5_0/1035_SDL_doesnt_send_REJECTED_code_to_mobile_app_when_activating_app_from_HMI_with_activate.lua
test_scripts/Defects/5_0/1218_Mandatory_parameter_spaceAvailable_is_not_provided_in_response_for_PutFile_request.lua
test_scripts/Defects/5_0/2405/001_omitted_omitted_SUCCESS.lua
test_scripts/Defects/5_0/2405/002_omitted_empty_SUCCESS.lua
test_scripts/Defects/5_0/2405/003_omitted_param_SUCCESS.lua
test_scripts/Defects/5_0/2405/004_empty_omitted_SUCCESS.lua
test_scripts/Defects/5_0/2405/005_empty_empty_USER_DISALLOWED.lua
test_scripts/Defects/5_0/2405/006_empty_param_SUCCESS_DISALLOWED.lua
test_scripts/Defects/5_0/2405/007_param_omitted_SUCCESS.lua
test_scripts/Defects/5_0/2405/008_param_empty_SUCCESS_DISALLOWED.lua
test_scripts/Defects/5_0/2405/009_param_param_SUCCESS.lua
test_scripts/Defects/5_0/2405/common.lua
test_scripts/Defects/5_0/964_SDL_sends_to_mobile_APPLICATION_NOT_REGISTRED_in_setAppIcon_responce_if_HMI_responds_with_INVALID_DATA.lua
test_scripts/Defects/5_1/2874_SDL_sends_system_request_with_correlationid_-1_and_INAVLID_DATA.lua
test_sets/Defects/Defects_releases_4_x_and_5_x.txt

ATF Test Scripts to fix #[2332](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2332)
Policy flow specification in scripts from Defects folder
develop
- #2335

Policy flow specification in scripts from Defects folder

---

test_scripts/Security/SSLHandshakeFlow/018_V5_happy_path_SUCCESS.lua

Fix check for BSON library in tests that use this library
https://github.com/smartdevicelink/sdl_atf/pull/192
* Fix check for BSON library in related tests

Fix bson library includes in project

---

test_scripts/Defects/5_0/2446_SDL_doesn_t_resume_HMILevel_when_DEACTIVATE_HMI_with_isActive_is_true_then_false.lua
test_scripts/Defects/5_0/2670_4_GetInteriorVD_after_ignition_off.lua
test_sets/Defects/Defects_releases_4_x_and_5_x.txt

ATF Test Scripts to fix #2376 
Updates in scripts related to the fix of [#3279](https://github.com/SmartDeviceLink/sdl_core/issues/3279)
develop

Fix scripts for defects according to 3279

---

test_scripts/Defects/6_1/3327_GetVehicleData_VEHICLE_DATA_NOT_AVAILABLE.lua
test_sets/Defects/6_1/3327.txt

ATF Test Scripts to check [#3327](https://github.com/smartdevicelink/sdl_core/issues/3327)
[New script is introduced to check the issue]
[develop]
* [Bug Fix Info]

Add script for 3327 issue

---

test_scripts/Defects/6_1/3321_OnAppPropertiesChange_remove_nickname.lua
test_sets/Defects/6_1/3321.txt

ATF Test Scripts to check [3321](https://github.com/smartdevicelink/sdl_core/issues/3321)
[Scripts to verify 3321 issue]
[develop]

Scripts for 3321 issue

---

test_scripts/Defects/4_5/1772_update_default_section.lua
test_sets/Defects/Defects_releases_4_x_and_5_x.txt

ATF Test Scripts to check #[1772](https://github.com/smartdevicelink/sdl_core/issues/1772)
PR to fix https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2314
Upadte script to verify 1772 issue
develop

Upadte script to verify 1772 issue

---

test_scripts/Defects/6_2/1398_RAI_duplicate_name.lua

ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/issues/1398
Add new test with cases where RAI should reply with DUPLICATE_NAME
latest
* add additional test

add test for issue 1398 RAI duplicate name

---

test_scripts/MobileProjection/Phase1/013_Rejecting_StartAudioStream_during_audio_service_start.lua
test_scripts/MobileProjection/Phase1/014_Rejecting_StartStream_during_video_service_start.lua

ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/pull/2553 and fix https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2406
Update number of start stream retries that should be expected.
Latest

update expectations to accomadate smartdevicelink/sdl_core#2553

---

test_scripts/Defects/6_2/1581_SubscribeVehicleData_Twice_Ignored.lua

ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/issues/1581
Add a new test for core issue 1581
latest

add test for core issue 1581

---

test_scripts/Defects/6_2/2461_UnsubscribeWaypoints_OnDisconnect.lua
test_scripts/Defects/6_2/3372_StaySubscribedWaypoints_OnOtherAppDisconnect.lua

ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/issues/2461 and https://github.com/smartdevicelink/sdl_core/issues/3372
add two scripts to test two different core issues
latest

add scripts for issues 2461 and 3372

---

test_scripts/TheSameApp/Security/commonSecurity.lua

Improve clean up of SDL certificates function.
https://github.com/smartdevicelink/sdl_atf/pull/201
- used set/clean functions from SDL module of ATF
- removed unnecessary modules

Fix clean up of SDL certificates

---

test_scripts/Policies/HMI_PTU/010_PTU_retry_sequence_HMI_has_timeout_more_then_SDL_propr.lua

ATF Test Scripts to check [#3393](https://github.com/smartdevicelink/sdl_core/issues/3393)
Update script according to fixed issue 
develop
- Added sending of `BC.OnSystemRequest` from HMI and increased number of expected `OnSystemRequest` messages to mobile app

Update script according to changes in #3393 issue

---

test_scripts/CloudAppRPCs/006_SetCloudAppProperties_InvalidParams.lua
test_scripts/Policies/External_UCS/Informing_HMI/021_ATF_N_GetListofPermissions_empty_due_to_invalid_param_status_OnAppPermissionChange.lua
test_scripts/RC/MultipleModules/commonRCMulModules.lua
test_scripts/UnknownEnums/001_unknown_mandatory_param.lua
test_scripts/UnknownEnums/002_unknown_nonmandatory_param.lua
test_scripts/UnknownEnums/003_single_unknown_enum_in_array.lua
test_scripts/UnknownEnums/004_multiple_unknown_enums_in_array.lua
test_scripts/UnknownEnums/005_unknown_enum_in_struct.lua
test_scripts/UnknownEnums/006_unkown_enum_in_array_of_structs.lua
test_scripts/UnknownEnums/007_multiple_unknown_enums_in_array_of_structs.lua
test_scripts/WebEngine/007_SetAppProperties_with_invalid_parameters.lua
test_sets/unknown_enums.txt

ATF Test Scripts to check #[issue number in sdl_core repository]
Test scripts for testing SDL Core [#3385](https://github.com/smartdevicelink/sdl_core/pull/3385)
Develop

Add test scripts for unknown enum cases

---

test_scripts/API/ServiceStatusUpdateToHMI/020_Video_service_protected_PTU_FAILED_TimeOut_2_failed_external.lua
test_scripts/API/ServiceStatusUpdateToHMI/021_Video_service_protected_PTU_FAILED_TimeOut_failed_success_failed_external.lua
test_scripts/API/ServiceStatusUpdateToHMI/022_Video_service_protected_PTU_FAILED_TimeOut_failed_success_2rd_try_failed_external.lua
test_scripts/API/ServiceStatusUpdateToHMI/023_Video_service_protected_PTU_FAILED_TimeOut_unprotected.lua
test_scripts/Defects/6_1/3136_02_External_Proprietary.lua
test_scripts/Defects/6_1/3136_05_External_Proprietary_3apps.lua
test_scripts/Policies/HMI_PTU/014_Successful_PTU_after_failed_retry_consequtive_trigger_ext.lua
test_scripts/Policies/HMI_PTU/016_Successful_PTU_after_failed_retry_parallel_trigger_ext.lua

Fixes off by one error in PTU retry test.
Correct delay index is used and the correct number of OnSystemRequests are sent.
Develop

Fix external off by one PTU retry error

---

test_scripts/API/VehicleData/GenericNetworkSignalData/032_Subscription_resumption_for_VDitems_2_apps_unexpected_disconnect.lua
test_scripts/API/VehicleData/GenericNetworkSignalData/033_Subscription_resumption_for_VDitems_2_apps_ign_off.lua

ATF Test Scripts to check #2385 
Change incorrect subscription item in hmiRequestDataApp2 from gps to rpm according to requirements.
develop (496be121cf530c6b87d5e54d9b8acb5139fd5d5b)

Actualization of the scripts 032 and 033 from API/VehicleData/GenericNetworkSignalData

---

test_scripts/API/CancelInteraction/008_SendCancelInteraction_SubtleAlert_HMIReceivesRequest.lua
test_scripts/API/SubtleAlertStyle/OnSubtleAlertPressed/001_PositiveCase_Subtle_Alert_Pressed.lua
test_scripts/API/SubtleAlertStyle/SubtleAlert/001_PositiveCase_With_SoftButtons_SUCCESS.lua
test_scripts/API/SubtleAlertStyle/SubtleAlert/002_PositiveCase_Without_SoftButtons_SUCCESS.lua
test_scripts/API/SubtleAlertStyle/SubtleAlert/003_PositiveCase_UI_Only_SUCCESS.lua
test_scripts/API/SubtleAlertStyle/SubtleAlert/004_PositiveCase_TTS_Interrupted_SUCCESS.lua
test_scripts/API/SubtleAlertStyle/SubtleAlert/005_PositiveCase_TwoApps_DEFAULT_ACTION_SUCCESS.lua
test_scripts/API/SubtleAlertStyle/SubtleAlert/006_PositiveCase_TwoApps_STEAL_FOCUS_SUCCESS.lua
test_scripts/API/SubtleAlertStyle/SubtleAlert/007_Interrupted_By_VR_ABORTED.lua
test_scripts/API/SubtleAlertStyle/SubtleAlert/008_Phone_Call_Active_REJECTED.lua
test_scripts/API/SubtleAlertStyle/commonSubtleAlert.lua
test_scripts/Smoke/commonSmoke.lua
test_sets/cancel_interation.txt
test_sets/smoke_tests.txt
test_sets/subtle_alert_style.txt

ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/pull/3459
Add test cases for SubtleAlert and OnSubtleAlertPressed RPCs
Develop

Subtle Alert Style tests

---

test_scripts/Defects/7_0/3511_Usage_of_bitsPerSample_from_HMI_capabilities_cache.lua
test_sets/Defects/Defects_release_7_0.txt

ATF Test Scripts to check [#3511](https://github.com/smartdevicelink/sdl_core/issues/3511)
New script to verify the issue.
develop

Add script to check #3511 issue

---

test_sets/Defects/Defects_release_7_0.txt

Add scripts for issue `2888` into test set
develop
- Updated `Defects_release_7_0.txt` test set with the links to scripts for issue `2888`

Add scripts for issue 2888 into test set

---

test_scripts/Defects/7_0/3517_GetIVD_various_successful_result_codes_HMI_response.lua
test_sets/Defects/Defects_release_7_0.txt

ATF Test Scripts to check [#3517](https://github.com/smartdevicelink/sdl_core/issues/3517)
New script to verify the issue.
develop

Add script to check #3517 issue

---

test_scripts/Defects/7_0/3527_SubtleAlert_2_apps_no_change_of_HMI_level.lua
test_sets/Defects/Defects_release_7_0.txt

ATF Test Scripts to check [#3527](https://github.com/smartdevicelink/sdl_core/issues/3527)
Add test scripts to check the 3527 issue.
develop

Add script to check #3527 issue

---

test_scripts/Defects/7_0/3532_OnSCU_after_Show_main_IGN_OFF_ON_Cycle.lua
test_scripts/Defects/7_0/3532_OnSCU_after_Show_widget_IGN_OFF_ON_Cycle.lua
test_sets/Defects/Defects_release_7_0.txt

ATF Test Scripts to check [3532](https://github.com/smartdevicelink/sdl_core/issues/3532)
Add test scripts to check the 3532 issue.
develop
Add test scripts to check the 3532 issue.

Add test scripts to check 3532 issue

---

test_scripts/Defects/7_0/3542_apps_activation_after_resumption.lua
test_sets/Defects/Defects_release_7_0.txt

ATF Test Scripts to check [#3542](https://github.com/smartdevicelink/sdl_core/issues/3542)
Add test scripts to check the 3542 issue.
develop

Add script to check #3542 issue

---

test_scripts/Defects/7_0/3547_1_RetryStrategy_for_start_streaming_Audio_HMI_last_SUCCESS.lua
test_scripts/Defects/7_0/3547_2_RetryStrategy_for_start_streaming_Video_HMI_last_SUCCESS.lua
test_scripts/Defects/7_0/3547_3_RetryStrategy_for_start_streaming_Audio_HMI_all_REJECTED.lua
test_scripts/Defects/7_0/3547_4_RetryStrategy_for_start_streaming_Video_HMI_all_REJECTED.lua
test_scripts/Defects/7_0/3547_5_RetryStrategy_for_start_streaming_Audio_HMI_no_response.lua
test_scripts/Defects/7_0/3547_6_RetryStrategy_for_start_streaming_Video_HMI_no_response.lua
test_scripts/Defects/7_0/common_3547.lua
test_scripts/MobileProjection/Phase1/013_Rejecting_StartAudioStream_during_audio_service_start.lua
test_scripts/MobileProjection/Phase1/014_Rejecting_StartStream_during_video_service_start.lua
test_sets/Defects/Defects_release_7_0.txt

ATF Test Scripts to check [#3547](https://github.com/smartdevicelink/sdl_core/issues/3547)
Add test scripts to check the 3547 issue.
develop
Script needs to be run 10-20 times.

Add script to check #3547 issue

---

test_scripts/CloudAppRPCs/012_Same_app_name_mobile_app_Disallowed.lua
test_scripts/CloudAppRPCs/013_Same_app_name_mobile_app_Unregistered.lua
test_scripts/Defects/7_0/3549_Register_App_and_Activate.lua
test_sets/Defects/Defects_release_7_0.txt

ATF Test Scripts to check [#3549](https://github.com/smartdevicelink/sdl_core/issues/3549)
Add test scripts to check the 3549 issue.
develop
Script needs to be run 10-20 times.

Add script to check #3549 issue

---

test_sets/Defects/Defects_releases_4_x_and_5_x.txt

Fix for https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2374
Fix for the issue
develop
- Script is enabled in test set since issue is not reproduced at 7.0

Enable script for 1893 issue

---

test_scripts/Smoke/HeartBeat/001_HeartBeat_App_does_not_send_HB_and_does_not_respond.lua
test_sets/Defects/Defects_releases_4_x_and_5_x.txt

ATF Test Scripts to check [#1892](https://github.com/smartdevicelink/sdl_core/issues/1892)
Updates in scripts to reflect changes in core
develop
- Updated existing smoke test related to HB functionality
- Enabled script specific to the issue in `Defects_releases_4_x_and_5_x.txt` test set

Update scripts to verify #1892 issue

---

test_scripts/API/VehicleData/OnVehicleData/003_OnVD_disallowed_after_PTU.lua
test_sets/vehicle_data.txt

ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/pull/3568
Uncomment previously failing OnVehicleData tests and fix precondition in `003_OnVD_disallowed_after_PTU.lua`
master (7.0.0)
* Uncomment previously failing OnVehicleData tests and fix precondition in `003_OnVD_disallowed_after_PTU.lua`

Uncomment OnVehicleData tests after fix

---

test_scripts/Policies/user_consent_of_Policies/215_ATF_User_clears_all_applications.lua

test 215 was failing because the second device was not connecting, I updated this test to use the new shared libraries

update 215 test to new shared libraries

---

test_scripts/API/System/OnSystemRequest/001_OnSystemRequest_send_binaryData_for_any_requestType.lua
test_scripts/API/System/commonSystem.lua

ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/issues/1714
fix missing include in common file and add policy check as test only applies to regular policy mode
latest
-  [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

test only applies to regular policy mode, fix missing include

---

test_scripts/Defects/7_1/1583_PerformInteraction_UNSUPPORTED_and_ABORTED_response_success.lua
test_scripts/Defects/7_1/1596_1_VRPerformInteraction_UNSUPPORTED_RESOURCE_success.lua
test_scripts/Defects/7_1/1596_2_UIPerformInteraction_UNSUPPORTED_RESOURCE_success.lua
test_scripts/Defects/7_1/1597_1_Alert_Unsupported_Speech_Type.lua
test_scripts/Defects/7_1/1597_2_SubtleAlert_Unsupported_Speech_Type.lua
test_scripts/Defects/7_1/1597_3_AlertManeuver_Unsupported_Speech_Type.lua
test_scripts/Defects/7_1/1597_4_PerformAudioPassThru_Unsupported_Speech_Type.lua
test_sets/Defects/Defects_release_7_1.txt

ATF Test Scripts to check #1583, #1596, and #1597
ATF Test Scripts to check #1583, #1596, and #1597
develop
* ATF Test Scripts to check #1583, #1596, and #1597

Add tests for defects 1583, 1596, and 1597

---

test_scripts/Defects/7_1/3580_Revoked_app_activated_via_device_consent.lua

ATF Test Scripts to check #[3580](https://github.com/smartdevicelink/sdl_core/issues/3580)
[Summary of PR changes]
develop

Add script to verify issue 3580

---

test_scripts/Smoke/API/048_GetSystemCapabilityRequest_SUCCESS.lua
user_modules/hmi_values.lua

ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/pull/3437
Add preferredFPS to existing tests
develop
* Add preferredFPS to existing tests

Add preferredFPS capability to existing tests

---

test_scripts/API/Additional_Submenus/006_duplicate_name_same_level.lua
test_scripts/API/SameMenuName/001_AddCommand.lua
test_scripts/API/SameMenuName/001_MenuName.lua
test_scripts/API/SameMenuName/002_CreateInteractionChoiceSet.lua
test_sets/additional_submenus_and_driver_distraction.txt
test_sets/smoke_tests.txt

ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/issues/2346
add tests for add command and CICS with duplicate menuNames

[SDL 0180] Broaden Choice Uniqueness

---

test_scripts/Smoke/API/003_AddCommand_PositiveCase_SUCCESS.lua
test_scripts/Smoke/API/005_AddSubMenu_PositiveCase_SUCCESS.lua

Tests [Core issue 3195](https://github.com/smartdevicelink/sdl_core/issues/3195)
This PR is **Ready** for review.
Expand add command and add submenu smoke tests to include new parameters
Develop

Update tests for main menu ui updates

---

test_scripts/Defects/7_1/3640_PTU_all_flows_Protected_Mode_v3.lua
test_sets/Defects/Defects_release_7_1.txt

ATF Test Scripts to check [#3640](https://github.com/SmartDeviceLink/sdl_core/issues/3640)
develop
- New scripts
- New test set for the issues in scope of `7.1` release

Add script(s) for issue 3640

---

test_scripts/Defects/7_1/3659_OnSystemRequest_1st_frame_non-encrypted.lua
test_sets/Defects/Defects_release_7_1.txt

ATF Test Scripts to check [#3659](https://github.com/SmartDeviceLink/sdl_core/issues/3659)
develop
- New scripts
- New test set for the issues in scope of `7.1` release

Add script(s) for issue 3659

---

test_scripts/Defects/7_1/3667_Revert_RC_SetGlobalProperties_on_failed_resumption.lua
test_sets/Defects/Defects_release_7_1.txt

ATF Test Scripts to check #[3667](https://github.com/smartdevicelink/sdl_core/issues/3667)
https://github.com/smartdevicelink/sdl_atf/commit/63d4f5f18b2efea1cdb99a907857aa14eb0f776b

Add script to verify issue 3667

---

test_scripts/Defects/5_0/2447_Resumption_revoked_app_still_be_resumed_as_FULL.lua
test_sets/Defects/Defects_releases_4_x_and_5_x.txt

Enable script for issue
develop
- Updated test set
- Added policy restrictions to test script

Enable script for 2447 issue

---

test_scripts/Policies/HMI_PTU/022_No_App_connected_days_trigger.lua
test_scripts/Policies/HMI_PTU/023_No_App_connected_ignition_cycles_trigger.lua
test_scripts/Policies/HMI_PTU/common_hmi_ptu.lua
test_sets/hmi_ptu.txt

ATF Test Scripts to check [#3648](https://github.com/smartdevicelink/sdl_core/issues/3648)
develop
- New scripts

Add scripts for issue 3648

---

test_sets/Defects/Defects_releases_4_x_and_5_x.txt

ATF Test Scripts to check #[3285](https://github.com/smartdevicelink/sdl_core/issues/3285)
Script is introduced to check the issue
develop

Enable script for 3285 issue

---

test_scripts/Defects/7_1/1896_SDL_does_not_send_HeartBeat_request_to_Mobile_HeartBeatTimeout_is_Zero.lua
test_sets/Defects/Defects_release_7_1.txt

ATF Test Scripts to check [#1896](https://github.com/SmartDeviceLink/sdl_core/issues/1896) 
New ATF script to check the issue.
develop
Added new scripts
Updated test set for 7.1 release with new scripts

Add test script for issue 1896

---

test_scripts/API/VehicleData/GenericNetworkSignalData/005_RPC_DISALLOWED_custom_parameter_is_not_allowed.lua
test_scripts/API/VehicleData/GenericNetworkSignalData/006_RPC_DISALLOWED_custom_parameter_is_not_allowed_user_consent.lua
test_scripts/Defects/7_2/2398_SendLocation_with_one_OR_more_allowed_params_and_one_OR_more_disallowed_params_by_user.lua
test_scripts/Policies/App_Permissions/014_ATF_Unsubscribe_Vehicle_Data_General_Resultcode_And_The_Individual_Result_Codes_For_A_Part_Of_Parameters_Disallowed_By_Policies.lua
test_scripts/Policies/App_Permissions/018_ATF_Get_Vehicle_Data_App_Sends_Allowed_Parameters_And_Not-allowed_By_Policies_Parameters.lua
test_sets/Defects/Defects_release_7_2.txt

ATF Test Scripts to check [#2398](https://github.com/smartdevicelink/sdl_core/issues/2398)
develop
- Fixed issue in existing scripts (`data.params` => `data.payload`)
- Corrected expectation in existing scripts
- Added new script
- Updated test set for the issues in scope of `7.2` release

Add script(s) for issue 2398

---

user_modules/shared_testcases/testCasesForPolicyTableSnapshot.lua

ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/pull/1537
include PTS usage_and_error_counts fields in all policy modes

include PTS usage_and_error_counts fields in all policy modes

---

test_scripts/API/Additional_Submenus/003_delete_nested_submenu_with_nested_submenu_and_commands.lua
test_scripts/API/Additional_Submenus/004_delete_top_level_submenu_with_nested_submenus_and_commands.lua
test_scripts/API/Additional_Submenus/additional_submenus_common.lua

ATF Test Scripts to check [#3747](https://github.com/smartdevicelink/sdl_core/issues/3747)
Update ATF scripts according to the fix for issue.
develop
- Changed expected order of deleted items
- Removed not required function `reverseArray()`

Update script(s) for issue 3747

---

test_scripts/Defects/8_0/3717_SDL_ignores_frame_info_for_Single_and_First_frames.lua
test_sets/Defects/Defects_release_8_0.txt

ATF Test Scripts to check [#3717](https://github.com/smartdevicelink/sdl_core/issues/3717)
develop
- New script

Add script(s) for issue 3717

---

test_scripts/Defects/8_0/3768_activate_media_app_via_vr.lua
test_scripts/SDL5_0/MobileVersioning/vrCommandOptional/003_perform_interaction_success_legacy_app.lua
test_scripts/SDL5_0/Transfer_RPC_with_invalid_image/005_PerfomInteraction.lua
test_scripts/Smoke/API/012_PerfomInteraction_PositiveCase_SUCCESS.lua
test_scripts/Smoke/API/031_PerformAudioPassThru_PositiveCase_SUCCESS.lua
test_scripts/TheSameApp/Subscriptions/010_Two_apps_with_same_appName_DIFF_devices_perform_AudioPassThru.lua
test_scripts/WidgetSupport/OnHMIStatus/007_SystemContext_from_MAIN_to_VRSESSION_and_HMI_OBSCURED_for_the_main_and_a_widget_windows.lua
test_sets/Defects/Defects_release_8_0.txt

ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/issues/3768

add test for core issue 3768

---

test_scripts/Defects/8_0/2206_Icon_Folder_Minimum_Size.lua
test_sets/Defects/Defects_release_8_0.txt

ATF Test Scripts to check #2206
Add a new script to check a fixed issue in core

add tests to validate core issue 2206

---

test_scripts/Defects/8_0/2957_Consent_func_group.lua
test_sets/Defects/Defects_release_8_0.txt
user_modules/utils.lua

ATF Test Scripts to check [#2957](https://github.com/smartdevicelink/sdl_core/issues/2957)
New ATF script to check the issue
develop
- Added new script and updated test set
- Updated `spairs` function in `utils` module in order to have numerical comparison of values in case they are numbers

Add script(s) for issue 2957

---

test_scripts/Defects/8_1/3800_Send_GetSystemCapability_during_OnSystemCapabilityUpdated.lua
test_sets/Defects/Defects_release_8_1.txt

ATF Test Scripts to check [#3800](https://github.com/smartdevicelink/sdl_core/issues/3800)
Adds script to test fix for [#3800](https://github.com/smartdevicelink/sdl_core/issues/3800)
develop
* Adds script to test fix for [#3800](https://github.com/smartdevicelink/sdl_core/issues/3800)

Add script(s) for issue 3800

---

test_scripts/Defects/8_1/3800_Send_GetSystemCapability_during_OnSystemCapabilityUpdated.lua

Addendum to #2607 
Fix description for `3800_Send_GetSystemCapability_during_OnSystemCapabilityUpdated.lua`
* Fixed description for `3800_Send_GetSystemCapability_during_OnSystemCapabilityUpdated.lua`

Update description for #3800 defect script

---

test_scripts/Defects/8_0/3783_crash_during_vr_langchange.lua
test_scripts/Defects/8_0/3797_3798_HMI_sends_SetAppProperties_and_tries_to_ActivateApp.lua
test_sets/Defects/Defects_release_8_0.txt

ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/issues/3783
Add test for issue 3783
In my testing this fails about 1-2% against the 7.0 release

add test for 3783 issue

---

test_scripts/Resumption/Handling_errors_from_HMI/007_resume_all_data_with_one_error_rpc_2apps_unexpected_disconnect.lua
test_scripts/Resumption/Handling_errors_from_HMI/008_resume_all_data_with_one_error_rpc_2apps_ign_off.lua
test_scripts/Resumption/Handling_errors_from_HMI/019_resume_all_data_without_response_to_one_rpc_2apps_unexpected_disconnect.lua
test_scripts/Resumption/Handling_errors_from_HMI/020_resume_all_data_without_response_to_one_rpc_2apps_ign_off.lua
test_scripts/Resumption/Handling_errors_from_HMI/commonResumptionErrorHandling.lua

Extending existing ATF Test Scripts to check [#3802](https://github.com/smartdevicelink/sdl_core/issues/3802)
Updates for existing scripts to cover cases in issue.
develop
- Extend scripts for `ResumptionErrorHandling` for `RC.SetGlobalProperties` request

Update script(s) for issue 3802

---

test_scripts/Defects/8_0/3674_2_HMI_starts_PTU_before_UpdateAppList.lua

Fix is related to [#3822](https://github.com/smartdevicelink/sdl_core/issues/3822)
It was found out [3674_2_HMI_starts_PTU_before_UpdateAppList.lua](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Defects/8_0/3674_2_HMI_starts_PTU_before_UpdateAppList.lua) script sometimes may fail due to missing `SDL.OnStatusUpdate` notifications. This could happen only for `HTTP` policy flow.
The reason of that was the fact that sometimes `SystemRequest` is sent from App before `OnSystemRequest` has been received from Core.
develop
- Added expectation on `OnSystemRequest` and followed sending of `SystemRequest`
- Clean up the code by deleting of not used function parameters

Make script stable for issue 3674

---

test_scripts/Defects/7_1/885_ShowConstantTBT.lua
test_scripts/Defects/7_1/885_UpdateTurnList.lua

ATF Test Scripts to check [#3829](https://github.com/smartdevicelink/sdl_core/issues/3829)
Update test scripts for issue 3829
develop
Update test scripts

Update test scripts for issue 3829

---

files/jsons/JSON_Language_parameter/JSONWithTtsNameVrSynonymsInSeparatedStructs.json
test_scripts/Defects/8_1/994_SDL_sends_appName_in_vrSynonyms_and_ttsName_in_case_of_separated_structure_in_json_file.lua
test_sets/Defects/Defects_release_8_1.txt

ATF Test Scripts to check [#994](https://github.com/smartdevicelink/sdl_core/issues/994)
develop
New scripts

Add script(s) for issue 944

---

test_scripts/Defects/8_1/3832_HMI_PTU_after_Ignition_cycle.lua
test_sets/Defects/Defects_release_8_1.txt

ATF Test Scripts to check [#3832](https://github.com/smartdevicelink/sdl_core/issues/3832)
develop
New scripts

Add script(s) for issue 3832

---

test_scripts/API/SDL_Passenger_Mode/007_OnDD_hmiLevel_NONE_to_FULL_DD_OFF.lua
test_scripts/API/SDL_Passenger_Mode/009_OnDD_PTU_several_apps.lua
test_scripts/API/SDL_Passenger_Mode/commonPassengerMode.lua

ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/issues/3841
Updated expectations after changes in https://github.com/smartdevicelink/sdl_core/pull/3842
develop
* Updates expectations after changes in https://github.com/smartdevicelink/sdl_core/pull/3842

Update expectations to include lock screen dismissal info during DD_OFF notification

---

test_scripts/Defects/8_1/1883_1_PerformInteraction_REJECTED_for_being_deleted_InteractionChoceSet.lua
test_scripts/Defects/8_1/1883_2_PerformInteraction_REJECTED_for_being_deleted_InteractionChoceSet_after_resumption.lua
test_sets/Defects/Defects_release_8_1.txt

ATF Test Scripts to check [#1883](https://github.com/smartdevicelink/sdl_core/issues/1883)
New ATF script to check the issue
develop
Added new script and updated test set

Add script(s) for issue 1883

---

test_scripts/SDL5_0/TemplateColorSchemes/001_TemplateColorSchemes_setDisplayWithColorsAndNewLayoutSuccess.lua
test_scripts/SDL5_0/TemplateColorSchemes/002_TemplateColorSchemes_setDisplayWithColorsRejected.lua
test_scripts/SDL5_0/TemplateColorSchemes/003_TemplateColorSchemes_setDisplayWithSameColorsSuccess.lua
test_scripts/Smoke/API/020_SetDisplayLayout_PositiveCase_SUCCESS.lua
test_scripts/WidgetSupport/Templates/SetDisplayLayout/001_SetDisplayLayout_2_requests.lua
test_scripts/WidgetSupport/Templates/SetDisplayLayout/002_SetDisplayLayout_RAI_and_request.lua
test_scripts/WidgetSupport/Templates/SetDisplayLayout/003_SetDisplayLayout_unsuccessful_HMI_response.lua
test_scripts/WidgetSupport/Versioning/002_SetDisplayLayout_new_app.lua
test_scripts/WidgetSupport/Versioning/004_SetDisplayLayout_old_app.lua

Update test Scripts to check [#3706](https://github.com/smartdevicelink/sdl_core/issues/3706)
Update SetDisplayLayout test scripts to use UI.Show
develop (https://github.com/smartdevicelink/sdl_atf/commit/03648399bc87b464e8b143952c9eabef394cda86)

[SDL 0334] Update SetDisplayLayout scripts to use UI.Show

---

README.md

Fixes #2629
Updates README with instructions for new config variables.
develop

Fix/Update README for ATF changes made in 243

---

test_scripts/Defects/5_1/1393_ListFiles_from_enumerating_through_the_file_system.lua
test_sets/Defects/Defects_releases_4_x_and_5_x.txt

ATF Test Scripts to check [#1393](https://github.com/smartdevicelink/sdl_core/issues/1393)
develop
New scripts

Add script(s) for issue 1393

---

test_scripts/Defects/7_1/1585_AlertManeuver_UNSUPPORTED_RESOURCE_response_success.lua
test_sets/Defects/Defects_release_7_1.txt

ATF Test Scripts to check [#1585](https://github.com/smartdevicelink/sdl_core/issues/1585)
develop
New script

Add script(s) for issue 1585

---

test_scripts/Defects/8_1/980_SDL_responds_INVALID_DATA_in_case_soft_button_has_Type_Image_or_Both_and_Text_has_specific_string.lua
test_sets/Defects/Defects_release_8_1.txt

ATF Test Scripts to check #[980](https://github.com/smartdevicelink/sdl_core/issues/980)
New ATF scripts to check the 980 issue.
develop
Add script for issue 980
Update test sets

Add scripts for issues/980

---

test_scripts/Defects/8_1/3880_1_PTU_Empty_endpoint_properties.lua
test_scripts/Defects/8_1/3880_2_PTU_Omitted_endpoint_properties.lua
test_sets/Defects/Defects_release_8_1.txt

ATF Test Scripts to check [#3880](https://github.com/smartdevicelink/sdl_core/pull/3880)
develop https://github.com/smartdevicelink/sdl_atf/commit/d6ba479cac6af6a50d6e17e0e97e18a7cd4d09c7

Add scripts to verify defect 3880

---

test_scripts/Policies/build_options/078_ATF_PTU_HMI_Level_Affected_Apps_FULL_LIMITED_HTTP.lua

ATF Test Scripts to check [#2646](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2646)
Improve stability 'PTU in scripts /test_scripts/Policies/build_options/078_ATF_PTU_HMI_Level_Affected_Apps_FULL_LIMITED_HTTP.lua
latest
update test for randomly select the application

Update test script for script issue in 078_ATF_PTU_HMI_Level

---

test_sets/policies_all_flows.txt
test_sets/policies_happy_paths_HTTP.txt

Add test scripts created with the submission of 0337 to the appropriate test sets.
latest
* Ensure scripts are part of test set

add 0337 test scripts to test set

---

test_scripts/Defects/8_0/2810_1_unexpected_disconnect_during_audio_streaming.lua
test_scripts/Defects/8_0/2810_2_unexpected_disconnect_during_video_streaming.lua
test_scripts/Defects/8_0/2810_3_unexpected_disconnect_during_video_and_audio_streaming.lua
test_scripts/Defects/8_0/3479_1_Audio-Video_streaming_same_time_no_response_from_HMI_for_Audio.lua
test_scripts/Defects/8_0/3479_2_Audio-Video_streaming_same_time_no_response_from_HMI_for_Video.lua
test_scripts/Defects/8_0/3479_3_Audio-Video_streaming_delayed_no_response_from_HMI_for_Audio.lua
test_scripts/Defects/8_0/3479_4_Audio-Video_streaming_delayed_no_response_from_HMI_for_Video.lua
test_scripts/Defects/8_0/common_3479_2810.lua
test_sets/Defects/Defects_release_8_0.txt

ATF Test Scripts to check #[2810](https://github.com/smartdevicelink/sdl_core/issues/2810)
Scripts for 2810 issue
develop
- Added new scripts for 2810 issue
- Updated common file for 3479 issue to avoid copy-paste of code and using this common file for 2819 scripts

Add scripts for issue 2810

---

user_modules/api/APITestDataGenerator.lua

ATF Test Scripts to check [#2655](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2655)
Improve stability GetVehicleData request for 'heading' value as part of gps parameter in scripts:
./test_scripts/API/VehicleData/GetVehicleData/001_GetVD_Success_flow.lua
Update rounding value to the smallest float number
latest
rounded value to the smallest float

Test scripts for issue 2655

---

test_scripts/Smoke/API/031_PerformAudioPassThru_PositiveCase_SUCCESS.lua

ATF Test Scripts to check [#2662](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2662)
Improve stability PerformAudioPassThru request in scripts:
./test_scripts/Smoke/API/031_PerformAudioPassThru_PositiveCase_SUCCESS.lua
latest
add AtLeast times for OnAudioPassThru notification

Test scripts for issue 2662

---

test_scripts/Security/GetSystemTime/common.lua

ATF Test Scripts to check [2679](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2679)
Improve stability 'PTU in scripts ./test_scripts/Security/GetSystemTime/011_GetSystemTime_mobile_cer_not_valid_sdl_becomes_invalid.lua
latest
add expectation SDL.OnStatusUpdate(UPDATING) for HTTP mode

Update test script for issue 2679

---

test_scripts/Defects/5_0/2467_Policy_table_corupted_after_first_ign_cycle.lua
test_sets/Defects/Defects_releases_4_x_and_5_x.txt

ATF Test Scripts to check [#2467](https://github.com/smartdevicelink/sdl_core/issues/2467)
Add test scripts for issue 2467
latest
Added new script
Test set updated with new added script

Add test scripts for issue 2467

---

test_scripts/Defects/8_2/3857_Crash_on_Ignition_Off_during_registering_Apps.lua
test_sets/Defects/Defects_release_8_2.txt

ATF Test Scripts to check [#3857](https://github.com/smartdevicelink/sdl_core/issues/3857)
Add test scripts for issue 3857
develop

Add test script for 3857
