config.py, fabfile.py
- Added variable with name of directory with test scripts to config.py
- Updated way to find scripts in test directory 
Related task : [APPLINK-25934](https://adc.luxoft.com/jira/browse/APPLINK-25934)
=> Add posibility to recursively find test scripts in configured directory

test_scripts/Polices/ATF_Preloaded_PT_validation.lua
Add check if SDL was stopped before trying start it.
If it wasn't then wait and stop SDL after timeout.
It is already merged in #174 in smartdevicelink:feature/external_proprietary_policy.
Please review @istoimenova
=> Fix tests for Starting SDL

user_modules/shared_testcases/commonFunctions.lua
Added conditions to catch OnStatusUpdate notification with UPDATING and UP_TO_DATE after registrations default app on ATF start because of sometimes in Test we can get UP_TO_DATE but sometimes firstly UPDATING and then UP_TO_DATE.
@LuxoftAKutsan please review.
=> Add fix to check_ptu_sequence_partly function to to catch UPDATING and UP_TO_DATE on starting default app

test_scripts/Polices/Validation_of_PolicyTables/277_ATF_Store_wers_country_code_in_PT.lua, test_scripts/Polices/Validation_of_PolicyTables/278_ATF_Store_language_in_PT.lua, test_scripts/Polices/Validation_of_PolicyTables/279_ATF_RAI_ccpu_version_via_GetSystemInfo.lua
Function AtLeast() was used to method Times() because script does not handle all HMI <-> SDL communications, first occurrence of BasicCommunication.GetSystemInfo is enough for reach goal of test
=> Updated test script with AtLeast function

test_scripts/Polices/Policy_Table_Update/003_ATF_P_TC_PTU_NotSuccessful_AppID_ListedPT_NewIgnCycle.lua
SDL should send OnStatusUpdate(UPDATE_NEEDED) after ignition on but not after OnAppRegistered
Related issues : APPLINK-31341 APPLINK-30381
=> Do not expect  OnStatusUpdate after OnAppRegistered

test_scripts/API/RAI/001_ATF_N_HMI_Does_Not_Respond_RAI_steeringWeelLocation.lua
Used common functions are implemented in 
https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/603
Script is part of TS: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/597
=> 001_HMI_Does_Not_Respond_RAI_steeringWheelLocation

test_scripts/API/PerformAudioPassThru/019_ATF_P_PerformAudioPassThru_WARNING_Missing_audioPassThruIcon_AllParams_STATIC.lua, test_scripts/API/PerformAudioPassThru/033_ATF_P_PerformAudioPassThru_WARNING_Missing_audioPassThruIcon_AllParams_STATIC.lua
019_ATF_P_PerformAudioPassThru_WARNING_Missing_audioPassThruIcon_AllParams_STATIC.lua 
Testing coverage available at #643
=>  019 Script for requirement  [PerformAudioPassThru] audioPassThruIcon does NOT exist at 'AppStorageFolder'

test_scripts/API/PerformAudioPassThru/023_ATF_P_PerformAudioPassThru_TTS_SUCCESS_UI_success_false.lua, test_scripts/API/PerformAudioPassThru/023_ATF_P_PerformAudioPassThru_TTS_SUCCESS_UI_success_false.lua.lua
023_ATF_P_PerformAudioPassThru_TTS_SUCCESS_UI_success_false.lua
=> 023 Script for requirement [PerformAudioPassThru] Speak (SUCCESS) + UI.PerformAudioPassThru (<applicable_resultCode>)

test_scripts/API/PerformAudioPassThru/024_ATF_P_PerformAudioPassThru_TTS_SUCCESS_UI_success_true.lua
024_ATF_P_PerformAudioPassThru_TTS_SUCCESS_UI_success_true.lua
=> 024 Script for requirement [PerformAudioPassThru] Speak (SUCCESS) + UI.PerformAudioPassThru (<applicable_resultCode>)

test_scripts/API/PerformAudioPassThru/026_ATF_P_PerformAudioPassThru_UI_success_false_TTS_success_false.lua
026_ATF_P_PerformAudioPassThru_UI_success_false_TTS_success_false.lua
=> 026 Script for requirement [PerformAudioPassThru] Speak (<errorCode>) + UI.PerformAudioPassThru (<errorCode>)

test_scripts/API/PerformAudioPassThru/025_ATF_P_PerformAudioPassThru_UI_SUCCESS_TTS_success_false_true.lua
025_ATF_P_PerformAudioPassThru_UI_SUCCESS_TTS_success_false_true.lua
=> 025 Script for requirement [PerformAudioPassThru] Speak (<errorCode>) + UI.PerformAudioPassThru (SUCCESS)

test_scripts/API/PerformAudioPassThru/027_ATF_P_PerformAudioPassThru_UI_timeout_TTS_success.lua
027_ATF_P_PerformAudioPassThru_UI_timeout_TTS_success.lua
=> 027 Script for requirement [GeneralResultCodes] GENERIC_ERROR watchdog timeout from HMI

test_scripts/API/PerformAudioPassThru/028_ATF_P_PerformAudioPassThru_TTS_timeout_UI_success.lua
028_ATF_P_PerformAudioPassThru_TTS_timeout_UI_success.lua
=> 028 Script for requirement [GeneralResultCodes] GENERIC_ERROR watchdog timeout from HMI

test_scripts/API/PerformAudioPassThru/029_ATF_P_PerformAudioPassThru_GENERIC_ERROR_invalid_HMI_response_fake_params.lua
Requirements:
[GENERIC_ERROR]: SDL behavior in case HMI sends invalid response AND SDL must transfer this response to mobile app
[HMI RPC validation]: SDL must send GENERIC_ERROR to mobile app in case SDL cuts off fake params from RPC and this RPC becomes invalid
029_ATF_P_PerformAudioPassThru_GENERIC_ERROR_invalid_HMI_response_fake_params.lua
=> 029 Script for requirements covering invalid HMI response in gerneral and due to fake params

test_scripts/API/PerformAudioPassThru/009_ATF_P_PerformAudioPassThru_SUCCESS_Dynamic_Image_All_Params.lua, test_scripts/API/PerformAudioPassThru/010_ATF_P_PerformAudioPassThru_SUCCESS_Dynamic_Image_MandatoryParams_and_audioPassThruIcon.lua, test_scripts/API/PerformAudioPassThru/021_ATF_P_PerformAudioPassThru_WARNING_Missing_audioPassThruIcon_AllParams_DYNAMIC.lua, test_scripts/API/PerformAudioPassThru/022_ATF_P_PerformAudioPassThru_WARNING_Missing_audioPassThruIcon_MandatoryParams_DYNAMIC.lua
@istoimenova 
Please review the updated paths for scripts:
009_ATF_P_PerformAudioPassThru_SUCCESS_Dynamic_Image_All_Params.lua
010_ATF_P_PerformAudioPassThru_SUCCESS_Dynamic_Image_MandatoryParams_and_audioPassThruIcon.lua
021_ATF_P_PerformAudioPassThru_WARNING_Missing_audioPassThruIcon_AllParams_DYNAMIC.lua
022_ATF_P_PerformAudioPassThru_WARNING_Missing_audioPassThruIcon_MandatoryParams_DYNAMIC.lua
=> Scripts updated with new expected path for DYNAMIC images adapted for both ATF and CI

test_scripts/API/PerformAudioPassThru/011_ATF_P_PerformAudioPassThru_SUCCESS_Valid_Request_Without_audioPassThruIcon.lua, test_scripts/API/PerformAudioPassThru/012_ATF_P_PerformAudioPassThru_SUCCESS_Mandatory_Only_Without_audioPassThruIcon.lua
@istoimenova Please check changes in scripts 011_ATF_P_PerformAudioPassThru_SUCCESS_Valid_Request_Without_audioPassThruIcon.lua  and 012_ATF_P_PerformAudioPassThru_SUCCESS_Mandatory_Only_Without_audioPassThruIcon.lua 
Due to change in specification the expected result is not SUCCESS instead of WARNINGS
=> Expected result changed due to update in specification

test_scripts/API/PerformAudioPassThru/029_ATF_P_PerformAudioPassThru_GENERIC_ERROR_invalid_HMI_response_fake_params.lua
@istoimenova Please check update in script 
029_ATF_P_PerformAudioPassThru_GENERIC_ERROR_invalid_HMI_response_fake_params.lua
=> Updated expectation for invalid HMI of TTS part

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/004_ATF_N_TC_existing_navi_app_certificate_exist.lua
Script is part of TS: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1163
common functions for CRQ: #1175
=> 004_ATF_N_TC_existing_navi_app_certificate_exist

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/005_ATF_P_TC_default_app_first_StartService_RPC_encrypt_true.lua
PRs: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1196; https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1197 have common scenario for different type of applications.
=> 005_ATF_P_TC_default_app_first_StartService_RPC_encrypt_true

test_scripts/Polices/External_UCS_Informing_HMI/002_ATF_P_GetListofPermissions_with_appID_all_ecs_lower_bound_EntitySatus_ON.lua
002_ATF_P_GetListofPermissions_with_appID_all_ecs_lower_bound_EntitySatus_ON.lua 
Test set available in  #1165
=> 002 Script for requirement [Policies] [External UCS] SDL informs HMI about <externalConsentStatus> via GetListOfPermissions response

test_scripts/Polices/External_UCS_Informing_HMI/003_ATF_P_GetListofPermissions_with_appID_all_ecs_upper_bound_EntitySatus_ON.lua
003_ATF_P_GetListofPermissions_with_appID_all_ecs_upper_bound_EntitySatus_ON.lua 
=> 003 Script for requirement [Policies] [External UCS] SDL informs HMI about <externalConsentStatus> via GetListOfPermissions response

test_scripts/Polices/External_UCS_Informing_HMI/004_ATF_P_GetListofPermissions_with_appID_fake_param_cut_EntitySatus_ON.lua
004_ATF_P_GetListofPermissions_with_appID_fake_param_cut_EntitySatus_ON.lua 
=> 004 Script for requirement [Policies] [External UCS] SDL informs HMI about <externalConsentStatus> via GetListOfPermissions response

test_scripts/Polices/External_UCS_Informing_HMI/005_ATF_P_GetListofPermissions_with_appID_all_ecs_in_bound_EntitySatus_OFF.lua
005_ATF_P_GetListofPermissions_with_appID_all_ecs_in_bound_EntitySatus_OFF.lua 
=> 005 Script for requirement [Policies] [External UCS] SDL informs HMI about <externalConsentStatus> via GetListOfPermissions response

test_scripts/Polices/External_UCS_Informing_HMI/006_ATF_P_GetListofPermissions_with_appID_all_ecs_lower_bound_EntitySatus_OFF.lua
006_ATF_P_GetListofPermissions_with_appID_all_ecs_lower_bound_EntitySatus_OFF.lua 
=> 006 Script for requirement [Policies] [External UCS] SDL informs HMI about <externalConsentStatus> via GetListOfPermissions response

test_scripts/Polices/External_UCS_Informing_HMI/007_ATF_P_GetListofPermissions_with_appID_all_ecs_upper_bound_EntitySatus_OFF.lua
007_ATF_P_GetListofPermissions_with_appID_all_ecs_upper_bound_EntitySatus_OFF.lua 
=> 007 Script for requirement [Policies] [External UCS] SDL informs HMI about <externalConsentStatus> via GetListOfPermissions response

tools/lua_style_and_check.sh
Pre-commit hook was applied to all test scripts
User modules still not under luacheck code control.
=> Pre-commit hook was applied to all test scripts

test_scripts/Polices/External_UCS_Informing_HMI/008_ATF_P_GetListofPermissions_with_appID_fake_param_cut_EntitySatus_OFF.lua
008_ATF_P_GetListofPermissions_with_appID_fake_param_cut_EntitySatus_OFF.lua 
=> 008 Script for requirement [Policies] [External UCS] SDL informs HMI about <externalConsentStatus> via GetListOfPermissions response

test_scripts/Polices/External_UCS_Informing_HMI/009_ATF_P_GetListofPermissions_with_appID_not_stored_ecs.lua
009_ATF_P_GetListofPermissions_with_appID_not_stored_ecs.lua 
=> 009 Script for requirement [Policies] [External UCS] SDL informs HMI about <externalConsentStatus> via GetListOfPermissions response

test_scripts/Polices/External_UCS_Informing_HMI/010_ATF_P_GetListofPermissions_no_appID_stored_ecs_present.lua
010_ATF_P_GetListofPermissions_no_appID_stored_ecs_present.lua 
=> 010 Script for requirement [Policies] [External UCS] SDL informs HMI about <externalConsentStatus> via GetListOfPermissions response

test_scripts/Polices/External_UCS_Informing_HMI/011_ATF_P_GetListofPermissions_no_appID_not_stored_ecs.lua
011_ATF_P_GetListofPermissions_no_appID_not_stored_ecs.lua 
=> 011 Script for requirement [Policies] [External UCS] SDL informs HMI about <externalConsentStatus> via GetListOfPermissions response

test_scripts/Polices/External_UCS_Informing_HMI/018_ATF_N_GetListofPermissions_empty_due_to_missing_status_OnAppPermissionChange.lua
018_ATF_N_GetListofPermissions_empty_due_to_missing_status_OnAppPermissionChange.lua
Script is a part of TS #1165 
@istoimenova  Please review
=> 018 Script for requirement [Policies] [External UCS] SDL informs HMI about <externalConsentStatus> via GetListOfPermissions response

test_scripts/Polices/External_UCS_Informing_HMI/017_ATF_N_GetListofPermissions_empty_due_to_missing_entityID_OnAppPermissionChange.lua
017_ATF_N_GetListofPermissions_empty_due_to_missing_entityID_OnAppPermissionChange.lua 
Script is a part of TS #1165 
=> 017 Script for requirement [Policies] [External UCS] SDL informs HMI about <externalConsentStatus> via GetListOfPermissions response

test_scripts/Polices/External_UCS_Informing_HMI/016_ATF_N_GetListofPermissions_empty_due_to_missing_entity_type_OnAppPermissionChange.lua
016_ATF_N_GetListofPermissions_empty_due_to_missing_entity_type_OnAppPermissionChange.lua
Script is a part of TS #1165
=> 016 Script for requirement [Policies] [External UCS] SDL informs HMI about <externalConsentStatus> via GetListOfPermissions response

test_scripts/Polices/External_UCS_Informing_HMI/012_ATF_N_GetListofPermissions_no_appID_no_app_registered_stored_ecs.lua
012_ATF_N_GetListofPermissions_no_appID_no_app_registered_stored_ecs.lua 
=> 012 Script for requirement [Policies] [External UCS] SDL informs HMI about <externalConsentStatus> via GetListOfPermissions response

test_scripts/Polices/External_UCS_Informing_HMI/013_ATF_N_GetListofPermissions_no_appID_no_app_registered_not_stored_ecs.lua
013_ATF_N_GetListofPermissions_no_appID_no_app_registered_not_stored_ecs.lua 
=> 013 Script for requirement [Policies] [External UCS] SDL informs HMI about <externalConsentStatus> via GetListOfPermissions response

test_scripts/Polices/External_UCS_Informing_HMI/014_ATF_N_GetListofPermissions_no_appID_app_unregistered_stored_ecs.lua
014_ATF_N_GetListofPermissions_no_appID_app_unregistered_stored_ecs.lua 
=> 014 Script for requirement [Policies] [External UCS] SDL informs HMI about <externalConsentStatus> via GetListOfPermissions response

test_scripts/Polices/External_UCS_Informing_HMI/022_ATF_N_OnAppPermissionConsent_not_sent_when_no_PTU.lua
022_ATF_N_OnAppPermissionConsent_not_sent_when_no_PTU.lua 
=> 022 Script for requirement [Policies] [External UCS] SDL informs HMI about <externalConsentStatus> via GetListOfPermissions response

test_scripts/Polices/External_UCS_Informing_HMI/015_ATF_N_GetListofPermissions_no_appID_app_unregistered_not_stored_ecs.lua
015_ATF_N_GetListofPermissions_no_appID_app_unregistered_not_stored_ecs.lua 
=> 015 Script for requirement [Policies] [External UCS] SDL informs HMI about <externalConsentStatus> via GetListOfPermissions response

test_scripts/API/PerformAudioPassThru/029_ATF_P_PerformAudioPassThru_GENERIC_ERROR_invalid_HMI_response_fake_params.lua
Applying fix for [GENIVI] Info parameter not sent for GENERIC_ERROR result code for PerformAudioPassThru when Invalid HMI response receive
Quotes need to be added to code parameter value to facilitate ATF processing of message
=> Adding quotes to code parameter value to facilitate ATF processing

test_scripts/ATF_ShutDown_IGNITION_OFF.lua, test_scripts/ATF_ShutDown_MASTER_RESET.lua, user_modules/dummy_connecttest.lua, user_modules/shared_testcases/commonFunctions.lua
Add tests for ShutDown MASTER_RESET and ShutDown IGNITION_OFF
Add dummy_connecttest and use it instead of connecttest.
Add waitForSDLStart and createMultipleExpectationsWaiter functions to CommonFunctions.
[SDLOPEN-932](https://adc.luxoft.com/jira/browse/SDLOPEN-932)
Is the same connect test that do not add any test cases to script by default. 
You should **run sdl**,  **init hmi**,  **connect mobile** , etc ... in your preconditions. In case if you need to avoid some step or modify it, you is able to redefine any step before call or do not call it at all ( for example if you need to start SDL without HMI)
Also each function like **init_hmi**, **init_hmi_onReady**, etc ..., now returns expectations. Not is is possible to shedule some code, that will be executed when step is done …
=> ShutDown Smoke tests

test_scripts/Polices/External_UCS_Informing_HMI/020_ATF_N_GetListofPermissions_empty_due_to_invalid_param_entityID_OnAppPermissionChange.lua
020_ATF_N_GetListofPermissions_empty_due_to_invalid_param_entityID_OnAppPermissionChange.lua
test is a part of TS #1165 
=> 020 Script for requirement [Policies] [External UCS] SDL informs HMI about <externalConsentStatus> via GetListOfPermissions response

test_scripts/Polices/External_UCS/External_Consent_OFF/030_ATF_Policies_External_Consent_OFF_empty_consent_groups.lua
030_ATF_Policies_External_Consent_OFF_empty_consent_groups.lua 
Test set is available in #1219 
User modules should be taken from #1211 
@dboltovskyi @vvvakulenko @ttdong 
=> [WIP] 030 Test for requirement [Policies] External UCS: empty consent_groups changes after externalConsentStatus was received

test_scripts/Polices/External_UCS/External_Consent_OFF/028_ATF_Policies_External_Consent_OFF_same_notification_user_consent_allowed_externalConsentStatus_disallowed.lua, test_scripts/Polices/External_UCS/External_Consent_OFF/029_ATF_Policies_External_Consent_OFF_same_notification_user_consent_disallowed_externalConsentStatus_allowed.lua
028_ATF_Policies_External_Consent_OFF_same_notification_user_consent_allowed_externalConsentStatus_disallowed.lua
029_ATF_Policies_External_Consent_OFF_same_notification_user_consent_disallowed_externalConsentStatus_allowed.lua
Test set is available in #1219
User modules should be taken from #1211
@dboltovskyi @vvvakulenko @ttdong
=> [WIP] 028 and 029 Scripts for [Policies] External UCS: externalConsentStatus vs. consentedFunctions priority

test_scripts/Polices/External_UCS/External_Consent_OFF/024_ATF_Policies_External_Consent_OFF_many_entities_pairs_in_one_group_01.lua, test_scripts/Polices/External_UCS/External_Consent_OFF/025_ATF_Policies_External_Consent_OFF_many_entities_pairs_in_one_group_02.lua, test_scripts/Polices/External_UCS/External_Consent_OFF/026_ATF_Policies_External_Consent_OFF_many_entities_pairs_in_one_group_03.lua, test_scripts/Polices/External_UCS/External_Consent_OFF/027_ATF_Policies_External_Consent_OFF_many_entities_pairs_in_one_group_04.lua
024_ATF_Policies_External_Consent_OFF_many_entities_pairs_in_one_group_01.lua 
025_ATF_Policies_External_Consent_OFF_many_entities_pairs_in_one_group_02.lua 
026_ATF_Policies_External_Consent_OFF_many_entities_pairs_in_one_group_03.lua 
027_ATF_Policies_External_Consent_OFF_many_entities_pairs_in_one_group_04.lua 
Test set is available in #1219
User modules should be taken from #1211
@dboltovskyi @vvvakulenko @ttdong
=> [WIP] 024,025,026,027 Scripts for requirement [Policies] External UCS: externalConsentStatus change for the whole functional_group

test_scripts/Polices/External_UCS/External_Consent_OFF/022_ATF_Policies_External_Consent_OFF_regist_new_app_disallowed_by_external_consent_entities_off.lua, test_scripts/Polices/External_UCS/External_Consent_OFF/023_ATF_Policies_External_Consent_OFF_regist_new_app_disallowed_by_external_consent_entities_on.lua
022_ATF_Policies_External_Consent_OFF_regist_new_app_disallowed_by_external_consent_entities_off.lua
023_ATF_Policies_External_Consent_OFF_regist_new_app_disallowed_by_external_consent_entities_on.lua
Test set is available in #1219
User modules should be taken from #1211
@dboltovskyi @vvvakulenko @ttdong
=> [WIP] 022, 023 Scripts for requirements [Policies] External UCS: settings for all connected apps

user_modules/connecttest_TTS_Isready.lua, user_modules/connecttest_VR_Isready.lua, user_modules/connecttest_initHMI.lua, user_modules/connecttest_resumption.lua, user_modules/shared_testcases/connecttest_TTS_Isready.lua
This is an update of specific _connection_test_ modules regarding https://github.com/smartdevicelink/sdl_atf/pull/83
=> Fix ATF hangs-up script execution when SDL is already running (extended) 

user_modules/connecttest_TTS_Isready.lua, user_modules/connecttest_VR_Isready.lua, user_modules/connecttest_resumption.lua, user_modules/dummy_connecttest.lua, user_modules/shared_testcases/connecttest_TTS_Isready.lua
This is an update of specific _connection_test_ modules regarding https://github.com/smartdevicelink/sdl_atf/pull/83
=> Fix ATF hangs-up script execution when SDL is already running (develop)

user_modules/shared_testcases/commonPreconditions.lua
Remove redundant 'local' statement
=> Fixed function getAbsolutePath()

test_scripts/API/PerformAudioPassThru/028_ATF_P_PerformAudioPassThru_TTS_timeout_UI_success.lua
Update based on requirement: "[HMI Status]: SDL must must send ATTENUATED streamingState to app in case SDL receives TTS.Started notification from HMI"
=> Update of expectation for OnHMIStatus

test_scripts/API/IsReady/UI_IsReady/SetAudioStreamingIndicator/002_ATF_N_TC_SetAudioStreamingIndicator_success_false_IsReady_HMI_doesnot_reply.lua, test_scripts/API/PerformAudioPassThru/023_ATF_P_PerformAudioPassThru_TTS_SUCCESS_UI_success_false.lua, test_scripts/API/PerformAudioPassThru/025_ATF_P_PerformAudioPassThru_UI_SUCCESS_TTS_success_false_true.lua, test_scripts/API/PerformAudioPassThru/026_ATF_P_PerformAudioPassThru_UI_success_false_TTS_success_false.lua, test_scripts/API/SetAudioStreamingIndicator/033_ATF_N_TC_SetAudioStreamingIndicator_media_app_HMI_replies_resultcode_success_false.lua, test_scripts/API/SetAudioStreamingIndicator/067_ATF_N_TC_SetAudioStreamingIndicator_media_app_sends_2_requests_HMI_replies_resultcode_success_false.lua
Clarification: "Must SDL resend HMI resultCode hmi_apis::Common_Result::DATA_NOT_AVAILABLE to mobile app"
=> VEHICLE_DATA_NOT_AVAILABLE is commented due to suspendd clarification.

test_scripts/Polices/appID_Management/162_ATF_P_TC_HMI_Status_Appid_Gets_Null_In_Case_Of_PTU.lua, test_scripts/Polices/appID_Management/163_ATF_P_TC_HMI_Status_Value_Of_AppId_In_PT_Is_Null.lua
This pull request fixes two scripts, that were not correspondent to current, updated requirements (please ask me if you need applink of correspondent jira task).
With this pr, scripts became updated and represent current requirements state.
@dboltovskyi 
@Itileda
=> Fix ptu is null scripts

test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/010_ATF_P_TC_media_app_PTU_fail_ForceProtectedService_ON_RPC_encrypted_true.lua, test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/011_ATF_P_TC_comm_app_PTU_fail_ForceProtectedService_ON_RPC_encrypted_true.lua, test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/012_ATF_P_TC_default_app_PTU_fail_ForceProtectedService_ON_RPC_encrypted_true.lua, test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/027_ATF_P_TC_navi_app_PTU_fail_ForceProtectedService_OFF_Audio_encrypted_true.lua, test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/028_ATF_P_TC_navi_app_PTU_fail_ForceProtectedService_OFF_Video_encrypted_true.lua, test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/029_ATF_P_TC_navi_app_PTU_fail_ForceProtectedService_OFF_Hybrid_encrypted_true.lua, test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/030_ATF_P_TC_navi_app_PTU_fail_ForceProtectedService_OFF_RPC_encrypted_true.lua, test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/035_ATF_P_TC_media_app_PTU_fail_ForceProtectedService_OFF_RPC_encrypted_true.lua, test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/036_ATF_P_TC_comm_app_PTU_fail_ForceProtectedService_OFF_RPC_encrypted_true.lua, test_scripts/Polices/Policies_Security/Trigger_PTU_NO_Certificate/037_ATF_P_TC_default_app_PTU_fail_ForceProtectedService_OFF_RPC_encrypted_true.lua
Reverts smartdevicelink/sdl_atf_test_scripts#1396
Based on clarification "Can you clarify should SDL send UPDATING after ptu fails?" changes are removed.
=> Revert "Fix scripts with not finished PTU"

test_scripts/API/RAI/031_ATF_P_steeringWheelLocation_LEFT_hmi_capabilities_RIGHT_IGN_OFF_IGN_ON_RAI_steeringWheelLocation.lua
Because of ATF defect "[ATF] ATF stops execution of scripts at IGNITION_OFF." script is updated.
=> Update based on ATF defect.

test_scripts/Polices/Related_HMI_API/206_ATF_OnAppPermissionConsent_with_appID.lua, test_scripts/Polices/Related_HMI_API/211_ATF_GetListOfPermissions_without_appID.lua, test_scripts/Polices/Related_HMI_API/212_ATF_GetListOfPermissions_with_appID.lua
UPDATE_NEEDED because of new trigger will be sent after finish first PTU.
As this is not expected in script, successful PTU is not added.
=> Remove expectation of UPDATE_NEEDED

test_scripts/Polices/Policy_Table_Update/027_ATF_P_TC_HMILvl_on_PTU_affected_in_FULL_or_LIMITED.lua
SDL will use one of applications in HMI level different that NONE.
To be sure that SDL will use application 2, first application is left in HMI level NONE.
=> Remove activation of first application.

test_scripts/Polices/user_consent_of_Policies/ATF_Device_identifier_creation_upon_connect_no_apps.lua
Verification of PTS element is removed because SDL snapshot will not be created until Device is consented through registered application
=> remove verification of pts

user_modules/shared_testcases/testCasesForExternalUCS.lua
Issue: "[GENIVI] SDL restarts PTU sequence with sending redundant BC.PolicyUpdate"
=> Update based on issue:

test_scripts/Polices/build_options/015_ATF_P_TC_Sending_PTS_to_Mobile_Application_HTTP.lua
"d.payload.timeout" is a number, but "timeout" is a string,
so because of that: (d.payload.timeout ~= timeout) was always return true.
After  type casting **tostring(**d.payload.timeout**)**  ValidIf(..) works correctly
=> Cast number to string

test_scripts/Polices/Validation_of_PolicyTables/293_ATF_HP_Applying_Heart_Beat_Timeout_Ms_From_PT.lua, test_scripts/Polices/Validation_of_PolicyTables/295_ATF_HP_Applying_Heart_Beat_Timeout_Ms_After_PTU.lua
Use local expectation of "Heartbeat" event instead of default one from ATF.
Use new functionality from ATF- start RPC with specific heartbeat
=> Fix checking of Heartbeat

test_scripts/RC/GetInteriorVehicleDataCapabilities/008.lua
The problem is that PTU generated by current script have `moduleType` value `{ }` which is not correct and this is a reason of PTU failure. The correct one is `[ ]`.
This pull request solves this issue.
=> Fix PTU sending with empty array member

user_modules/shared_testcases/commonFunctions.lua
Before this fix it was no possible to build SDL and to run ATF test scripts in the same time
=> Fix force killing of SDL

user_modules/dummy_connecttest.lua
- Added `hmi_table_element.occurrence` to hmi_capabilities
- Added logic for `hmi_table_element.occurrence == 0`
Example of input table:
```
hmi_table.UI.IsReady = {
params = {
available = true
},
mandatory = true,
pinned = false,
occurrence = 0
}
```
- Remove strict derivation of function logic on base of  `hmi_table_element.occurrence`
- Add logic for case SDL sends request and HMI does not responds (parameter "params = nil")
Example of input table:
```
hmi_table.UI.IsReady = {
params = nil,
mandatory = true,
pinned = false
}
```
- Add wait parameter for delay expectation configuring 
(with next logic: create delayed expectation only in case it was not created for set or bigger time)
Example of input table:
```
hmi_table.UI.IsReady = {
params = {
available = true
},
mandatory = true, …
```
=> Fixed issue with Times 0

user_modules/dummy_connecttest.lua, user_modules/hmi_values.lua, user_modules/script_runner.lua, user_modules/shared_testcases/commonFunctions.lua, user_modules/test_settings.lua
**Changes:**
- Function readParameterFromCMakeCacheFile was added to commonFunction module
- Test script runner was updated with SDL and script compatibility check
- Created module with table that contains all information and restrictions of test
- Create module which handle ATF config and populate it with data about SDL build options
- Updated HMI capabilities module with logic to handle cases when RC functionality is on/off
- For example one test script was reworked to show described above improvements.
**Examples:**
Run test that requires next SDL build options:
`REMOTE_CONTROL = ON` and `EXTENDED_POLICY = PROPRIETARY`
with SDL built with options
`REMOTE_CONTROL = ON` and `EXTENDED_POLICY = PROPRIETARY`
```
==============================
Start …
```
=> Implementation of test runner with sdl build options

test_scripts/API/VehicleData/GetVehicleData/001_Success_flow.lua, test_scripts/API/VehicleData/GetVehicleData/002_RPC_parameter_DISALLOWED_by_policies_flow.lua, test_scripts/API/VehicleData/OnVehicleData/001_Success_flow.lua, test_scripts/API/VehicleData/OnVehicleData/002_NotificationForUnsubsribedParameter_Ignored_flow.lua, test_scripts/API/VehicleData/OnVehicleData/003_NotificationParameterDisallowedByPolicies_Ignored_flow.lua, test_scripts/API/VehicleData/SubscribeVehicleData/001_Success_flow.lua, test_scripts/API/VehicleData/SubscribeVehicleData/002_RPC_parameter_DISALLOWED_by_policies_flow.lua, test_scripts/API/VehicleData/SubscribeVehicleData/003_RPC_parameter_already_subscribed_Result_IGNORED_flow.lua, test_scripts/API/VehicleData/UnsubscribeVehicleData/001_Success_flow.lua, test_scripts/API/VehicleData/UnsubscribeVehicleData/002_RPC_parameter_not_yet_subscribed_IGNORED_flow.lua, test_scripts/API/VehicleData/UnsubscribeVehicleData/003_RPC_parameter_already_unsubscribed_Result_IGNORED_flow.lua, test_scripts/API/VehicleData/UnsubscribeVehicleData/004_RPC_parameter_disallowed_by_policies_Result_DISALLOWED_flow.lua, test_scripts/API/VehicleData/commonVehicleData.lua
Created test coverage for RPCs containing `engineOilLife` parameter
``` "GitHub issue link" ~ "https://github.com/SmartDeviceLink/sdl_core/issues/1733" ```
=> Added common module for VehicleData and test coverage

user_modules/dummy_connecttest.lua
Currently if expected data is provided in EXPECT_HMIRESPONSE() function it fails with error.
This fix removes unnecessary code that was the reason of the issue.
=> Fix EXPECT_HMIRESPONSE issue with expected result validation

test_scripts/smoke_api.lua
According to req-t "[ResetGlobalProperties] SUCCESS on UI.SetGlobalProperties and TTS.SetGlobalPrtoperties":
>In case mobile app sends valid ResetGlobalProperties with "HELPPROMPT" and/or "TIMEOUTPROMPT" and at least one other valid parameter in "properties" array, SDL must:
>1) set-up the value of 'HelpPrompt' to an empty array and/or retrieve the value of "TimeOutPrompt" parameter from .ini file correspondingly
>2) transfer the items requested ("HELPPROMPT" or/and "TIMEOUTPROMPT") TTS.SetGlobalProperties(helpPrompt:"<empty array>", and/or timeoutPrompt:<'TimeOutPrompt' from ini.file>) to HMI.
>3) transfer UI.SetGlobalProperties with appropriate values to HMI (see more APPLINK-20718, APPLINK-20825).
>4) respond (resultCode:SUCCESS, success:true) to mobile application on getting the both …
=> Fix for ResetGlobalProperties regarding helpPrompt

user_modules/shared_testcases/commonFunctions.lua
A 50 ms timeout was causing a lot of false negatives for certain test cases. Looking at the blame, I believe that this line had been changed to a higher value but then was readded as 50ms via a copy and paste error. I have decided to remove the timeout entirerly and let ATF use the default timeout instead.
=> Remove timeout

test_scripts/API/Navigation/SendLocation/021_SendLocation_out_of_bound_values.lua, test_scripts/API/Navigation/SendLocation/022_SendLocation_fake_another_request_params.lua, test_scripts/API/Navigation/SendLocation/023_SendLocation_app_not_registered.lua, test_scripts/API/Navigation/SendLocation/024_SendLocation_diff_HMI_levels.lua, test_scripts/API/Navigation/SendLocation/025_SendLocation_duplicated_corr_id.lua, test_scripts/API/Navigation/SendLocation/026_SendLocation_disallowed_by_policies.lua, test_scripts/API/Navigation/SendLocation/027_SendLocation_invalid_HMI_responses.lua
Added checks:
- our of boundary values 
- fake parameters
- application not registered 
- request in different HMI levels
- duplicated correlation id
- API disallowed by policies
- invalid HMI responses
=> Regression SendLocation scripts

test_scripts/API/Navigation/OnWayPointChange/008_OnWayPointChange_boundary_values_by_parameters.lua
In case minlength of 'String' parameter is ommited SDL must set '1' as minlength by default
=> Fix minlength of 'String' parameter

test_scripts/Defects/4_5/1772_update_default_section.lua, test_scripts/Defects/4_5/commonDefects.lua
Script for reproducing defect https://github.com/SmartDeviceLink/sdl_core/issues/1772 "Default app policies are never updated after a PTU"
=> Script for issue1772 "Default app policies are never updated after a PTU"

test_scripts/Defects/4_5/1225_FACTORY_DEFAULTS.lua
Script for issue  https://github.com/SmartDeviceLink/sdl_core/issues/1225 "SDL does not clear all user consent records in "user_consent_records" section of the LocalPT"
=> Script for issue 1225 "SDL does not clear all user consent records in "user_consent_records" section of the LocalPT" - Drop2

test_scripts/Defects/4_5/1892_HB_from_SDL_after_receiving_HB_from_mobile.lua
Script for issue https://github.com/smartdevicelink/sdl_core/issues/1892 "SDL must start heartbeat only after first Heartbeat request from mobile app"
=> Script for issue 1892 "SDL must start heartbeat only after first Heartbeat request from mobile app" - Drop3

test_scripts/Defects/4_5/1912_Video_service_start_via_2_protocol.lua
Script for issue https://github.com/SmartDeviceLink/sdl_core/issues/1912 "SDL must respond NACK in case navigation app connected over protocol v2 sends StartService for audio service"
=> Script for issue 1912 "SDL must respond NACK in case navigation app connected over protocol v2 sends StartService for audio service" - Drop4

test_scripts/Defects/4_5/1873_Parameters_empty_in_policy_table.lua, test_scripts/Defects/4_5/1873_UnsubscribeVD_OnVD_Parameters_empty_in_policy_table.lua
Scripts for issue https://github.com/SmartDeviceLink/sdl_core/issues/1873 "PoliciesManager allows all requested params in case "parameters" field is empty"
=> Scripts for issue 1873 "PoliciesManager allows all requested params in case "parameters" field is empty" - Drop3

test_scripts/Smoke/Resumption/ATF_Resumption_3rd_ignition_cycle.lua, test_scripts/Smoke/Resumption/ATF_Resumption_FULL_IGNITION_OFF.lua, test_scripts/Smoke/Resumption/ATF_Resumption_LIMITED_IGNITION_OFF.lua, test_scripts/Smoke/Resumption/ATF_Resumption_app_registered_in_more_than_30sec_after_BC.OnReady.lua, test_scripts/Smoke/Resumption/ATF_Resumption_disconnect_more_than_30s_before_SUSPEND.lua, test_scripts/Smoke/ShutDown/ATF_ShutDown_IGNITION_OFF.lua, test_scripts/Smoke/ShutDown/ATF_ShutDown_MASTER_RESET.lua
Fix is related to the case when Postconditions step was executed a long time.
ATF did not close SDL logger in case if SDL was stopped successfully (Ignition Off, Factory Reset etc.)
There is also fix on ATF side in PR [#111](https://github.com/smartdevicelink/sdl_atf/pull/111)
=> Fix issue regarding long executuion of Postconditions

test_scripts/RC/commonRC.lua
This PR fixes 2 issues:
1. During execution of ```commonRC.rai_ptu_n()``` function there are 2 ```OnPermissionsChange``` notifications are sent to mobile app: one for ```RegisterAppInterface``` and 2nd one for ```PTU```
2. Temporary .json file was not removed since corresponding code was executed too early
=> Stabilize RC scripts

test_scripts/Smoke/Registration/001_Register_5_connection.lua, test_scripts/Smoke/Resumption/008_Resumption_heartbeat_disconnect.lua, user_modules/dummy_connecttest.lua
Since it's possible to register the same expectations several times, user expectations have to have higher priority over system expectations.
Eg.: ```BC.UpdateAppList``` which is registered twice: 
1) in ```initHMI_onReady()``` of ```dummy_connecttest``` module
2) in ```Smoke/Registration/006_Reregister_App_if_two_apps_are_registered.lua```
=> Fix check priority of events

test_scripts/RC/commonRC.lua
Since iAP over Bluetooth switching brings new definition for MAC and Device ID, this PR fixes RC tests
=> Fix obtaining of MAC address and Device Id

user_modules/shared_testcases/commonTestCases.lua
```testCasesForPolicyTable``` module is not used in ```commonTestCases``` module.
But in ```testCasesForPolicyTable``` module 2nd version of SDL protocol is defaulted.
So removing of this module from required list solves an issues with smoke tests.
=> Remove defaulting of 2nd version of SDL protocol

test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/006_RPC_parameters_values.lua, test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/012_Transfering_of_HMI_resultCode_to_mobile.lua, test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/013_Absence_of_isSubscribed_parameter_in_case_request_from_Mob_app_without_subscribe_parameter_but_response_from_HMI_with_isSubscribed.lua, test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/014_Absence_of_subscribe_parameter_in_request_for_HMI_in_case_of_2nd_Subscription_UnSubscription.lua, test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/015_Transfering_of_isSubscribed_parameter_in_case_request_from_Mob_app_with_subscribe_parameter_but_response_from_HMI_without_isSubscribed.lua, test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/OnInteriorVehicleData/005_Absence_of_OnIVD_in_case_of_successfull_subscribing_with_isSubscribe_false_from_HMI.lua, test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/OnInteriorVehicleData/009_Existence_of_OnIVD_in_case_of_successfull_unsubscribing_with_isSubscribe_true_from_HMI.lua, test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/OnInteriorVehicleData/010_Existence_of_OnIVD_in_case_of_successfull_unsubscribing_without_isSubscribe_from_HMI.lua, test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/commonRCmodules.lua
According to proposal 'keepContext' parameter is not required for the responses for AUDIO module, so it's need to be removed.
=> Remove not required parameter 'keepContext' in responses for AUDIO module

test_scripts/Image_template/001_isTemplate_is_true.lua, test_scripts/Image_template/003_isTemplate_is_absent.lua, test_scripts/Image_template/004_isTemplate_invalid_type.lua, test_scripts/Image_template/005_isTemplate_is_true_with_not_png_image.lua, test_scripts/Image_template/006_isTemplate_is_true_with_STATIC_image.lua, test_scripts/Image_template/commonImageTemplate.lua, test_sets/template_images.txt
Expanded coverage with STATIC image type and not PNG file type according to clarification in https://github.com/smartdevicelink/sdl_requirements/issues/53
=> Expanded coverage with STATIC image type and not PNG file type

user_modules/script_runner.lua
Some scripts have a lot of test cases. Each test case is separated from another one by Title.
Currently there is no possibility to see this Title in ATF log. This PR adds such option.
=> Add Title to ATF report

test_scripts/Defects/4_6/1035_SDL_doesnt_send_REJECTED_code_to_mobile_app_when_activating_app_from_HMI_with_activate.lua, test_scripts/Defects/commonDefects.lua
Verified:
SDL doesn't send "REJECTED" code to mobile app when activating app from HMI
with activate https://github.com/smartdevicelink/sdl_core/issues/1035
=> Verified issue SDL doesn't send "REJECTED" code to mobile

test_scripts/Defects/4_6/1031_SDL_transfer_OnKeyboardInput_notification_to_not_active_App_when_there_is_no_active_PerformInteraction_KEYBOARD.lua
Verified:
SDL transfer OnKeyboardInput notification to not active App when there
is no active PerformInteraction(KEYBOARD) smartdevicelink/sdl_core#1031
=> Verified issue SDL transfer OnKeyboardInput notification to not active App

test_scripts/SDL4.6/SDL-0162/001_DuplicateCorrelationIDs_INVALID_ID.lua
Requires https://github.com/smartdevicelink/sdl_atf/pull/135 to pass
Tests for [SDL-0162](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0162-define-handling-of-duplicate-correlation-ids.md), Core PR: https://github.com/smartdevicelink/sdl_core/pull/2101
=> Test handling of duplicate correlation IDs

test_scripts/Defects/4_6/965_API_App_is_not_unregistered_by_reason_=_REQUEST_WHILE_IN_NONE_HMI_LEVEL.lua
Script for reproducing issue [[API] App is not unregistered by reason = REQUEST_WHILE_IN_NONE_HMI_LEVEL](https://github.com/smartdevicelink/sdl_core/issues/965)
=> Script for reproducing issue 965

test_scripts/Defects/4_6/1032_CreateInteractionChoiceSet_core_successfully_creates_choice_set_with_duplicate_vrCommands_menuName_inside_it.lua
Script for reproducing issue [CreateInteractionChoiceSet: core successfully creates choice set with duplicate vrCommands/menuName inside it](https://github.com/SmartDeviceLink/sdl_core/issues/1032)
=> Script for reproducing issue 1032

test_scripts/Defects/4_6/972_SDL_should_respond_IGNORED_with_correct_result_code_for_UnSubscribeVehicleData_in_case_vi_interface_is_not_available.lua
Script for reproducing issue [SDL should respond "IGNORED" with correct result code for UnSubscribeVehicleData in case vi interface isn't available](https://github.com/SmartDeviceLink/sdl_core/issues/972)
=> Script for reproducing issue 972

test_scripts/RC/CLIMATE_RADIO/OnRemoteControlSettings/008_Allowed_false.lua, test_scripts/RC/CLIMATE_RADIO/OnRemoteControlSettings/024_Allowed_false_no_PTU.lua
Test for verifying of the issue https://github.com/smartdevicelink/sdl_core/issues/2173
=> Verifies that SDL does not put RC apps to NONE state when user disables RC in HMI

test_scripts/Defects/4_6/964_SDL_sends_to_mobile_APPLICATION_NOT_REGISTRED_in_setAppIcon_responce_if_HMI_responds_with_INVALID_DATA.lua
Script for reproducing issue [SDL sends to mobile "APPLICATION_NOT_REGISTRED" in setAppIcon responce if HMI responds with "INVALID_DATA"](https://github.com/smartdevicelink/sdl_core/issues/964)
=> Scripts for reproduce issues 964

test_scripts/Policies/build_options/066_ATF_PTU_Validation_Failure_HTTP.lua
Updates for ATF Test Scripts
According to requirements in case if PTU validation failure SDL should send SDL.OnStatusUpdate(UPDATE_NEEDED) to HMI and that`s all.
SDL no need to start any retry in this case.
=> Fix policy script 066 according to clarification

test_scripts/API/ATF_AddCommand.lua, test_scripts/API/ATF_Alert.lua, test_scripts/API/ATF_AlertManeuver.lua, test_scripts/API/ATF_CreateInteractionChoiceSet.lua, test_scripts/API/ATF_PerformInteraction.lua, test_scripts/API/ATF_ScrollableMessage.lua, test_scripts/API/ATF_SetGlobalProperties.lua, test_scripts/API/ATF_Show.lua, test_scripts/API/ATF_ShowConstantTBT.lua, test_scripts/API/ATF_UpdateTurnList.lua, test_scripts/API/SubMenuIcon/003_menuIcon_selected_not_existing_file.lua, test_scripts/API/Transfer_RPC_with_invalid_image/001_AddCommand.lua, test_scripts/API/Transfer_RPC_with_invalid_image/002_AddSubMenu.lua, test_scripts/API/Transfer_RPC_with_invalid_image/003_Alert.lua, test_scripts/API/Transfer_RPC_with_invalid_image/004_CreateInteractionChoiceSet.lua, test_scripts/API/Transfer_RPC_with_invalid_image/005_PerfomInteraction.lua, test_scripts/API/Transfer_RPC_with_invalid_image/006_ScrollableMessage.lua, test_scripts/API/Transfer_RPC_with_invalid_image/007_Show.lua, test_scripts/API/Transfer_RPC_with_invalid_image/008_ShowConstantTBT.lua, test_scripts/API/Transfer_RPC_with_invalid_image/009_SendLocation.lua, test_scripts/API/Transfer_RPC_with_invalid_image/010_SetAppIcon.lua, test_scripts/API/Transfer_RPC_with_invalid_image/011_UpdateTurnList.lua, test_scripts/API/Transfer_RPC_with_invalid_image/012_AlertManeuver.lua, test_scripts/API/Transfer_RPC_with_invalid_image/013_GetWayPoints.lua, test_scripts/API/Transfer_RPC_with_invalid_image/014_OnWayPointChange.lua, test_scripts/API/Transfer_RPC_with_invalid_image/015_SetGlobalProperties.lua, test_scripts/API/Transfer_RPC_with_invalid_image/common.lua, test_sets/SDL_0042_Transfer_RPC_with_Invalid_Image.txt
ATF Test Scripts to check invalid image RPC transfer
This PR is ready for review.
Scripts for 'RPC’s with invalid image reference parameters to the HMI' feature.
[Develop branch](https://github.com/smartdevicelink/sdl_atf_test_scripts/tree/develop)
=> SDL_0042 tests for image not available in storage

test_scripts/Security/DTLS/common.lua, test_scripts/Security/GetSystemTime/common.lua
Updates for ATF Test Scripts
Update DTLS and GetSystemTime security test scripts for EXTERNAL_PROPRIETARY flow of SDL
=> Adopt DTLS and GetSystemTime scripts to EXTERNAL_PROPRIETARY flow

test_scripts/Policies/Policy_Table_Update/122_ATF_PTU_NotSuccessful_AppID_ListedPT_NewIgnCycle.lua
There is an additional check is required in script according to issue [#2489](https://github.com/smartdevicelink/sdl_core/issues/2489)
=> Add additional check into policy script 122

test_scripts/Smoke/API/020_SetDisplayLayout_PositiveCase_SUCCESS.lua
Tests for [SDL-0151](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0151-imagefieldname-for-secondary-image.md)
=> Add `secondaryGraphic` to SetDisplayLayout smoke test

test_scripts/API/VehicleData/GetVehicleData/002_RPC_parameter_DISALLOWED_by_policies_flow.lua, test_scripts/API/VehicleData/SubscribeVehicleData/002_RPC_parameter_DISALLOWED_by_policies_flow.lua, test_scripts/API/VehicleData/UnsubscribeVehicleData/004_RPC_parameter_disallowed_by_policies_Result_DISALLOWED_flow.lua
The PTU still included these params in the VehicleInfo-3 functional group so policies was not disallowing the RPC. This updates the ptu function so that the parameters are removed from Emergency-1 and VehicleInfo-3
=> Correctly update all functional groups for vehicle data disallowed

test_scripts/Defects/5_0/1866_SDL_does_not_respond_to_HMI_request_with_missed_mandatory_params.lua
Script for reproducing issue [SDL does not respond to HMI request with missed mandatory params](https://github.com/SmartDeviceLink/sdl_core/issues/1866)
=> Script for reproducing issue 1866

test_scripts/Defects/4_6/1868_SDL_does_not_respond_to_HMI_request_with_empty_string_parameter.lua, test_scripts/Defects/5_0/1868_SDL_does_not_respond_to_HMI_request_with_empty_string_parameter.lua
Script for reproducing issue [SDL does not respond to HMI request with empty string parameter](https://github.com/smartdevicelink/sdl_core/issues/1868)
=> Script for reproducing issue 1868

test_scripts/Defects/5_0/1867_SDL_does_not_respond_to_HMI_request_with_wrong_type_of_params.lua
Script for reproducing issue [SDL does not respond to HMI request with wrong type of params](https://github.com/smartdevicelink/sdl_core/issues/1867)
=> Script for reproducing issue 1867

test_scripts/Policies/Validation_of_PolicyTables/227_ATF_usage_and_error_counts_update_count_sync_out_of_memory.lua, test_scripts/Policies/Validation_of_PolicyTables/264_ATF_pt_snapshot_creation_rule.lua
Deletes the policy table at the end of the test script. Without this, tests following these tests in the external proprietary test set will fail because of the previous policy state.
=> Fix external proprietary tests' shutdown and cleanup 

test_scripts/Policies/build_options/097_ATF_PTU_Cycleing_Through_The_URLs_During_Retry_Sequence_HTTP.lua
There are following improvements in script:
1) Added app1 activation => this allows to perform new PTU cycle only through this app
2) Validation result function corrected due to the fact that array of available URLs could be unsorted (order of elements is changed from run to run)
=> Correct validation of result on URLs cycling during PTU retry sequence

test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/016_Change_audio_source_from_MOBILE_APP_keepContext_true_LIMITED.lua
Originally in [0150-video-streaming-state](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0150-video-streaming-state.md) there was a statement that HMI level has to be changed from LIMITED to BACKGROUND in case both audio and video streaming states set to NOT_STREAMABLE.
However this requirement does not describe the case when context should be kept and HMI level should not be changed.
In https://github.com/smartdevicelink/sdl_core/pull/2607 besides other fixes there was introduced change that LIMITED level should be kept if `SetInteriorVehicleData` was sent with `keepContext=true`
By this change SDL behavior became the same for FULL and LIMITED levels.
So the script needs to be updated accordingly.
=> Correct expected result for LIMITED and keepContext=true

test_scripts/Security/SSLHandshakeFlow/common.lua, user_modules/sequences/actions.lua
Fix for [#2025](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2025)
Policy Table Update sequence is used in a lot of test scripts. However this procedure could fail at the very first start due to missing snapshot etc.
This PR implement possibility to create policy table update file from either snapshot or from SDL's preloaded file.
* Remove `ptuTable` local variable from `actions` module
* Remove unnecessary function `setPTUTable()`
=> Make safeguard in getPTUFromPTS

test_sets/SDL5_0/mobile_projection_2.txt, test_sets/SDL5_0/mobile_projection_2_smoke.txt
By current PR failed test scripts from Mobile Projection are excluded from test sets (marked as skipped with link to appropriate issue)
=> Exclude failed test scripts from Mobile Projection test sets and add link to GitHub issue

test_scripts/SDL5_0/MobileVersioning/PlayPauseButton/002_play_pause_v4_invalid_data.lua, test_scripts/SDL5_0/MobileVersioning/VersionNegotiation/001_register_legacy_app.lua
Update min negotiated rpc version to 4.5.1.
[Associated core pr](https://github.com/smartdevicelink/sdl_core/pull/2673)
=> Update min rpc patch version

test_scripts/RC/commonRC.lua
Message included hd radio related information, therefore I believe that the hdRadioEnable parameter is meant to be set to true.
=> Make HD radio enable true

test_scripts/Defects/5_0/1030_API_SDL_sends_OnAppInterfaceUnregistered(DRIVER_DISTRACTION_VIOLATION)_to_app_when_receives_OnExitApplication(DRIVER_DISTRACTION_VIOLATION)_from_HMI.lua
**Summary:**
ATF script to check that **_SDL Core_** don't send _OnAppUnregistered_ notification to **_HMI_** when recieved _OnExitApplication_ notification from **_HMI_**.
**Issue:**
[Defect #1030](https://github.com/smartdevicelink/sdl_core/issues/1030)
[FORDTCN-1934](https://adc.luxoft.com/jira/browse/FORDTCN-1934)
This PR is **ready** for review
=> ATF script for defect 1030

test_scripts/Policies/App_Permissions/002_ATF_HP_OnPermissionsChange_With_Assigned_Policy_After_App_Registration.lua, test_scripts/Policies/Policy_Table_Update/144_ATF_PTU_validation_failure.lua, test_scripts/Policies/Validation_of_PolicyTables/265_ATF_pt_snapshot_storage_on_file_system.lua, test_scripts/Policies/Validation_of_PolicyTables/282_ATF_PT_Exchanged_X_Days_After_Epoch_In_PTS.lua, test_scripts/Policies/user_consent_of_Policies/188_ATF_HP_Device_Data_Section_Validation.lua
Some existing tests scripts on Policies were failed randomly.
Current PR fixes instability in these tests.
=> Stabilize test scripts on Policies

test_scripts/Smoke/API/022_SubscribeButton_PositiveCase_SUCCESS.lua, test_scripts/Smoke/API/023_UnsubscribeButton_PositiveCase_SUCCESS.lua, test_scripts/Smoke/API/042_SubscribeButton_Non_Media_PositiveCase_SUCCESS.lua, test_scripts/Smoke/API/043_UnsubscribeButton_Non_Media_PositiveCase_SUCCESS.lua, user_modules/hmi_values.lua
This is **draft** of the scripts.
Updated Subscribe notifications for ButtonSubscribe requests
develop
=> Update in smoke tests regarding buttonSubscription response from HMI

test_scripts/API/VehicleData/GpsShiftSupport/001_GetVehicleData_gps_shift.lua, test_scripts/API/VehicleData/GpsShiftSupport/002_GetVehicleData_gps_without_shift.lua, test_scripts/API/VehicleData/GpsShiftSupport/002_OnVehicleData_gps_shift.lua, test_scripts/API/VehicleData/GpsShiftSupport/003_OnVehicleData_gps_shift.lua, test_scripts/API/VehicleData/GpsShiftSupport/004_OnVehicleData_gps_without_shift.lua, test_scripts/API/VehicleData/GpsShiftSupport/005_GetInteriorVehicleData_stationLocation_shift.lua, test_scripts/API/VehicleData/GpsShiftSupport/006_GetInteriorVehicleData_stationLocation_without_shift.lua, test_scripts/API/VehicleData/GpsShiftSupport/007_OnInteriorVehicleData_stationLocation_shift.lua, test_scripts/API/VehicleData/GpsShiftSupport/008_OnInteriorVehicleData_stationLocation_without_shift.lua, test_scripts/API/VehicleData/GpsShiftSupport/commonGpsShift.lua, test_sets/gps_shift_support.txt
ATF Test Scripts to check [#2639](https://github.com/smartdevicelink/sdl_core/issues/2639)
Adding-GPS-Shift-support
=> [WIP] GPS Shift support

test_scripts/CloudAppRPCs/010_get_icon_url.lua, test_scripts/CloudAppRPCs/commonCloudAppRPCs.lua
Add success case for onSystemRequest ICON Url. Tests that the request is created when a icon url is added to the PT. Also tests the SystemRequest from mobile that the image is received and a new onHMIStatus is updated.
=> Test for onsystemRequest ICON_URL

test_scripts/AppServices/GetAppServiceData/011_M2M_GENERIC_ERROR.lua, test_scripts/AppServices/GetAppServiceData/012_M2H_GENERIC_ERROR.lua, test_scripts/AppServices/GetAppServiceData/013_H2M_GENERIC_ERROR.lua, test_scripts/AppServices/PerformAppServiceInteraction/003_H2M_success_flow.lua, test_scripts/AppServices/PerformAppServiceInteraction/010_H2M_Timeout.lua, test_scripts/AppServices/PerformAppServiceInteraction/011_M2M_GENERIC_ERROR.lua, test_scripts/AppServices/PerformAppServiceInteraction/012_M2H_GENERIC_ERROR.lua, test_scripts/AppServices/PerformAppServiceInteraction/013_H2M_GENERIC_ERROR.lua
ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/issues/2866
Adds tests for GENERIC_ERROR timeout when app service provider doesn't respond
`develop` branch
* Adds tests for GENERIC_ERROR timeout when app service provider doesn't respond
=> Add GENERIC_ERROR timeout tests for app service RPCs

test_sets/app_services.txt
Add missing App Services tests to test set
`develop` branch
* Add missing App Services tests to test set
=> Add GENERIC_ERROR tests to app services test set

test_scripts/Policies/Validation_of_PolicyTables/310_ATF_Check_count_of_removals_for_bad_behavior_REQUEST_WHILE_IN_NONE_HMI_LEVEL.lua, test_scripts/Policies/user_consent_of_Policies/200_ATF_Data_consent_prompt.lua
Adds cleanup steps to the  EXTERNAL_PROPRIETARY test scripts which were corrupting the Preloaded policy table and SmartDeviceLink.ini file
=> Added cleanup steps for test scripts which corrupt the PT/INI file

test_scripts/API/ATF_GetSystemCapability.lua, test_scripts/Smoke/API/048_GetSystemCapabilityRequest_SUCCESS.lua, test_sets/smoke_tests.txt
- Add getSystemCapability test to smoke test set.
- Add video streaming capabilities to the getSystemCapability test.
Develop/Master
=> Add getSystemCapability test to smoke test set

test_scripts/API/VehicleData/GpsShiftSupport/001_GetVehicleData_gps_shift.lua, test_scripts/API/VehicleData/GpsShiftSupport/002_GetVehicleData_gps_without_shift.lua, test_scripts/API/VehicleData/GpsShiftSupport/003_OnVehicleData_gps_shift.lua, test_scripts/API/VehicleData/GpsShiftSupport/004_OnVehicleData_gps_without_shift.lua, test_scripts/API/VehicleData/GpsShiftSupport/005_GetInteriorVehicleData_stationLocation_shift.lua, test_scripts/API/VehicleData/GpsShiftSupport/006_GetInteriorVehicleData_stationLocation_without_shift.lua, test_scripts/API/VehicleData/GpsShiftSupport/007_OnInteriorVehicleData_stationLocation_shift.lua, test_scripts/API/VehicleData/GpsShiftSupport/008_OnInteriorVehicleData_stationLocation_without_shift.lua, test_scripts/API/VehicleData/GpsShiftSupport/009_GetInteriorVehicleData_stationLocation_shift_after_subscription.lua, test_scripts/API/VehicleData/GpsShiftSupport/commonGpsShift.lua, test_sets/gps_shift_support.txt
ATF Test Scripts to check #[2639](https://github.com/smartdevicelink/sdl_core/issues/2639)
Scripts for "Adding GPS Shift support" feature
=> Feature/GPS Shift support

test_scripts/API/CloseApplication/001_Success_flow.lua, test_scripts/API/CloseApplication/002_HMI_error_response.lua, test_scripts/API/CloseApplication/commonCloseApplication.lua, test_scripts/Policies/Related_HMI_API/176_ATF_OnAllowSDLFunctionality_allowed_false_with_device.lua, test_scripts/Policies/appID_Management/043_ATF_HMI_Status_Appid_Gets_Null_In_Case_Of_PTU.lua, test_scripts/Policies/appID_Management/044_ATF_HMI_Status_Value_Of_AppId_In_PT_Is_Null.lua, test_scripts/Policies/user_consent_of_Policies/207_ATF_HMILevel_before_data_consented.lua, test_sets/CloseApplication_RPC.txt, test_sets/smoke_tests.txt
ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/pull/2948
Add base CloseApplication RPC tests
develop
* Add base CloseApplication RPC tests
=> Add CloseApplication RPC tests

test_scripts/API/Expanded_proprietary_data_exchange/commonDataExchange.lua
There is some instability in scripts for Proprietary data exchange feature
Current PR fix this 
develop
Remove expectation on `OnStatusUpdate` notification. 
In `develop` branch such expectation doesn't exist
So current PR is just use develop version of `policyTableUpdate()` function
=> Make scripts for proprietary data exchange stable

test_scripts/API/GetPolicyConfigurationData/001_GetPolicyConfigurationData_success.lua, test_scripts/API/GetPolicyConfigurationData/002_GetPolicyConfigurationData_incorrect_params.lua, test_scripts/API/GetPolicyConfigurationData/commonGetPolicyConfigurationData.lua, test_scripts/API/VehicleData/GenericNetworkSignalData/054_GetPolicyConfigurationData_processing.lua, test_sets/get_policy_configuration_data.txt, test_sets/smoke_tests.txt
Extension of test coverage for feature "Read Generic Network Signal data" 
- There is fixed test script "054_GetPolicyConfigurationData_processing.lua"
- There are created test scripts to check new GetPolicyConfigurationData RPC 
- [X ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)
=> [Read generic network signal data] Extension of test coverage

test_scripts/Smoke/API/049_SetMenuLayout_SUCCESS.lua, test_scripts/Smoke/API/050_SetMenuLayout_unspported_WARNINGS.lua, test_scripts/Smoke/API/050_SetMenuLayout_unsupported_WARNINGS.lua, test_sets/smoke_tests.txt
ATF Test Scripts to check [#2925](https://github.com/smartdevicelink/sdl_core/issues/2925)
Add the ability to request a tiled menu through SetGlobalProperties or AddSubMenu RPCs.
develop
* Adds new parameter menuLayout to SetGlobalProperties RPC.
* Adds new parameter menuLayout to AddSubMenu RPC.
* Adds new parameter menuLayoutsAvailable to HMI Capabilities
=> add tests for using new menuLayout parameter

user_modules/sequences/remote_control.lua
Updates for ATF Test Scripts that checks RC related functionality that have been merged in scope of **[SDL 0204- Support running the same app from multiple devices at the same time feature](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2202 )** - 
And need to be updated in scope of **[SDL 0221-Remote Control - Allow Multiple Modules per Module Type feature](https://github.com/smartdevicelink/sdl_core/issues/2919)** 
**[these changes will be merged to [#2226](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2226)]**
Update existing scripts according multiple modules feature changes
https://github.com/smartdevicelink/sdl_atf/tree/develop
=> fixup! Add remote_control module as new core module of user_modules

test_scripts/API/VehicleData/GenericNetworkSignalData/007_Applying_PTU_with_updated_VDitems.lua, test_scripts/API/VehicleData/GenericNetworkSignalData/008_SubscribeVehicleData_cache_with_VDitems_one_app.lua, test_scripts/API/VehicleData/GenericNetworkSignalData/009_UnsubscribeVehicleData_cache_with_VDitems_one_app.lua, test_scripts/API/VehicleData/GenericNetworkSignalData/010_Subscription_resumption_for_VDitems_unexpected_disconnect.lua, test_scripts/API/VehicleData/GenericNetworkSignalData/011_Subscription_resumption_for_VDitems_ign_off.lua, test_scripts/API/VehicleData/GenericNetworkSignalData/029_SubscribeVehicleData_cache_with_VDitems_for_different_data_two_apps.lua, test_scripts/API/VehicleData/GenericNetworkSignalData/031_UnsubscribeVehicleData_cache_with_VDitems_for_different_data_two_apps.lua, test_scripts/API/VehicleData/GenericNetworkSignalData/032_Subscription_resumption_for_VDitems_2_apps_unexpected_disconnect.lua, test_scripts/API/VehicleData/GenericNetworkSignalData/033_Subscription_resumption_for_VDitems_2_apps_ign_off.lua, test_scripts/API/VehicleData/GenericNetworkSignalData/040_Get_Subscribe_Unsubscribe_request_data_not_match_to_response_data.lua, test_scripts/API/VehicleData/GenericNetworkSignalData/051_VD_request_with_false_value.lua, test_scripts/API/VehicleData/GenericNetworkSignalData/commonGenericNetSignalData.lua
Update of scripts for feature "Read Generic Network Signal data" according new revision of proposal [Read Generic Network Signal Data Clarification](https://github.com/smartdevicelink/sdl_evolution/pull/802)
- Scripts were updated with adding with non mandatory parameter `oemCustomDataType`  into `VehicleDataResult` structure
=> Read Generic Network Signal data feature scripts update according new revision

user_modules/sequences/actions.lua
Fixed issue [#2231](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2231)
Improve app activation speed
develop
* Activation speed is improved significantly in case of single app
In case of a few apps delay is reduced to 500ms
* Removed expectation on `audioStreamingState`
=> Improve app activation speed

user_modules/shared_testcases/testCasesForPolicyTableSnapshot.lua
ATF Test Scripts to check https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2215
Update for Policies scripts which verifies Policy Table Snapshot data consistency.
https://github.com/smartdevicelink/sdl_atf/tree/develop
New `lock_screen_dismissal_enabled` is added to `verify_PTS()` function
=> Add 'lock_screen_dismissal_enabled' to the list of available data in PTS

test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/016_RADIO_GPSdata_in_HMI_response.lua
ATF Test Scripts to check https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2216
Update for existing RC script with cutting of redundant `gpsData` from `stationLocation` according to changes in requirements within [[SDL 0199]-Adding-GPS-Shift-support](https://github.com/smartdevicelink/sdl_core/issues/2639) feature
https://github.com/smartdevicelink/sdl_atf/tree/develop
=> Update for RC script with cutting of redundant gpsData from stationLocation

test_scripts/API/Expanded_proprietary_data_exchange/commonDataExchange.lua, test_scripts/API/ServiceStatusUpdateToHMI/common.lua, test_scripts/API/VehicleData/DOP/common.lua, test_scripts/API/VehicleData/GpsShiftSupport/commonGpsShift.lua, test_scripts/AppServices/RPCPassThrough/008_PTU_allow_unknown_rpc_passthrough.lua, test_scripts/AppServices/commonAppServices.lua, test_scripts/CloudAppRPCs/005_SetCloudAppProperties_Success.lua, test_scripts/CloudAppRPCs/007_SetCloudAppProperties_InitNewCloudApp.lua, test_scripts/CloudAppRPCs/010_get_icon_url.lua, test_scripts/CloudAppRPCs/commonCloudAppRPCs.lua, test_scripts/SDL5_0/FullAppID/common.lua, test_scripts/Security/SSLHandshakeFlow/common.lua, test_scripts/TheSameApp/Security/001_Send_RPC_or_encrypted_RPC_in_protected_unprotected_mode_apps_with_same_appName_appID_from_2_devices.lua, test_scripts/TheSameApp/Security/002_Send_RPC_or_encrypted_RPC_in_protected_unprotected_mode_apps_with_same_appName_diff_appID_from_2_devices.lua, test_scripts/TheSameApp/Security/003_Send_RPC_or_encrypted_RPC_in_protected_unprotected_mode_apps_with_diff_appName_same_appID_from_2_devices.lua, test_scripts/TheSameApp/commonTheSameApp.lua, user_modules/sequences/actions.lua
Fixed issue [#2229](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2229)
Update various common modules in order to support SDL's `HTTP` and `EXTERNAL_PROPRIETARY` policy modes
The main idea is to make possible to run ATF test scripts on all existing SDL policy modes: `PROPRIETARY`, `EXTERNAL_PROPRIETARY` and `HTTP`
develop
- add support of `HTTP`mode to `actions.policyTableUpdate()`
- create new `actions.isPTUStarted()` function
- add policy mode configuration option to some scripts to prevent running of them on not applicable mode (test will be skipped)
- remove `user_consent_prompt` for some scripts related to VehicleData.
- add delay after `BC.DecryptCertificate` in order to SDL has time to store certificates on a file system (this fixed instability in security scripts …
=> Update test scripts to support HTTP and EXT SDL's policy modes

test_scripts/SDL5_0/Transfer_RPC_with_invalid_image/005_PerfomInteraction.lua
ATF Test Scripts to check #[2974]( https://github.com/smartdevicelink/sdl_core/issues/2974)
According to HMI specification, result structure has no any messages and SDL doesn't resent any 'info' messages to the mobile, this is why I removed 'info' validation 
https://github.com/smartdevicelink/sdl_atf/tree/develop(d6c2138)
=> Remove undefined info param from response validation

test_scripts/API/VehicleData/GetVehicleData/001_Success_flow.lua, test_scripts/API/VehicleData/GetVehicleData/002_RPC_parameter_DISALLOWED_by_policies_flow.lua, test_scripts/API/VehicleData/GetVehicleData/003_GetVD_gps_mandatory_parameters.lua, test_scripts/API/VehicleData/GetVehicleData/004_Success_deviceStatus_primaryAudioSource.lua, test_scripts/API/VehicleData/OnVehicleData/001_Success_flow.lua, test_scripts/API/VehicleData/OnVehicleData/002_NotificationForUnsubsribedParameter_Ignored_flow.lua, test_scripts/API/VehicleData/OnVehicleData/003_NotificationParameterDisallowedByPolicies_Ignored_flow.lua, test_scripts/API/VehicleData/OnVehicleData/004_OnVD_gps_mandatory_parameters.lua, test_scripts/API/VehicleData/OnVehicleData/005_Success_flow_deviceStatus_primaryAudioSource.lua, test_scripts/API/VehicleData/SubscribeVehicleData/001_Success_flow.lua, test_scripts/API/VehicleData/SubscribeVehicleData/002_RPC_parameter_DISALLOWED_by_policies_flow.lua, test_scripts/API/VehicleData/SubscribeVehicleData/003_RPC_parameter_already_subscribed_Result_IGNORED_flow.lua, test_scripts/API/VehicleData/UnsubscribeVehicleData/001_Success_flow.lua, test_scripts/API/VehicleData/UnsubscribeVehicleData/002_RPC_parameter_not_yet_subscribed_IGNORED_flow.lua, test_scripts/API/VehicleData/UnsubscribeVehicleData/003_RPC_parameter_already_unsubscribed_Result_IGNORED_flow.lua, test_scripts/API/VehicleData/UnsubscribeVehicleData/004_RPC_parameter_disallowed_by_policies_Result_DISALLOWED_flow.lua, test_scripts/API/VehicleData/commonVehicleData.lua, test_sets/SDL5_0/vehicle_data.txt, test_sets/vehicle_data.txt
Fixed issue [#2243](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2243)
Rework VehicleData scripts
develop
- utilized functions from `actions` module
- added possibility to run scripts on all SDL policy flows
- included in test set previously disabled tests since such functionality is implemented in scope of `Read Generic Network Signal Data` proposal
- fixed expected result in [SubscribeVehicleData/003_RPC_parameter_already_subscribed_Result_IGNORED_flow](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/API/VehicleData/SubscribeVehicleData/003_RPC_parameter_already_subscribed_Result_IGNORED_flow.lua)
=> Rework VehicleData scripts

test_scripts/Policies/App_Permissions/002_ATF_HP_OnPermissionsChange_With_Assigned_Policy_After_App_Registration.lua, test_scripts/Policies/Related_HMI_API/186_ATF_OnPolicyUpdate_initiation_of_PTU.lua, test_scripts/Policies/Validation_of_PolicyTables/227_ATF_usage_and_error_counts_update_count_sync_out_of_memory.lua, test_scripts/Policies/Validation_of_PolicyTables/228_ATF_usage_and_error_counts_update_count_of_sync_reboots.lua, test_scripts/Policies/Validation_of_PolicyTables/229_ATF_usage_and_error_counts_update_count_of_iap_buffer_full.lua, test_scripts/Policies/Validation_of_PolicyTables/230_ATF_usage_and_error_counts_update_minutes_in_hmi_none.lua, test_scripts/Policies/Validation_of_PolicyTables/231_ATF_usage_and_error_counts_update_minutes_in_hmi_limited.lua, test_scripts/Policies/Validation_of_PolicyTables/232_ATF_usage_and_error_counts_update_minutes_in_hmi_full.lua, test_scripts/Policies/Validation_of_PolicyTables/233_ATF_usage_and_error_counts_update_minutes_in_hmi_background.lua, test_scripts/Policies/user_consent_of_Policies/221_ATF_Factory_reset.lua, test_scripts/Smoke/Policies/001_PTU_all_flows.lua, test_scripts/Smoke/commonSmoke.lua, user_modules/sequences/actions.lua
Fixed issue [#2259](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2259)
Improve stability of policy scripts - additional updates
develop
- in `registerApp()` function of `actions` module added expectation on `OnSystemRequest(LOCK_SCREEN_ICON_URL)` message. It will make PTU sequence more stable since another  `OnSystemRequest` is also used in this sequence
- in `001_PTU_all_flows.lua` added delay for `allowSDL` as in `action` module
- in `002_ATF_HP_OnPermissionsChange_With_Assigned_Policy_After_App_Registration.lua` message to HMI is removed from ordering verification since Mobile and HMI connections are not depends on each other
- in `186` delay is added before postconditions 
- in `227`, `228` delay is added when system messages are …
=> Improve stability of policy scripts - additional updates

test_scripts/Smoke/Policies/002_PTU_all_flows_Protected_Mode.lua, test_sets/smoke_tests.txt, user_modules/sequences/security.lua
ATF Test Scripts to check [#2922](https://github.com/smartdevicelink/sdl_core/issues/2922)
There are following updates:
- Added new script to check PTU in protected mode.
Supported all SDL policy flows.
develop
=> Add script to check PTU in protected mode

test_scripts/Smoke/API/049_SetMenuLayout_SUCCESS.lua, test_scripts/Smoke/API/050_SetMenuLayout_unsupported_WARNINGS.lua
ATF Test Scripts to check #2925 
#2925 was closed with the expectation that this change would be made as part of the fix for #2918 
`MenuLayoutsAvailable` is no longer a member of HMI capabilities and is not loaded by HMI values but instead by the `BasicCommunication.OnSystemCapabilityUpdated`
develop
* Updated tests to work with new core changes in [#3043](https://github.com/smartdevicelink/sdl_core/pull/3043)
=> move MenuLayoutsAvailable to WindowCapability

test_scripts/RC/MultipleModules/commonRCMulModules.lua, user_modules/sequences/remote_control.lua
Fix ATF Test Scripts for modified behavior in core fix [#3050](https://github.com/smartdevicelink/sdl_core/pull/3050)
Core fix [#3050](https://github.com/smartdevicelink/sdl_core/pull/3050) adds behavior to filter the moduleIds in the `GetInteriorVehicleDataConsent` request forwarded to the HMI for consent.
Currently if an app sends `GetInteriorVehicleDataConsent` with two moduleIds(one free and one taken by another user) core would ask the HMI for consent for both moduleIds, even though one of the modules is free. 
After this core fix, the moduleIds sent to the HMI will be filtered based on whether or not core can automatically decide what the consent should be for a particular moduleId. (For example in the test case …
=> Add filtering moduleIds for GetInteriorVehicleDataConsent requests to the HMI

test_scripts/TheSameApp/Resumption/001_Resumption_IGNITION_OFF_same_app_on_different_devices.lua, test_scripts/TheSameApp/Resumption/002_Resumption_unexpected_disconnect_same_app_on_different_devices.lua
ATF Test Scripts to check #[2266](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2266)
Added delay between consecutive `AddCommand` and `AddSubMenu` requests in order to SDL be able to send `OnHashChange` properly.
develop
=> Make TheSameApp scripts stable by adding delay between requests

test_scripts/Smoke/API/049_SetMenuLayout_SUCCESS.lua, test_scripts/Smoke/API/050_SetMenuLayout_unsupported_WARNINGS.lua
ATF Test Scripts to check #[2270](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2270)
Implemented ordering of messages: `SetGlobalProperties` and `AddSubMenu` are send only after receiving of `OnSystemCapabilityUpdated`, 
develop
=> Improve stability of API/049 script from smoke

test_scripts/API/VehicleData/GenericNetworkSignalData/045_PTU_unknown_types_of_parameters.lua, test_sets/read_generic_network_signal_data.txt
ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/pull/3062
Update failing test after revisions to the Generic Network Signal Data proposal, allowing for unknown enum data types in a PTU
develop
* Modify PTU validation test to handle unknown enum data types
=> Update test to accept PTU with invalid params and pass rpc request tests

test_scripts/MobileProjection/Phase2/005_audioStreamingState_111-118.lua, test_scripts/MobileProjection/Phase2/smoke/005_audioStreamingState_111-118.lua, test_scripts/Policies/App_Permissions/022_ATF_No_Permission_Notification_To_HMI_In_First_App_Registration.lua, test_scripts/Policies/build_options/072_ATF_PTU_PM_Sets_Status_UPDATE_NEEDED_HTTP.lua
ATF Test Scripts to check #[2276](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2276)
- Scripts `005_audioStreamingState_111-118` may abort to the following reason:
Function `StopStreaming` was defined in callback of `OnHMIStatus`.
In this case if app stops streaming SDL sends 2nd `OnHMIStatus` message with `audioStreamingState=AUDIBLE` which is correct.
However this may lead to 2nd invocation of the same callback with `StopStreaming` function and ATF in this case can't stop streaming which is already stopped.
Fix is to move `StopStreaming` function to a separate step.
- Script `022_ATF_No_Permission_Notification_To_HMI_In_First_App_Registration` may fail due to the reason that `BC.OnAppRegistered` may be sent in a different order than …
=> Improve stability of scripts - additional updates

test_scripts/Policies/user_consent_of_Policies/214_ATF_User_consent_prompt_persists.lua
Update due to changes introduced by fix for [#1880](https://github.com/smartdevicelink/sdl_core/issues/1880)
According to [#1880](https://github.com/smartdevicelink/sdl_core/issues/1880) timeout is calculated by the formulae:
```
DefaultTimeout(from .ini file) + RPCs_internal_timeout
```
Fix is to increase default timeout for Alert response
develop
=> Increase timeout for Alert response

test_scripts/TheSameApp/commonTheSameApp.lua
ATF Test Scripts to fix #[2278](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2284)
During script execution ATF checks SDL status every 400ms in `CheckStatus()` function in `modules/testbase.lua` module.
In case if SDL process is stopped ATF will abort script and report corresponding status.
Fix is to let ATF know that SDL could be in stopped state by setting `config.ExitOnCrash` parameter and to continue script execution.
develop
=> Make IgnitionOff function more stable

test_scripts/iAP2TransportSwitch/common.lua
Currently the iAP2TransportSwitch tests corrupt the `smartDeviceLink.ini` since the common file doesn't have a backup step for the INI file
This PR adds backup and restore steps for the INI file in `iAP2TransportSwitch/common.lua`
=> Fix/iAP tests corrupting INI file

test_scripts/SDL5_0/Transfer_RPC_with_invalid_image/005_PerfomInteraction.lua, test_scripts/Smoke/API/012_PerfomInteraction_PositiveCase_SUCCESS.lua, test_scripts/Smoke/API/039_PerfomInteraction_Non_Media_PositiveCase_SUCCESS.lua, test_scripts/WidgetSupport/OnHMIStatus/007_SystemContext_from_MAIN_to_VRSESSION_and_HMI_OBSCURED_for_the_main_and_a_widget_windows.lua
ATF Test Scripts to check [#2830](https://github.com/smartdevicelink/sdl_core/issues/2830) & [#3112](https://github.com/smartdevicelink/sdl_core/issues/3112)
Added cases for PerformInteraction response handling in VR only/BOTH modes
Updated existing tests.
develop
=> Fix sdl sending of PerformInteraction unsuccess response to mobile in case choice id selected via VR

test_scripts/Defects/6_1/3142_01_Absence_of_misplaced_OnVideoDataStreaming.lua, test_scripts/Defects/6_1/3142_02_Absence_of_misplaced_OnAudioDataStreaming.lua
Fixed issue #2345
Existing expectation are modified to conform the logic described in [#3123](https://github.com/smartdevicelink/sdl_core/issues/3123)
develop
In case if 1st app is currently streaming and 2nd app is activated and starts streaming the following messages are sent to HMI:
- `Navi.StopStream` for App_1
- `Navi.OnVideoDataStreaming(false)`
- `Navi.StartStream` for App_2
- `Navi.OnVideoDataStreaming(true)`
=> Align scripts for 3142 with fix for 3123

test_scripts/Defects/5_0/974_updateDeviceList_after_closingConnection.lua, test_scripts/Defects/6_1/974_updateDeviceList_after_closingConnection.lua, test_sets/Defects/6_1/974.txt
ATF Test Scripts to check #[974](https://github.com/smartdevicelink/sdl_core/issues/974)
ATF test script to verify the issue.
[develop](https://github.com/smartdevicelink/sdl_atf/commit/6ed5c5c7a55fa05b015de3db7c04e13b91ace01a)
=> Script for issue 974

test_scripts/Policies/build_options/052_ATF_PTU_Trigger_IGN_Cycles_HTTP.lua, test_scripts/Policies/build_options/053_ATF_Policy_Table_Update_Trigger_After_N_Days_HTTP.lua, test_scripts/Policies/build_options/078_ATF_PTU_HMI_Level_Affected_Apps_FULL_LIMITED_HTTP.lua, test_scripts/Policies/build_options/101_ATF_SDL_Build_EXTENDED_POLICY_HTTP.lua, test_scripts/Policies/build_options/118_ATF_Request_PTU_Trigger_App_Excluded_PT_HTTP.lua
Fixed issue #2349
Some policy scripts expect to receive `OnSystemRequest(LOCK_SCREEN_ICON_URL)` even if no endpoint
develop
In case if no endpoint expectation on `OnSystemRequest(LOCK_SCREEN_ICON_URL)` is removed
=> Align scripts with fix for 2932

test_scripts/Smoke/commonSmoke.lua, user_modules/connecttest_TTS_Isready.lua, user_modules/connecttest_VR_Isready.lua, user_modules/connecttest_initHMI.lua, user_modules/connecttest_resumption.lua, user_modules/dummy_connecttest.lua, user_modules/sequences/actions.lua
Fix [#193](https://github.com/smartdevicelink/sdl_atf/issues/193)
Сoncomitant changes in common modules related to the fix in ATF.
ATF from PR https://github.com/smartdevicelink/sdl_atf/pull/194
* removed parameters in getDefaultAdapter() in mobile_adapter_controller module
* added selection of the mobile host depends on connection type (local or remote)
=> Fix Remote Connection issue

test_scripts/RC/CLIMATE_RADIO/Capabilities/008_Default_capabilities_if_HMI_doesnt_respond_to_RC_IsReady_and_doesnt_respond_to_RC_GetCapabilities_RADIO.lua, test_scripts/RC/CLIMATE_RADIO/Capabilities/009_Default_capabilities_if_HMI_doesnt_respond_to_RC_IsReady_and_doesnt_respond_to_RC_GetCapabilities_CLIMATE.lua, test_scripts/RC/CLIMATE_RADIO/Capabilities/014_Default_capabilities_if_HMI_doesnt_respond_to_RC_IsReady_and_doesnt_respond_to_RC_GetCapabilities.lua, test_scripts/RC/commonRC.lua
This PR is **[not ready]** for review.
There are following updates:
Update according to changes in hmi_capabilities.json for RC 
Add delay to avoid holding for RAI sequence due to the "DefaultTimeout" for RC.GetCapabilities response 
[ATF version to use]
=> Fix RC scripts within persisting hmi cpabilities 

test_scripts/Defects/6_1/3267_1_RAI_OnSystemRequest_LOCK_SCREEN_ICON_URL.lua, user_modules/sequences/actions.lua
Update fixed an issue with `HeartBeat` which is still continue works when application has been unregistered and session has removed.
develop
- Replace `deleteSession()` by `closeSession()` in app.unRegister() in `actions` module
Function `closeSession()` invokes both `deleteSession()` and `session:Stop()` which is also invokes `StopHeartbeat()`
- Remove delay in script for `3267` that was added previously in [#2378](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2378) 
This delay is not required anymore
=> Add closeSession to unregisterApp

test_scripts/API/VehicleData/GenericNetworkSignalData/036_4_Subscribtion_after_removing_VD_from_permissions_from_1_app_2_apps.lua, test_scripts/API/VehicleData/GenericNetworkSignalData/036_5_Subscribtion_after_removing_VD_from_permissions_from_2_apps.lua, test_scripts/Defects/6_1/common_3139_3140_3142.lua, user_modules/sequences/actions.lua
Various fixes related to scripts stability.
Various fixes related to scripts stability and maintenance.
develop
- In two scripts for the `RGNSD` there was an issue for `HTTP` flow due to missing call of `isPTUStarted` function. `policyTableUpdateWithOnPermChange` function is replaced by `ptuWithPolicyUpdateReq` one which has such call.
- Sometimes `500ms` timeout for app activation is not enough especially for `EXTERNAL_PROPRIETARY` policy flow, so for issues related to streaming this timeout is increased
=> Improve stability of scripts #3

test_sets/policies_all_flows.txt, test_sets/policies_happy_paths_HTTP.txt
Re-add previously broken test after https://github.com/SmartDeviceLink/sdl_core/issues/1219 was fixed
* Re-add previously broken test to HTTP policy test set
=> Re-add fixed test to HTTP policy test set

test_scripts/WebEngine/026_PTU_snapshot_validation.lua, test_scripts/WebEngine/028_PTU_snapshot_validation_no_app_connected.lua, test_scripts/WebEngine/commonWebEngine.lua, test_sets/webengine.txt
Tests the changes for Core PR [#3349](https://github.com/smartdevicelink/sdl_core/pull/3349)
SDL Server implements the following pts validation logic:"
```
function validateCorePost (req, res) {
if (!req.body.policy_table) {
return res.errorMsg = "Please provide policy table information";
} else if (!req.body.policy_table.app_policies) {
return res.errorMsg = "Please provide app policies information";
} else if (!req.body.policy_table.consumer_friendly_messages) {
return res.errorMsg = "Please provide consumer friendly messages information";
} else if (!req.body.policy_table.device_data) {
return res.errorMsg = "Please provide device data information";
} else if (!req.body.policy_table.functional_groupings) {
return res.errorMsg = "Please provide …
```
=> Add validation to PT snapshot creation for webengine

test_scripts/Smoke/API/002_ResetGlobalProperties_PositiveCase_SUCCESS.lua, test_scripts/iAP2TransportSwitch/003_resume_failed_remove_data_check.lua
ATF Test Scripts to accomodate changes in https://github.com/smartdevicelink/sdl_core/pull/3357
Update expectations in `test_scripts/Smoke/API/002_ResetGlobalProperties_PositiveCase_SUCCESS.lua` to include `vrHelp` and `helpPrompt`.
Remove the expectation of appName to be sent as `vrHelpTitle ` in `test_scripts/iAP2TransportSwitch/003_resume_failed_remove_data_check.lua`
master
=> changes to accomodate sdl_core #3357

test_scripts/Policies/user_consent_of_Policies/221_ATF_Factory_reset.lua
Fix for #2355
Change incorrect reason in OnAppInterfaceUnregistered from IGNITION_OFF to FACTORY_DEFAULTS according to requirements.
develop
=> Actualization of the script 221_ATF_Factory_reset

test_scripts/Defects/6_2/2430_AppSendsRPCWIthProtocolVersionAboveMax_IsUnregistered.lua
ATF Test Scripts to check https://github.com/SmartDeviceLink/sdl_core/issues/2430
- Update Core's ini with { MaxSupportedProtocolVersion = 2, MalformedMessageFiltering = false }
- Start SDL Core and connect a mobile app
- Activate mobile app
- Send an RPC using a protocol above 2 (MaxSupportedProtocolVersion)
- App should be disconnected for protocol violation
latest
=> add script to check core issue 2430

test_scripts/API/SetAppIcon/commonIconResumed.lua, test_scripts/Defects/4_5/commonDefects.lua, test_scripts/Defects/5_0/1898_Canceling_HMILevel_resumption_of_media_app_after_unexpectedDisconnect.lua, test_scripts/Defects/5_0/2447_Resumption_revoked_app_still_be_resumed_as_FULL.lua, test_scripts/Defects/5_0/959_resumption_limited_non_media.lua, test_scripts/Defects/commonDefects.lua, test_scripts/Policies/App_Permissions/003_ATF_HP_User_Consent_Yes.lua, test_scripts/Policies/App_Permissions/004_ATF_HP_User_Consent_NO.lua, test_scripts/Policies/App_Permissions/005_ATF_DISALLOWED_app_Id_policies_And_RequestType_Validation.lua, test_scripts/Policies/App_Permissions/006_ATF_Steal_focus_validation_false_PTU.lua, test_scripts/Policies/App_Permissions/007_ATF_StealFocus_validation_true_PTU.lua, test_scripts/Policies/App_Permissions/024_ATF_APP_UNAUTHORIZED_If_Failed_Nickname_Validation_After_PTU.lua, test_scripts/Policies/App_Permissions/025_ATF_ChangeRegistration_With_AppName_Not_Listed_In_NickNames.lua, test_scripts/Policies/HMI_PTU/008_reseting_timeout_after_receiving_OnSystemRequest.lua, test_scripts/Policies/Policy_Table_Update/151_ATF_Apply_PTU_and_OnPermissionChange_notify.lua, test_scripts/Policies/Validation_of_PolicyTables/268_ATF_pt_update_validation_rules_general.lua, test_scripts/Policies/Validation_of_PolicyTables/280_ATF_Reset_ignition_cycles_since_last_exchange_in_PT.lua, test_scripts/Policies/Validation_of_PolicyTables/308_ATF_Check_app_registration_language_gui.lua, test_scripts/Policies/Validation_of_PolicyTables/312_ATF_Check_count_of_removals_for_bad_behavior_too_many_requests.lua, test_scripts/Policies/build_options/060_ATF_Timeout_to_wait_response_PTU_HTTP.lua, test_scripts/Policies/build_options/064_ATF_Received_PTU_From_Mobile_Application_HTTP.lua, test_scripts/Policies/build_options/072_ATF_PTU_PM_Sets_Status_UPDATE_NEEDED_HTTP.lua, test_scripts/SDL5_0/ConditionalResumption/common.lua, test_scripts/SDL5_0/Handling_VR_help_requests/commonVRhelp.lua, test_scripts/Smoke/commonSmoke.lua, test_scripts/WidgetSupport/common.lua, user_modules/sequences/actions.lua
Various fixes related to scripts which improve stability on a high loads.
develop
* added delay to disconnect function(s)
* added delay to connect function for `WSS` connection
* improved stability of Ignition Off sequence
* improved stability of some Policy scripts:
- moved app registration to separate test step
- added missing expectation on `OnHMIStatus(FULL)` in `ActivateAppInSpecificLevel() `function
- reworked script to get rid of `Unpin()` function
* [Bug Fix Info]
=> Improve stability of scripts #4

test_scripts/MobileProjection/Phase2/025_Media_app_must_get_ATTENUATED_streaming_state_when_navi_app_starts_streaming.lua, test_sets/SDL5_0/mobile_projection_2.txt
Update to fix #2404 
The first app should expect the changing of audioStreamingState back to `AUDIBLE` state, and the second app should expect 0 OnHMIlevel notification.
develop
=> Fixing of wrong OnHMIStatus expectation after streaming end 

test_scripts/WebEngine/028_PTU_snapshot_validation_no_app_connected.lua
028 script for Web Engine was designed to check if PTU is started without registered application. However for `HTTP` policy mode at least one registered application is required for PTU. So this script needs to be excluded for `HTTP` policy mode.
develop
* Added policy mode restriction to 028 script for Web Engine: only `PROPRIETARAY` and `EXTERNAL_PROPRIETARAY` modes are supported. 
* Removed unused code
=> Add restrictions to 028 script for Web Engine

test_scripts/RC/MultipleModules/commonRCMulModules.lua
Within merge of https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2419 it was introduced `string.match` function to validate `info` message. However 2nd argument of this function may have special characters that need to be escaped. These are ` ( ) . % + - * ? [ ^ $`. Unfortunately some tests failed since info message contains `[` character which is in the list:
```
./test_scripts/RC/MultipleModules/ModulesAllocation/052_ReleaseInteriorVehicleDataModule_current_app.lua
./test_scripts/RC/MultipleModules/ModulesAllocation/053_ReleaseInteriorVehicleDataModule_another_app.lua
./test_scripts/RC/MultipleModules/ModulesAllocation/054_ReleaseInteriorVehicleDataModule_free.lua	
```
develop
- Function `string.match` has replaced by regular `=`
=> Fix info msg check for RC Multiple Modules

test_sets/Defects/6_2/2395.txt, test_sets/Defects/6_2/955.txt, test_sets/Defects/Defects_release_7_0.txt
Introduced test set for fixed defects in scope of Release 7.0
develop
- Added new test set for defects of 7.0
- Removed obsolete test sets for 6.2
=> Test set for defects included in Release 7.0

test_scripts/API/SetAppIcon/commonIconResumed.lua, test_scripts/API/SubMenuIcon/commonSubMenuIcon.lua, test_scripts/CloudAppRPCs/commonCloudAppRPCs.lua, test_scripts/SDL5_0/TTSChunks/common.lua, test_scripts/smoke_api.lua, user_modules/shared_testcases/testCasesForExternalUCS.lua
Change removal of the storage folder to actually remove storage folder contents.
This is needed because in our parallel atf runner, I recently added a ramdisk mount at core's storage folder to ease the stress on disk. Now Core's backup thread will be writing to RAM instead of disk making the whole system faster. This causes one test to fail: `./test_scripts/CloudAppRPCs/010_get_icon_url.lua` because it cannot delete a folder that is a mount. This PR will enable all tests to pass with storage as a ramdisk.
latest
* core's storage folder can be a mount
=> delete contents of the storage folder instead of the entire folde

test_scripts/API/Additional_Submenus/001_additional_submenu_success.lua, test_scripts/API/Additional_Submenus/002_legacy_app_parentID_filtered.lua, test_scripts/API/Additional_Submenus/003_delete_nested_submenu_with_nested_submenu_and_commands.lua, test_scripts/API/Additional_Submenus/004_delete_top_level_submenu_with_nested_submenus_and_commands.lua, test_scripts/API/Additional_Submenus/005_duplicate_name_different_level_success.lua, test_scripts/API/Additional_Submenus/006_duplicate_name_same_level_fail.lua, test_scripts/API/Additional_Submenus/additional_submenus_common.lua, test_scripts/API/DriverDistractionCapability/001_get_driver_distraction_capability.lua, test_sets/additional_submenus_and_driver_distraction.txt, user_modules/hmi_values.lua
ATF Test Scripts to check #2084 & #2123
Add test scripts for checking parentID param for AddSubMenu requests and DRIVER_DISTRACTION system capability.
Develop
=> Add tests for additional submenus and driver distraction

test_scripts/Smoke/commonSmoke.lua
Fix issue with smoke tests for remote connection mode.
Tests were aborted with error:
```
Lua panic: ./modules/hmi_adapter/remote_hmi_adapter.lua:57: attempt to index field 'connection' (a nil value) (/home/developer/sdl/sdl_atf/src/remote_adapter/remote_adapter_client/lua_remote_library.cc:16)
```
develop
Function `SDL:StopSDL()` with condition has replaced by `StopSDL()` which stops SDL and cleans up all outstanding events and expectations.
=> Clean up all events in Smoke postconditions step

test_scripts/API/ShowAppMenu/commonShowAppMenu.lua, test_scripts/SDL5_0/MobileVersioning/VersionNegotiation/003_legacy_app_new_rpc_fail.lua, test_sets/SDL5_0/mobile_api_versioning.txt
ATF Test Scripts to check #[3466](https://github.com/smartdevicelink/sdl_core/issues/3466)
This PR is **Ready** for review.
Adds a test to check that an older app sending a newer rpc receives invalid data with an info string.
Develop
=> Add test to check legacy app sending newer rpc's

test_scripts/API/MainMenuUpdating/001_dynamic_update_capabilities_success.lua, test_scripts/API/MainMenuUpdating/002_on_update_file_success.lua, test_scripts/API/MainMenuUpdating/003_on_update_sub_menu_success.lua, test_sets/main_menu_updating_and_pagination.txt
ATF Test Scripts to check #[3212](https://github.com/smartdevicelink/sdl_core/issues/3212)
Adds some tests for main menu updating.
Test for checking the new displayCapability param
Test for an OnUpdateFile senario
Test for an OnUpdateSubMenu senario. 
Develop
=> Add main menu updating tests

test_scripts/Capabilities/PersistingHMICapabilities/017_getSystemCapability_use_default_capability_cache_is_not_exist.lua, test_scripts/Capabilities/PersistingHMICapabilities/018_getSystemCapability_use_default_does_not_contain_correspond_cap.lua, test_scripts/Capabilities/PersistingHMICapabilities/021_getSystemCapability_use_cache_capability.lua, test_scripts/Capabilities/PersistingHMICapabilities/common.lua
ATF Test Scripts to check Core pr: https://github.com/smartdevicelink/sdl_core/pull/3478/files
Add driver distraction capability to the persisting hmi capabilities tests
Develop
=> Add dd capability to persisting hmi capability tests

test_scripts/CloudAppRPCs/012_Same_app_name_mobile_app_Disallowed.lua, test_scripts/CloudAppRPCs/013_Same_app_name_mobile_app_Unregistered.lua
ATF Test Scripts to check #[3605](https://github.com/smartdevicelink/sdl_core/pull/3506)
This PR is **Ready** for review.
1. Change endpoint for cloud apps to be unique. Cloud apps shouldnt be sharing an endpoint.
2. Have the HMI send an ActivateApp request before registration to better simulate how cloud app activation works.
=> Fix endpoint and add hmi activateApp RPC

test_scripts/Resumption/Handling_errors_from_HMI/commonResumptionErrorHandling.lua
This update in scripts is required for https://github.com/smartdevicelink/sdl_core/issues/3502
Delay to send an error response from HMI is increased for the case when 2nd app is registered just after the 1st one.
This improves stability of the script.
develop
=> Fix delay in scripts for Resumption Error Handling

files/hmi_capabilities_SearchButton.json, files/hmi_capabilities_Without_PRESET9.json, test_scripts/API/ATF_RegisterAppInterface.lua, test_scripts/Capabilities/PersistingHMICapabilities/019_RAI_use_default_capability_does_not_contain_correspond_cap.lua, test_scripts/Capabilities/PersistingHMICapabilities/020_RAI_use_default_capability_cache_file_is_not_exist.lua, test_scripts/Capabilities/PersistingHMICapabilities/028_Suspending_of_RAI_request_processing_in_case_no_cap_response.lua, test_scripts/Capabilities/PersistingHMICapabilities/031_Suspending_of_RAI_request_processing_in_case_cache_file_does_not_exist_no_cap_response.lua, test_scripts/Capabilities/PersistingHMICapabilities/033_Suspending_of_RAI_request_processing_during_OnReady_in_case_no_cap_response.lua, test_scripts/Capabilities/PersistingHMICapabilities/034_Suspending_of_RAI_request_processing_during_OnReady_in_case_cache_file_does_not_exist_no_cap_response.lua, test_scripts/Capabilities/PersistingHMICapabilities/common.lua, test_scripts/Capabilities/pcmStreamCapabilities/commonPcmStreamCapabilities.lua
Updates in scripts due to changes introduced by [pull/3510](https://github.com/smartdevicelink/sdl_core/pull/3510)
Update for existing scripts.
develop
- Removed `RATE_` prefix for `bitsPerSample` and  `samplingRate` parameters
- Removed conversion logic for internal names
=> Get rid of internal name conversion for `bitsPerSample` and `samplingRate` parameters

test_scripts/WebEngine/WebEngineProjection/014_HMI_status_transitions_different_applications_interactions.lua, test_scripts/WebEngine/WebEngineProjection/027_OnExitApplication_RESOURCE_CONSTRAINT_multiple_apps_on_different_connections.lua
ATF Test Scripts to check [#2458](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2458)
Since scripts mentioned in issue have Mobile (TCP) and WebWngine (WS) connections for different apps, the idea is to force default mobile connection to `TCP` transport and retain `WS` for WebEngine connection.
develop
Force `TCP` transport for mobile connection
=> Force connection type in WebEngineProjection scripts

test_scripts/Capabilities/PersistingHMICapabilities/common.lua
Fix https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2455
The `hmiOnReady()` function does not work as expected if the SDL was built with `BUILD_WEBSOCKET_SERVER_SUPPORT=OFF` because SDL doesn't send UpdateDeviceList before the connectMobile()
Now additionalExp will contain UpdateDeviceList only if `BUILD_WEBSOCKET_SERVER_SUPPORT=ON` and GetSystemInfo if `BUILD_WEBSOCKET_SERVER_SUPPORT=OFF` 
develop
=> Update additionalExp for webSocketServerSupport == OFF

test_scripts/API/Additional_Submenus/007_non-existent_parentID.lua, test_sets/additional_submenus_and_driver_distraction.txt
ATF Test Scripts to check [#3524](https://github.com/smartdevicelink/sdl_core/issues/3524)
New script to verify the issue.
develop
2. Updated test set for `additional_submenus` feature
=> Add script to check #3524 issue

test_scripts/Protocol/NACKReason/005_Wrong_app_type_Video_Audio_Services_NACK.lua, test_scripts/Protocol/NACKReason/006_Wrong_HMI_level_Video_Audio_Services_NACK.lua, test_scripts/Protocol/NACKReason/007_Force_protected_Video_Audio_Services_NACK.lua, test_scripts/Protocol/NACKReason/008_Force_not_protected_Video_Audio_Services_NACK.lua, test_scripts/Protocol/NACKReason/009_PTU_failed_Video_Service_NACK.lua, test_scripts/Protocol/NACKReason/010_PTU_failed_Audio_Service_NACK.lua, test_scripts/Protocol/NACKReason/011_PTU_failed_RPC_Service_NACK.lua, test_scripts/Protocol/NACKReason/012_Invalid_time_Video_Service_NACK.lua, test_scripts/Protocol/NACKReason/013_Invalid_time_Audio_Service_NACK.lua, test_scripts/Protocol/NACKReason/014_Invalid_time_RPC_Service_NACK.lua, test_scripts/Protocol/NACKReason/015_Second_unprotected_Video_Audio_RPC_Services_NACK.lua, test_scripts/Protocol/NACKReason/016_SetVideoConfig_no_response_Video_Service_NACK.lua, test_scripts/Protocol/NACKReason/017_SetVideoConfig_error_response_Video_Service_NACK.lua, test_scripts/Protocol/NACKReason/018_SetVideoConfig_error_response_with_rejected_params_Video_Service_NACK.lua, test_scripts/Protocol/commonProtocol.lua, test_sets/protocol_nak_reason_param.txt
ATF Test Scripts to check #[3539](https://github.com/smartdevicelink/sdl_core/issues/3539)
ATF Test Scripts to Extending coverage for [Add a Reason Parameter to All Protocol NAKs](https://github.com/smartdevicelink/sdl_core/issues/3434)
Extending coverage for `Add a Reason Parameter to All Protocol NAKs`, scripts for issue #3539
develop
New test script to check the next reasons
- Invalid time
- Failed PTU
- Repeated start of second unprotected service
- Wrong HMI level
- Wrong HMI type
- Service start not according to settings in .ini file
=> [SDL-0308] Extending coverage for `Add a Reason Parameter to All Protocol NAKs`, scripts for issue #3539

test_scripts/WidgetSupport/Capabilities/008_GetSCs_no_app_specific_capabilities.lua, test_sets/widget_support.txt, user_modules/hmi_values.lua
Extended coverage for `GetSystemCapability(DISPLAYS)` and `SubtleAlert` parameters
develop
- Added new script
- Updated test set for `widget_support`
=> Extended coverage for GetSystemCapability and SubtleAlert parameters

test_scripts/Defects/4_5/1893_ATF_HeartBeat_App_does_not_send_HB_and_does_not_respond.lua
ATF Test Scripts update related to [#1892](https://github.com/smartdevicelink/sdl_core/issues/1892)
Along with the changes made in https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2476 script `1893` also needs to be updated.
develop
- switch on HB in ATF: in this way 1st HB message would be sent to SDL and hence SDL starts it's HB monitor
=> Update 1893 script

test_scripts/API/VehicleData/OnVehicleData/003_OnVD_disallowed_after_PTU.lua
Sometimes script:
```
./test_scripts/API/VehicleData/OnVehicleData/003_OnVD_disallowed_after_PTU.lua
```
may fail on PTU step with message:
```
expected: UP_TO_DATE, actual value: UPDATE_NEEDED
```
The reason of that is `odometer` trigger. 
In case if the difference between current odometer value and the one received on a previous PTU update exceeds `exchange_after_x_kilometers` parameter SDL triggers new PTU update.
develop
- replace random generated value for `odometer` in `OnVehicleData` by a hard-coded one (e.g. `1`). This would make `odometer` trigger is never happen.
=> Add hard-coded odometer value in VD script

test_scripts/API/VehicleData/GenericNetworkSignalData/commonGenericNetSignalData.lua
ATF Test Scripts to check [#3133](https://github.com/smartdevicelink/sdl_core/issues/3133)
Updates for Vehicle Data scripts related to "[SDL 0255] Enhance BodyInformation vehicle data" feature
[7.1.0_version_bump](https://github.com/smartdevicelink/sdl_atf/pull/217)
- updated common module for RGNSD tests with new parameters
=> [SDL 0255] Feature/Enhance BodyInformation vehicle data

test_scripts/API/KeyboardEnhancements/ResetGlobalProperties/001_App_resets_KeyboardProperties.lua, test_scripts/API/KeyboardEnhancements/Resumption/002_SDL_resumes_cached_KeyboardProperties.lua, test_scripts/API/KeyboardEnhancements/Resumption/003_SDL_resumes_cached_KeyboardProperties_with_removed_autoCompleteList.lua, test_scripts/API/KeyboardEnhancements/Resumption/004_SDL_resumes_cached_KeyboardProperties_single_parameter.lua
ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/pull/3635
Add expectation for maskInputCharacters in ResetGlobalProperties and in resumption cache
develop
* Add expectation for maskInputCharacters in ResetGlobalProperties and in resumption cache to match Core fix
=> Update keyboard property reset and cache expectations

test_scripts/API/AutoCompleteList/004_ResetGlobalProperties_SUCCESS.lua
Add change needed for core pr 3635
=> Add default input mask to resetGlobalProperties test

test_scripts/Policies/External_UCS/003_ATF_P_TC_LPT_Creation_PreloadedPT_without_disallowed_by_external_consent_entities_off_struct.lua, test_scripts/Policies/External_UCS/004_ATF_P_TC_LPT_Creation_PreloadedPT_with_disallowed_by_external_consent_entities_off_struct.lua, test_scripts/Policies/External_UCS/005_ATF_P_TC_LPT_Creation_PreloadedPT_without_disallowed_by_external_consent_entities_on_struct.lua, test_scripts/Policies/External_UCS/006_ATF_P_TC_LPT_Creation_PreloadedPT_with_disallowed_by_external_consent_entities_on_struct.lua, test_scripts/Policies/External_UCS/021_ATF_N_TC_PTU_with_disallowed_by_external_consent_entities_off_struct_with_invalid_type_of_params.lua, test_scripts/Policies/External_UCS/022_ATF_N_TC_PTU_with_disallowed_by_external_consent_entities_on_struct_with_invalid_type_of_params.lua, test_scripts/Policies/External_UCS/025_ATF_P_TC_LPT_Update_PreloadedPT_without_disallowed_by_external_consent_entities_off_struct.lua, test_scripts/Policies/External_UCS/026_ATF_P_TC_LPT_Update_PreloadedPT_with_disallowed_by_external_consent_entities_off_struct.lua, test_scripts/Policies/External_UCS/027_ATF_P_TC_LPT_Update_PreloadedPT_without_disallowed_by_external_consent_entities_on_struct.lua, test_scripts/Policies/External_UCS/028_ATF_P_TC_LPT_Update_PreloadedPT_with_disallowed_by_external_consent_entities_on_struct.lua, test_scripts/Policies/Policy_Table_Update/149_ATF_Policy_Table_Update_Trigger_After_N_Days.lua, test_scripts/Policies/Policy_Table_Update/172_ATF_PTU_request_after_N_ignition_cycles.lua, test_scripts/Policies/Validation_of_PolicyTables/280_ATF_Reset_ignition_cycles_since_last_exchange_in_PT.lua, test_scripts/Policies/Validation_of_PolicyTables/308_ATF_Check_app_registration_language_gui.lua, test_scripts/Policies/user_consent_of_Policies/221_ATF_Factory_reset.lua, user_modules/shared_testcases/testCasesForExternalUCS.lua
ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/pull/3649
Add expectation for BC.PolicyUpdate during InitHMI_OnReady in External Proprietary tests. 
develop
* Add expectation for BC.PolicyUpdate during InitHMI_OnReady in External UCS tests
* Add expectation for BC.PolicyUpdate during InitHMI_OnReady in Policy Table validation tests
* Add expectation for BC.PolicyUpdate during InitHMI_OnReady in Policy Table Update tests
* Add expectation for BC.PolicyUpdate during InitHMI_OnReady in user consent tests
=> Add expectations for HMI PTU in EXTERNAL_PROPRIETARY policy tests

test_scripts/Resumption/Handling_errors_from_HMI/002_successful_resumption_other_successful_result_codes.lua, test_scripts/Resumption/Handling_errors_from_HMI/027_resume_all_data_with_one_error_rpc_unexpected_disconnect_different_resultCodes.lua
ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/issues/3660
Modify tests for IsResponseSuccessful updates that will now consider result_code instead of info message
latest
=> update testing for resumption status codes

test_scripts/Smoke/API/028_AlertManeuver_PositiveCase_SUCCESS.lua, test_scripts/Smoke/API/044_AlertManeuver_Non_Media_PositiveCase_SUCCESS.lua
ATF Test Scripts to check #[1582](https://github.com/smartdevicelink/sdl_core/issues/1582)
Adding of appId check to AlertManeuver and Speak requests in smoke tests
[ATF version to use]
* Update with adding of appId check in existed smoke scripts for AlertManeuver RPC
=> [Issue-1582] Adding of appId check to AlertManeuver and Speak requests in smoke tests

test_scripts/Smoke/API/056_SendHapticData_PositiveCase_SUCCESS.lua, test_scripts/Smoke/commonSmoke.lua, test_sets/smoke_tests.txt
ATF Test Scripts to check #[3645](https://github.com/smartdevicelink/sdl_core/issues/3645)
Script with a check of successful processing of SendHapticData RPC  
develop
* Added new script with SendHapticData RPC 
* Updated smoke test set with new script
* Added permissions for SendHapticData RPC in common smoke file
=> Add SendHapticData RPC to the smoke

test_scripts/Defects/7_1/3620/common.lua
There is an instability of scripts for issue 3620:
https://github.com/smartdevicelink/sdl_atf_test_scripts/tree/develop/test_scripts/Defects/7_1/3620
Some scripts randomly failed with message:
```
HMI notification BasicCommunication.OnServiceUpdate: ValidIf: 
params.serviceEvent: expected: REQUEST_RECEIVED, actual value: REQUEST_ACCEPTED
params.serviceEvent: expected: REQUEST_REJECTED, actual value: REQUEST_RECEIVED
HMI notification BasicCommunication.OnServiceUpdate: Times: The most allowed occurences boundary exceed
```
develop
- Added expectation on `BC.OnServiceUpdate` into `startUnprotectedRPCservice()` function
=> Make stable scripts for issue 3620

test_scripts/API/VehicleData/SubscribeVehicleData/003_SubscribeVD_disallowed_after_PTU.lua, test_scripts/API/VehicleData/UnsubscribeVehicleData/003_UnsubscribeVD_disallowed_after_PTU.lua
Currently 2 scripts on VD below has incorrect list of parameters for `common.processRPCFailure()` function:
```
./test_scripts/API/VehicleData/SubscribeVehicleData/003_SubscribeVD_disallowed_after_PTU.lua
./test_scripts/API/VehicleData/UnsubscribeVehicleData/003_UnsubscribeVD_disallowed_after_PTU.lua
```
It leads to an issue that appropriate check doesn't work.
develop
- Fix list of parameters for `common.processRPCFailure()` function
=> Fix list of parameters in VD Subscribe/Unsubscribe scripts

test_scripts/API/SetAppIcon/commonIconResumed.lua
ATF Test Scripts to check #[issue number in sdl_core repository]
get `AppIconsFolder` from ini instead of assuming it is `storage`
tests `test_scripts/API/SetAppIcon` 2-6 and 10-11 were failing on a fresh build before these changes
latest
=> get AppIconsFolder value from ini config

user_modules/sequences/actions.lua
Within https://github.com/smartdevicelink/sdl_core/pull/2202 folder for icons had changed from `storage` to a `icons`
Appropriate clean up is required for a new folder.
https://github.com/smartdevicelink/sdl_atf/pull/227
- Added call of `SDL.AppIcons.clean()` function into `preconditions()`
=> Add clean up for AppIcons folder

test_scripts/Policies/Policy_Table_Update/148_ATF_HMILvl_on_PTU_affected_in_BACKGROUND_or_NONE.lua, test_scripts/Policies/Validation_of_PolicyTables/230_ATF_usage_and_error_counts_update_minutes_in_hmi_none.lua, test_scripts/Policies/Validation_of_PolicyTables/231_ATF_usage_and_error_counts_update_minutes_in_hmi_limited.lua, test_scripts/Policies/Validation_of_PolicyTables/232_ATF_usage_and_error_counts_update_minutes_in_hmi_full.lua, test_scripts/Policies/Validation_of_PolicyTables/233_ATF_usage_and_error_counts_update_minutes_in_hmi_background.lua, test_scripts/Policies/build_options/079_ATF_PTU_HMI_Level_Affected_Apps_NONE_BACKGROUND_HTTP.lua, test_scripts/SDL5_0/LowVoltage/common.lua, user_modules/all_common_modules.lua, user_modules/common_functions.lua, user_modules/shared_testcases/commonSteps.lua, user_modules/shared_testcases/testCasesForExternalUCS.lua, user_modules/shared_testcases_custom/commonSteps.lua
ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/pull/3686
Update `app_info.dat` path to account for it being stored in the `storage` folder.
https://github.com/smartdevicelink/sdl_atf/pull/226
* Update `app_info.dat` path to account for it being stored in the `storage` folder.
=> Update AppInfo path to account for Core changes

user_modules/sequences/actions.lua
Scripts are failing if run consecutively:
```
./test_scripts/API/RemoveUrlParameterMaxLength/002_StartStream.lua
./test_scripts/API/RemoveUrlParameterMaxLength/003_StartAudioStream.lua
```
develop
- Added clean up of `AppStorage` and `AppIcons` folders into `postconditions()` function
=> Add clean up of AppStorage and AppIcons folders into postconditions

test_scripts/Defects/8_0/3725_populate_GetUserFriendlyMessage.lua
ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/issues/3725
Add a new test to see if SDL Core includes data with the GetUserFriendlyMessage response.
=> Add Test for 3725, Ensure Core Populates GetUserFriendlyMessage

test_scripts/API/VehicleData/TireStatusMismatch/001_GetVD_TireStatus_default_values_for_old_app.lua, test_scripts/API/VehicleData/TireStatusMismatch/002_OnVD_TireStatus_default_values_for_old_app.lua, test_scripts/API/VehicleData/TireStatusMismatch/003_OnVD_TireStatus_default_values_for_different_apps_version.lua, test_scripts/API/VehicleData/TireStatusMismatch/common.lua, test_sets/tireStatus_mismatch.txt
ATF Test Scripts to check  [#2940](https://github.com/smartdevicelink/sdl_core/issues/2940)
ATF scripts to cover SDL behavior with old applications for the 'Update mismatch in TireStatus structure' feature
[8.0.0_version_bump](https://github.com/smartdevicelink/sdl_atf/tree/feature/8.0.0_version_bump)
- Add scripts to check default values for the old app
=> [SDL-0236] Update mismatch in TireStatus structure

test_scripts/Security/SecurityQueryErrorHandling/001_Invalid_query_size.lua, test_scripts/Security/SecurityQueryErrorHandling/002_Invalid_query_id.lua, test_scripts/Security/SecurityQueryErrorHandling/003_Service_not_protected.lua, test_scripts/Security/SecurityQueryErrorHandling/common.lua, test_sets/security.txt, user_modules/sequences/security.lua
ATF Test Scripts to check https://github.com/smartdevicelink/protocol_spec/issues/40
Adds tests for error handling in the security manager, depends on https://github.com/smartdevicelink/sdl_atf/pull/238
https://github.com/smartdevicelink/sdl_atf/pull/238
* Adds tests for "Send Internal Error" security query
=> Add tests for Security Query error handling

test_scripts/API/VehicleData/TireStatusMismatch/002_OnVD_TireStatus_default_values_for_old_app.lua, test_scripts/API/VehicleData/TireStatusMismatch/003_OnVD_TireStatus_default_values_for_different_apps_version.lua
Align VD scripts on Tire status with fix for https://github.com/smartdevicelink/sdl_core/issues/3368
develop
- Updated expectations in a way `OnVehicleData` notifications from HMI with empty structs shouldn't be transferred by SDL to Apps
=> Align VD scripts on Tire status with fix for 3368

test_scripts/API/VehicleData/GetVehicleData/011_GetVD_allowed_and_disallowed_after_PTU.lua, test_scripts/API/VehicleData/OnVehicleData/010_OnVD_allowed_and_disallowed_after_PTU.lua, test_scripts/API/VehicleData/SubscribeVehicleData/015_SubscribeVD_allowed_and_disallowed_after_PTU.lua, test_scripts/API/VehicleData/UnsubscribeVehicleData/012_UnsubscribeVD_allowed_and_disallowed_after_PTU.lua, test_scripts/API/VehicleData/common.lua, test_sets/API/vehicle_data.txt
Additional ATF scripts to check disallowed parameters for vehicle data RPCs.
These cover test cases when only one VD parameter is disallowed after PTU and other ones are still allowed.
develop
- Added new scripts and updated common file
- Updated test set for Vehicle Data
=> Extended coverage for disallowed parameters for vehicle data RPCs

test_scripts/Defects/4_6/842_App_does_not_activate_when_policies_are_disabled.lua
ATF Test Scripts to check [#2624](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2624)
Improve stability Activate App in scripts ./test_scripts/Defects/4_6/842_App_does_not_activate_when_policies_are_disabled.lua for script_issue 2624
develop
update test script for script issue 2624
=> Update test script for script issue 2624

test_scripts/API/ATF_OnAppInterfaceUnregistered.lua, test_scripts/Defects/7_1/3580_Revoked_app_activated_via_device_consent.lua
Updates in ATF Test Scripts for https://github.com/smartdevicelink/sdl_core/issues/2795
Message with AppUnauthorized code is more obvious for users when application is revoked.
develop
- Change massage code in applicable scripts
=> Changed messagecode for ActivateApp for revoked app

test_scripts/Policies/Policy_Table_Update/174_PTU_from_wrong_app.lua, test_scripts/Policies/Policy_Table_Update/175_PTU_from_wrong_app_HTTP.lua, test_scripts/Policies/build_options/078_ATF_PTU_HMI_Level_Affected_Apps_FULL_LIMITED_HTTP.lua, test_scripts/Policies/build_options/079_ATF_PTU_HMI_Level_Affected_Apps_NONE_BACKGROUND_HTTP.lua, test_scripts/Protocol/NACKReason/004_Invalid_Certificate_NACK.lua, test_scripts/TheSameApp/Policies/AppId/002_PTU_is_triggered_after_registration_app_with_different_app_id.lua, user_modules/sequences/actions.lua
ATF Test Scripts to fix https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2634
Test 078 and 079 had a failing PTU because no app was send OnSystemRequest notification, to allow their PTU the HMI sends an OnSystemRequest to be forwarded to mobile.
Test 004 is testing ServiceStart NAKs and is not policy dependent. Maintaining it for less policy flows will be easier and still provide us the same insight.
Latest
* Fix tests
=> Update HTTP Policy scripts affected by 0337

test_scripts/Defects/7_0/1903_Media_app_is_not_activated_during_active_embedded_navigation.lua
ATF Test Scripts to check [#2643](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2643)
Improve stability 'Activate media app step in scripts ./test_scripts/Defects/7_0/1903_Media_app_is_not_activated_during_active_embedded_navigation.lua
latest
add onHMIStatus for script issue in 1903_Media_app
=> Update test script for script issue in 1903_Media_app

test_scripts/API/ButtonSubscription/commonButtonSubscription.lua
ATF Test Scripts to check [#2657](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2657)
Improve stability Subscribe on Soft button in script ./test_scripts/API/ButtonSubscription/Capabilities/009_SubscribeButton_CUSTOM_BUTTON_resumption_IGN_OFF_ON_not_supported_by_HMI.lua
latest
add onHMIStaus Full during Activate app
=>  Update test script for script issue 2657

test_scripts/API/Restructuring_OnResetTimeout/021_BC_OnResetTimeout_for_GetInteriorVehicleDataConsent_without_SetInteriorVehicleData_response.lua, test_scripts/API/Restructuring_OnResetTimeout/022_BC_OnResetTimeout_for_GetInteriorVehicleDataConsent_and_SetInteriorVehicleData.lua, test_scripts/API/Restructuring_OnResetTimeout/024_BC_OnResetTimeout_for_GetInteriorVehicleDataConsent_without_ButtonPress_response.lua, test_scripts/API/Restructuring_OnResetTimeout/025_BC_OnResetTimeout_for_GetInteriorVehicleDataConsent_and_ButtonPress.lua
ATF Test Scripts to check #2659 
`delay` value is calculated by some trigger (e.g. receiving request) and in case this trigger is not activated the delay value is equal to the `nil` and script gets ABORTED status. (but should be FAILED because of timeout expiration)
Scripts stabilization regarding `delay` value  for `OnResetTimeout` functionality.
latest
Added check for `delay` value existence.
=> Scripts stabilization regarding `delay` value  for `OnResetTimeout` functionality

test_scripts/Defects/8_2/3912_PTS_With_WSS_App_Content_Length.lua, test_sets/Defects/Defects_release_8_2.txt
ATF Test Scripts to check #[3912](https://github.com/smartdevicelink/sdl_core/issues/3912)
develop (https://github.com/smartdevicelink/sdl_atf/commit/2645fc1aee1cd0026141c2b869cfc17cb6065bba)
=> Add scripts to verify defect 3912

test_scripts/RC/CLIMATE_RADIO/GetInteriorVehicleDataConsent/011_TIMED_OUT_after_default_timeout.lua, test_scripts/RC/commonRC.lua
ATF Test Scripts to check [#2671](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2671)
Improve stability SetInteriorVehicleData response in scripts:
./test_scripts/RC/CLIMATE_RADIO/GetInteriorVehicleDataConsent/011_TIMED_OUT_after_default_timeout.lua
Added defaultTimeoutCompensation for HMI response
latest
add DefaultTimeoutCompensation for SetIVD response
=> Update test script for issue 13031

test_scripts/Defects/5_0/2439_3014/common.lua
ATF Test Scripts update to fix scripts issue#[2687](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2687)
Scripts for 2439, 3014 are not applicable for external_proprietary policy flow, so this PR fixes this issue.
latest
Removed user consent prompt for "Location-1" policy group
=> Fix common file for 2439, 3014 for external_proprietary policies

test_scripts/Defects/8_1/2448_1_Master_Reset_Removes_AppInfo_Dat.lua, test_scripts/Defects/8_1/2448_2_Factory_Defaults_Removes_AppInfo_Dat.lua, test_sets/Defects/Defects_release_8_1.txt
ATF Test Scripts to check #[2448](https://github.com/smartdevicelink/sdl_core/issues/2448)
Extended coverage for checking of `app_info.dat` removing
latest
- updated file name in existed script with `MASTER_RESET`
- small correction for existed 2448 script
- created script for `FACTORY_DEFAULTS`
- updated 8_1 test set
=> Extended coverage for 2448 issue

test_scripts/Resumption/Handling_errors_from_HMI/013_resume_one_rpc_late_response_unexpected_disconnect.lua, test_scripts/Resumption/Handling_errors_from_HMI/014_resume_one_rpc_late_response_ign_off.lua, test_scripts/Resumption/Handling_errors_from_HMI/commonResumptionErrorHandling.lua
ATF Test Scripts to check [#2652](https://github.com/smartdevicelink/sdl_atf_test_scripts/issues/2652)
Improve stability Reregister App resumption in scripts:
./test_scripts/Resumption/Handling_errors_from_HMI/013_resume_one_rpc_late_response_unexpected_disconnect.lua
./test_scripts/Resumption/Handling_errors_from_HMI/014_resume_one_rpc_late_response_ign_off.lua
Added defaultTimeoutCompensation for HMI response
latest
add defaultTimeoutCompensation for HMI response
=> Test scripts for issue 2652
